packages/penelope/config/index.js
packages/penelope/src/shape.js

Penelope fix

---

packages/utils/src/formatMm/index.js

Closes freesewing/freesewing.org#317

Fixes bug due to not passing format to formatImperial

---

README.md

Fixes a few broken links in the README.

Update links in main README.md

---

packages/plugin-mirror/.babelrc
packages/plugin-mirror/CHANGELOG.md
packages/plugin-mirror/README.md
packages/plugin-mirror/package.json
packages/plugin-mirror/rollup.config.js
packages/plugin-mirror/src/index.js
packages/plugin-mirror/tests/mirror.test.js

closes #405 
The initial draft of mirror plugin, I have some tests I wrote to check results of `mirrorGen` and `lineValues` but am unsure how tests of plugin packages are run with lerna. Any pointers there would help.

Addition of mirror plugin

---

packages/plugin-mirror/src/index.js

Fix line slope equation for mirror plugin

---

packages/i18n/src/locales/en/options/wahid.yml

Corrected typo in description field of hemRadius:

Typo corrected

---

packages/hugo/src/pocket.js

Fix missing CutOnFold

---

packages/i18n/src/locales/en/app.yaml
packages/i18n/src/locales/en/email.yaml

fix minor typo in profile pic drag-and-drop instructions, add word for clarification in "change e-mail"-email

minor: fix typo, add word for clarification

---

packages/i18n/src/locales/en/options/jaeger.yml
packages/i18n/src/locales/en/options/sandy.yml

fixed typos in options of Sandy and Jaeger

minor fix: typos in options of Sandy, Jaeger

---

packages/i18n/src/locales/en/options/simon.yml
packages/i18n/src/locales/en/options/tamiko.yml

fix spelling of "width" in Simon options, add spaces in "shoulder seam" in Tamiko options

minor fix: typos in options of Tamiko, Simon

---

packages/aaron/config/index.js
packages/albert/config/index.js
packages/florent/config/index.js
packages/teagan/config/index.js
packages/titan/config/index.js
packages/waralee/config/index.js

I changed the difficulties of six FreeSewing patterns. The hope is that this review makes the difficulties more consistent.

Difficulty changes

---

packages/cathrin/src/panels.js

This issue was spotted by @nataliabarnhart and reported on Discord.
Rather than fix it outright, I'm creating a pull request so she can approve/merge it.

fix(cathrin): Fix for issue with panel 4

---

packages/tutorial/src/bib.js
packages/tutorial/src/step11.js

Update deprecated gendered snap snippets to new ones (see commit freesewing@dbda0bc)

 fix(dev:tutorial): update names of snap snippets 

---

markdown/org/docs/patterns/holmes/instructions/en.md

I was re-reading the method as I am planning to make up the drawings for this and realised Oh yea you can't understitch after closing the lining opening gg me,
Changes
-Steps 11 and 12 of Assembly and Lining Method 2 have been swapped
-Steps 11 and 13 now both state that they are optional or Alternates for each other.
-Tutorial changed to video as Bernadette Banner generally does not refer to these videos as tutorials and it is more of a visual aid rather than a tutorial.

Method re-evaluation. Holmes Construction en.md

---

LATEST_DEVELOPER_NEWS.md
LATEST_NEWS.md

@joostdecock Do these updates about v3 look okay?

Updated contributor call dates and project-2022 to v3

---

markdown/org/docs/patterns/yuri/instructions/en.md

Step 10 had a line break that was causing the title markdown to not function properly. Hopefully this will make it work.

Yuri Step 10 format change.

---

markdown/org/docs/measurements/bustpointtounderbust/en.md

New bustpointtounderbust doc page. I liked @joostdecock's explanation in discord a lot, so I took the liberty of copying it here.
Related: https://github.com/freesewing/backend/pull/526 and https://github.com/freesewing/freesewing.org/pull/1471.

feat: create bustpointtounderbust doc page

---

packages/holmes/src/ear.js
packages/holmes/src/gore.js

Slight change to the paperless of the gore and ear pieces that was missed after changing the bottom seam allowances.
Changes
- Changed Gore "vd" paperless to have sa*2
- Changed Ear "hd" paperless to have sa*2

Holmes - Minor Paperless Changes

---

markdown/org/docs/patterns/albert/instructions/en.md

Resolves #1082 
Have been working with Wouter to create Albert Instructions
Added
- Albert Instructions

Albert Instructions

---

markdown/org/docs/patterns/cornelius/cutting/en.md
markdown/org/docs/patterns/cornelius/fabric/en.md
markdown/org/docs/patterns/cornelius/instructions/en.md
markdown/org/docs/patterns/cornelius/needs/en.md

Have been working with Wouter on Cornelius Docs.
Added
- Cornelius Cutting
- Cornelius Fabric Options
- Cornelius What you need
Changes
- More in depth Instructions

Cornelius Documentation Update

---

markdown/org/docs/patterns/bella/instructions/en.md

Added
- More info in Step 2 tip
Changed
- Reverted back to bullet points

Minor Changes to Bella Construction

---

markdown/org/docs/patterns/bent/instructions/en.md

- Removed sew sleeve side seam as that is covered in previous as it is a two part seam.
Additions 
- Note about leaving the bottom of one of the sleeves seams open to put on.

Minor Changes to Bent Instructions

---

markdown/org/docs/patterns/bella/instructions/en.md

Changes
- Changed right sides to good sides.

Minor Changes to Bella Instructions

---

markdown/org/docs/patterns/breanna/cutting/en.md
markdown/org/docs/patterns/breanna/needs/en.md

Added Sleeves to Breanna Cutting

---

markdown/org/docs/patterns/charlie/options/crossseamcurveangle/en.md
markdown/org/docs/patterns/charlie/options/crotchseamcurveangle/en.md

Added
- Cross Seam Angle
- Crotch Seam Angle
I took the info from the Pattern like I did from Breanna but they may be a little vague.

Charlie Missing Options

---

markdown/org/docs/patterns/brian/cutting/en.md
markdown/org/docs/patterns/brian/fabric/en.md
markdown/org/docs/patterns/brian/instructions/en.md
markdown/org/docs/patterns/brian/needs/en.md

Added
- Brian Instructions
- Brian What you need
- Brian Fabric Options
Changes
- Minor formatting to Brian Cutting
- Added a tip to Brian Cutting

Brian Documentation Update

---

markdown/org/docs/patterns/yuri/instructions/en.md

After updating Hugo realised that Yuri's neckband info was not properly adapted for Yuri as it has an opening unlike Hugo. Should be fixed now.

Minor Changes to Neckband Info of Yuri

---

markdown/org/docs/patterns/hugo/instructions/en.md

Fix for #1494
Taken from Yuri which takes it from Hugo's video tutorial. This does mean that Yuri's is actually slightly incorrect so will need to fix that too.

Fix for #1494 Added info on how to make a neckband 

---

markdown/dev/tutorials/pattern-design/en.md

Raised from https://github.com/freesewing/freesewing/issues/1514

feat: Adds link to reference bib code in tutorial start

---

markdown/org/docs/patterns/huey/cutting/en.md
markdown/org/docs/patterns/huey/instructions/en.md
markdown/org/docs/patterns/huey/needs/en.md

The instructions will probably need a proof read as it is late for me when I did this.
Also the zipper instructions may need double checking.
Added
- Huey Cutting
- Huey What you need
- Huey Instructions

Huey Documentation Update

---

markdown/org/docs/patterns/simone/cutting/en.md
markdown/org/docs/patterns/simone/fabric/en.md
markdown/org/docs/patterns/simone/instructions/en.md
markdown/org/docs/patterns/simone/needs/en.md

Noticed the links for Simon Pattern were broken so have fixed those. Also took the oppurtunity to update the Instructions slightly so people understand to close the bust darts etc.

Simone Fixed Links

---

markdown/org/docs/patterns/penelope/cutting/en.md
markdown/org/docs/patterns/penelope/fabric/en.md
markdown/org/docs/patterns/penelope/instructions/en.md
markdown/org/docs/patterns/penelope/needs/en.md

Changes
- Updated Penelope Cutting
- Updated Penelope Fabric options
- Updated Penelope Instructions
- Updated Penelope What you need
This is mostly a re-format of the pages to bring the inline with the others however more info has been added in some places that were lacking, The Construction instructions are still quite barebones but they now have a little more info then they did before and they now have bullet points. But due to the many ways to construct a skirt this is not a big deal.

Penelope Documentation Update

---

markdown/org/docs/patterns/penelope/instructions/en.md

Why do I only notcie these things after they have been merged I'm so sorry.

Singular not Plural, Penelope Instructions

---

markdown/org/docs/patterns/penelope/instructions/en.md

Sorry, just a few typos I spotted after re-reading it again.

Minor typos Penelope Instructions

---

markdown/org/docs/patterns/brian/fabric/en.md

A minor miss when copy and pasting

Brian not Breanna

---

markdown/org/docs/patterns/titan/cutting/en.md
markdown/org/docs/patterns/titan/fabric/en.md
markdown/org/docs/patterns/titan/instructions/en.md
markdown/org/docs/patterns/titan/needs/en.md

The last and final block is done.
Felt like Titan was a little left out from the documentation game but also best for the Blocks to be all sort of inline with eachother.

Titan Documentation Update

---

markdown/dev/tutorials/pattern-design/conclusion/en.md

feat: Adds link to beginner pattern ideas from developer site

---

markdown/dev/tutorials/pattern-design/conclusion/en.md

Would resolve - https://github.com/freesewing/freesewing/issues/1630 if merged

fix: Updates open patterns link in tutorial

---

config/dependencies.yaml

Attempting to address a build failure in #1649. See https://github.com/freesewing/freesewing/pull/1649#issuecomment-1013638582.

Add babel/core to dev deps.

---

markdown/org/docs/patterns/simon/options/roundback/en.md

I'm hoping this is correct and my wording makes sense.
This should close  #1187 as this is the last one on the list.

Round Back Info for Simon(e) Option

---

markdown/dev/tutorials/pattern-design/completing-the-neck-opening/en.md

Related to [this PR](https://github.com/freesewing/freesewing/pull/1640).
Updated this code block to reflect the instructions and previous step where a quarterNeck path was created.

Update code block in tutorial

---

markdown/dev/howtos/dev/freesewing-org/en.md

Updating documentation to add the steps to init and update the submodule. Also adding context about the move to monorepo and that the instructions are subject to change.

Update steps to run freesewing.org locally

---

markdown/dev/guides/patterns/en.md
markdown/dev/guides/patterns/paths/en.md
markdown/dev/guides/translation/en.md
markdown/dev/reference/api/pattern/en.md
markdown/dev/tutorials/getting-started-mac/installing-nvm/en.md

Fixing some minor text issues in reviewing the freesewing.dev documentation

Minor text fixes

---

markdown/org/docs/patterns/sandy/cutting/en.md
markdown/org/docs/patterns/sandy/fabric/en.md
markdown/org/docs/patterns/sandy/instructions/en.md
markdown/org/docs/patterns/sandy/needs/en.md

This was a tricky one but this is most certainly a start.
I have had to split the instructions in two, One for seamless, One for closures.
I'm hoping this is less confusing than having them combined but time will tell.
Due to circle skirts having many options on both construction and styles a lot of this is a guide line rather than a full set of methods though you could say that about any pattern.
I have proof read these but knowing me I may have missed one or two. 
This at least gives a ground-work for anyone who comes along and wants to be the ambassodor of the pattern.

Sandy Documentation Update

---

markdown/org/docs/patterns/holmes/instructions/en.md

After re-formatting some of the numbers in number remained and needed removing. I was waiting to get some diagrams/pictures done before updating but that may be a minute so have opted just to sort it now.

Removing Repeat Step Numbers - Holmes Instructions

---

markdown/org/docs/patterns/tamiko/instructions/en.md

Additions
- Step 3: Enjoy! Didn't want Tamiko missing out
Changes
- Steps re-formated to bullet points to bring in line with others.
- Added a little more info about the three seamlines though the diagram does most of the work. Also is there a missing letter D on the digaram?

Minor Update Tamiko Instructions

---

packages/i18n/src/locales/en/options/holmes.yml

Adding the missing Holmes Pattern Options and updating the existing to reflect the name changes.

Update holmes.yml  Added missing options.

---

markdown/org/docs/patterns/holmes/instructions/en.md

Typo in the Ear Flap with Ties note, changed it slightly so the wording flows better and removes the typo.

fix(docs) Holmes typo in Step 3 Note

---

README.md

add NoteJS version to the quickstart instructions

---

markdown/org/docs/patterns/holmes/options/gores/de.md
markdown/org/docs/patterns/holmes/options/gores/en.md
markdown/org/docs/patterns/holmes/options/gores/es.md
markdown/org/docs/patterns/holmes/options/gores/fr.md
markdown/org/docs/patterns/holmes/options/gores/nl.md

https://freesewing.org/docs/patterns/holmes/options/gores

Fix broken gore image link.

---

markdown/org/docs/patterns/bee/options/bandlength/en.md
markdown/org/docs/patterns/bee/options/bellaguide/en.md
markdown/org/docs/patterns/bee/options/crossbackties/en.md
markdown/org/docs/patterns/bella/options/backdartheight/en.md
packages/bee/config/index.js
packages/i18n/src/locales/en/optiongroups.yaml
packages/i18n/src/locales/en/options/bee.yml

Was originally suppsoe to be just a little tidy up and adding yml info has divulged a little
Additions
- Add missing options to bee.yml
- Added more info to Show bella Doc
- Added more info to Cross Back Ties Doc
Changes
- Changed Cross Back Ties opening scentence doc
- Changed Cross Back Ties in yml
- Changed fullChestEaseReduction to a slider
- Fixed some typos
I am debating whether it is prudent to add links from the Bee options to their corresponding Bella options though? If it is I'll get right on it.

update(yml, docs, config) Bee

---

packages/i18n/src/locales/en/options/holmes.yml

Semi-sphere does not indicate properly what part of the pattern this options affects.

update(yml) Holmes. Crown not Semi-sphere

---

README.md

See https://github.com/freesewing/freesewing/issues/1737#issuecomment-1022935461

Revert README.md changes made in a2a4e2a.

---

config/templates/readme.main.md

Better than https://github.com/freesewing/freesewing/pull/1742

Really add NodeJs to README.

---

packages/plugin-theme/package.json
packages/plugin-theme/src/index.js
packages/plugin-theme/src/lib/paperless.js
packages/plugin-theme/src/lib/sample.js
packages/plugin-theme/src/scss/sample.scss

See #1656
Tested this by loading the change in `plugintest`. I could see my changes to paperless in the exported svg.

Remove Sass from plugin-theme.

---

packages/backend/README.md
packages/backend/example.env

I had some trouble getting the backend running locally with `docker-compose up`. The first error was about missing `FS_JWT_ISSUER`. The second was a failure to connect to the local database.

Update backend example.env and README.

---

markdown/org/docs/patterns/lunetius/cutting/en.md
markdown/org/docs/patterns/lunetius/fabric/en.md
markdown/org/docs/patterns/lunetius/instructions/en.md
markdown/org/docs/patterns/lunetius/needs/en.md

I meant to have put this as a comment yesterday sorry.
This just adds the standard fromat to the wonderful updates made by @SeaZeeZee

update(docs) Lunetius re-formatting new updates

---

packages/plugin-bartack/tests/plugin.test.mjs
packages/plugin-bust/tests/plugin.test.mjs
packages/plugin-buttons/tests/plugin.test.mjs
packages/plugin-cutonfold/tests/plugin.test.mjs
packages/plugin-dimension/tests/plugin.test.mjs
packages/plugin-flip/tests/plugin.test.mjs
packages/plugin-gore/tests/plugin.test.mjs
packages/plugin-measurements/tests/plugin.test.mjs
packages/plugin-notches/tests/plugin.test.mjs

From https://github.com/freesewing/freesewing/pull/1521
FYI: I left out several tests like "Should set the plugin name:version attribute" because I found that there is similar test included by default in the "Shared Plugin Tests". See [tests/plugins/shared.mjs](https://github.com/freesewing/freesewing/blob/develop/tests/plugins/shared.mjs).

Add some plugin unit tests.

---

packages/simon/src/sleeve.js

Grainline point altered so grainline is straight. Take two because extra commit that should have stayed local.

sleeve grainline alteration

---

markdown/dev/guides/markdown/frequent-mistakes/en.md

Added documentation on frequent mistakes in Markdown #1513

Markdown Documentation Frequent Mistakes

---

markdown/dev/guides/markdown/frequent-mistakes/en.md

Added heading for custom components examples see  #1808

---

packages/i18n/src/locales/en/options/waralee.yml

I'm not sure when the options were updated but the yml hadn't been. This should bring it upto date.

fix(yml) Warlaee Pattern Options

---

.github/workflows/checkdocs.yml
markdown/dev/reference/api/config/options/pct/snap/en.md
markdown/dev/reference/api/path/intersects/en.md
markdown/dev/tutorials/getting-started-windows/en.md
markdown/org/docs/faq/what-is-freesewing/fr.md
markdown/org/docs/guide/account/de.md
markdown/org/docs/guide/account/en.md
markdown/org/docs/guide/account/es.md
markdown/org/docs/guide/account/fr.md
markdown/org/docs/guide/account/nl.md
markdown/org/docs/patterns/breanna/options/fr.md
markdown/org/docs/patterns/brian/options/fr.md
markdown/org/ui/homepage/extra/de.md
markdown/org/ui/homepage/extra/es.md
markdown/org/ui/homepage/extra/fr.md
markdown/org/ui/homepage/extra/nl.md
package.json

- Fix remaining issues.
- Change command to use `--use remark-preset-lint-consistent --use remark-preset-lint-recommended`
- Add workflow.

Add checkdocs workflow.

---

packages/teagan/src/sleeve.js

Fix Teagan sleeve title.

---

markdown/org/docs/patterns/teagan/instructions/en.md

https://github.com/freesewing/freesewing/issues/1936

Update Teagan left/right sleeve instructions.

---

markdown/org/docs/patterns/charlie/cutting/en.md

I cut two, not paying close attention and then halfway through construction realised I needed 2x2 = 4

Making it more clear you need four pocket facings

---

packages/charlie/src/front-pocket-facing.js

feat(charlie): Add notches to front pocket facing. Closes #1991

---

packages/core/src/path.js

Wouter found a novel way to break things. I fixed in in his fork, and this is the backported fix.
Essentially, it checks that the point we're splitting a path on lies on the start/end of a path segment (a curve or line) and if so doesn't split the path, but rather divides it at that point.
This is needed because splitting on the actual endpoint (or a point very close to it) will result in a path operation that draws a line or curve between two (almost) identical points.
And in the `path.offset()` method, we thrown out those sort of things, resulting in weird behaviour in `path.offset` (and the `pd` macro).
Since offsetting Bezier paths is dark voodoo stuff, best to handle this prior to that, and don't split beziers (or lines) when the split point is one of its end/start points.

fix(core): Handle path split on start/end of path segments

---

markdown/org/docs/patterns/lucy/cutting/en.md
markdown/org/docs/patterns/lucy/fabric/en.md
markdown/org/docs/patterns/lucy/instructions/en.md

Some Re-formatting of Lucy's Doc to bring in-line. I'll admit I got a little carried away with the instructions and made some additions.

Lucy Documentation Re-Format

---

markdown/org/docs/patterns/theo/instructions/en.md

Fingers crossed this will fix errors around markdown, otherwise revert.

Change quotes to tips

---

packages/freesewing.dev/hooks/useApp.js
packages/freesewing.lab/hooks/useApp.js
packages/freesewing.org/hooks/useApp.js
packages/freesewing.shared/components/wrappers/workbench.js
packages/freesewing.shared/hooks/useLocalStorage.js
packages/freesewing.shared/hooks/useTheme.js

the way localstorage was working was giving me errors with hydration. These new hooks use the react lifecycle to make changes after mounting

Fix hydration errors due to localstorage

---

sites/shared/components/workbench/draft/part/index.js
sites/shared/components/workbench/menu/core-settings/core-setting-sa-bool.js
sites/shared/components/workbench/menu/core-settings/core-setting-sa-mm.js
sites/shared/components/workbench/menu/view.js
sites/shared/components/wrappers/workbench.js
sites/shared/hooks/useGist.js

continuing, but hopefully ending the #2281 saga. I searched for all mentions of gist in the `sites` folder and made sure everyone was using the new methods correctly. The only things that were having trouble still were ClearThing and seam allowance, and they are now working. I tried to click around everywhere in the lab to make sure it all looked good, and as far as I could tell, it did.

all gist mutation now uses the new functions

---

markdown/org/docs/patterns/hi/cutting/en.md
markdown/org/docs/patterns/hi/fabric/en.md
markdown/org/docs/patterns/hi/instructions/en.md
markdown/org/docs/patterns/hi/needs/en.md
markdown/org/docs/patterns/hi/options/aggressive/en.md
markdown/org/docs/patterns/hi/options/hungry/en.md
markdown/org/docs/patterns/hi/options/nosePointiness/en.md
markdown/org/docs/patterns/hi/options/size/en.md

Just doing some re-formatting and minor updating to Hi's Docs before it goes out.
Adds a bit more info to some areas and re-formats some of the docs for better UI. 
Thanks to @tangerineshark for some help with the wording.

Hi Documentation Update

---

packages/i18n/src/locales/en/optiongroups.yaml

Adding type for the new option group created by Noble.
Edit: Noticed Bob had the new option group size as well so added to this.

add(optiongroups.yaml) Added Type and Size for Noble & Bob

---

markdown/org/docs/patterns/hi/options/size/en.md

Name of pattern is not present for Design Option titles so have removed.

Incorrect Title Format Hi Size Design Option page

---

markdown/org/docs/patterns/hi/instructions/en.md
markdown/org/docs/patterns/hi/needs/en.md

Forgot to add these in the previous update my bad.
Additions
- Eye and Gill needs 
- Eye and Gill instructions
Changes
- Number of steps

add(Hi Docs) Added info on gills and eyes.

---

markdown/org/docs/patterns/noble/options/dartPosition/en.md

Noticed this was missing and simply adds it in using parts of the yml language as a reference.

Adding Noble's missing Dart Position page.

---

markdown/org/docs/patterns/bee/options/shouldertoshoulderease/en.md
packages/i18n/src/locales/en/options/bee.yml

Simply adds the Shoulder to Shoulder ease like the other Bella options of Bee.

Bee adding Shoulder to Shoulder Info

---

sites/lab/page-templates/design-list.js
sites/shared/components/layouts/default.js
sites/shared/package.json
yarn.lock

Just some missing stuff that's breaking develop

Fix problem imports in develop

---

plugins/plugin-grainline/src/index.js

This requires #2502 to be merged

feat(plugin-grainline): Set part grain in macro

---

plugins/plugin-cutonfold/src/index.js

feat(plugin-cutonfold): Set part cutonfold/grain in macro

---

markdown/org/docs/patterns/bob/options/lengthratio/en.md
markdown/org/docs/patterns/bob/options/neckratio/en.md
markdown/org/docs/patterns/bob/options/widthratio/en.md

Takes the info from the .yml file and adds a little more info where required.
Additions
- Added Length Ratio Info
- Added Width Ratio Info
- Added Neck Ratio Info
I am aware that the bias binding is being written so pushed up the timeline on working on these. May still need some info here or there. I have added a link to neckRatio so that may need a once over just to make sure I formatted it correctly.

add(info) Bob Pattern Options

---

sites/shared/prebuild/i18n.mjs

Used @woutervdub 's instructions from here: https://discord.com/channels/698854858052075530/970129333895180310/970375280881446983

Update Waralee pocket instructions

---

CHANGELOG.md
config/changelog.yaml
designs/cathrin/src/panel1ab.js

(This PR also re-alphabetizes CHANGELOG.md by moving the `aaron` section up.)

fix (cathrin): Remove seam allowance from Part1a foldline. Fixes #2545

---

markdown/dev/guides/best-practices/respect-draft-settings/en.md
markdown/dev/guides/plugins/hooks/en.md
markdown/dev/guides/plugins/loading-build-time-plugins/en.md
markdown/dev/howtos/code/shorthand/en.md
markdown/dev/reference/api/hooks/postsample/en.md
markdown/dev/reference/api/hooks/presample/en.md
markdown/dev/reference/api/part/units/en.md
markdown/dev/reference/api/path/trim/en.md
markdown/dev/reference/api/point/clone/en.md
markdown/dev/reference/api/point/copy/en.md
markdown/dev/reference/api/point/rotate/en.md
markdown/dev/reference/api/point/shiftfractiontowards/en.md
markdown/dev/reference/api/point/shifttowards/en.md
markdown/dev/reference/api/settings/sa/en.md
markdown/dev/reference/api/snippet/en.md
markdown/dev/reference/api/utils/beamintersectsx/en.md
markdown/dev/reference/api/utils/beamintersectsy/en.md
markdown/dev/reference/api/utils/beamsintersect/en.md
markdown/dev/reference/api/utils/curveintersectsx/en.md
markdown/dev/reference/api/utils/curveintersectsy/en.md
markdown/dev/reference/api/utils/linesintersect/en.md
markdown/dev/reference/api/utils/pointonline/en.md
markdown/dev/tutorials/pattern-design/new-design/en.md
markdown/dev/tutorials/pattern-design/part-structure/en.md
markdown/dev/tutorials/pattern-design/testing-your-pattern/en.md

Also update one `yarn` instruction.

fix: Broken links to the API reference

---

designs/lucy/src/pocket.js
markdown/org/docs/patterns/lucy/cutting/en.md
markdown/org/docs/patterns/lucy/en.md
markdown/org/docs/patterns/lucy/fabric/en.md
markdown/org/docs/patterns/lucy/instructions/en.md
markdown/org/docs/patterns/lucy/needs/en.md
markdown/org/docs/patterns/lucy/options/edge/en.md
markdown/org/docs/patterns/lucy/options/length/en.md
markdown/org/docs/patterns/lucy/options/width/en.md

This PR adds documentation for Lucy!

Lucy documentation

---

designs/wahid/config/index.js
designs/wahid/src/back.js
designs/wahid/src/front.js
designs/wahid/src/frontfacing.js
designs/wahid/src/frontlining.js
designs/wahid/src/pocketbag.js
designs/wahid/src/pocketfacing.js
designs/wahid/src/pocketinterfacing.js
designs/wahid/src/pocketwelt.js
packages/i18n/src/next.mjs

Wahid grainlines, issue 2564

---

markdown/org/docs/patterns/noble/options/armholedartposition/en.md
markdown/org/docs/patterns/noble/options/armholedepth/en.md
markdown/org/docs/patterns/noble/options/backarmholecurvature/en.md
markdown/org/docs/patterns/noble/options/backarmholepitchdepth/en.md
markdown/org/docs/patterns/noble/options/backarmholeslant/en.md
markdown/org/docs/patterns/noble/options/backdartheight/en.md
markdown/org/docs/patterns/noble/options/backhemslope/en.md
markdown/org/docs/patterns/noble/options/backneckcutout/en.md
markdown/org/docs/patterns/noble/options/bustspanease/en.md
markdown/org/docs/patterns/noble/options/chestease/en.md
markdown/org/docs/patterns/noble/options/frontarmholecurvature/en.md
markdown/org/docs/patterns/noble/options/frontarmholepitchdepth/en.md
markdown/org/docs/patterns/noble/options/frontshoulderwidth/en.md
markdown/org/docs/patterns/noble/options/highbustwidth/en.md
markdown/org/docs/patterns/noble/options/shoulderdartposition/en.md
markdown/org/docs/patterns/noble/options/shouldertoshoulderease/en.md
markdown/org/docs/patterns/noble/options/upperdartlength/en.md
markdown/org/docs/patterns/noble/options/waistdartlength/en.md
markdown/org/docs/patterns/noble/options/waistease/en.md
packages/i18n/src/locales/en/options/noble.yml

Additions
- Added frontArmholeCurvature to the yml file.
Changes
- Removed duplicated titles in pattern options that I suspect happened when the images were created.
That's it minor visual changes.

(docs fix) Noble Pattern options; add missing yml and removal of duped titles.

---

sites/backend/src/controllers/github.js

I botched my old PR #2655 branch as a result of some pull/merge conflict. I had to create a new branch and resubmit this new PR.
I believe that I can use the bare `?` and `&` characters directly in the URL, without having to encode them?

Add Lab and remove Workbench and Next gist re-creation links.

---

packages/core/src/pattern.mjs

Before the fix:
After the fix:

Change v3 pattern raise.info message to use new data property config.

---

markdown/org/docs/faq/breasts/en.md

The section on breast binding confused me at first due to the generic nature of the word 'binding'. This commit attempts to clarify this point to make it more readily understandable for a broader audience — hopefully without introducing exclusive or unsuitable language.

Clarify the meaning of 'binding'

---

designs/yuri/src/back.mjs
designs/yuri/src/front.mjs
designs/yuri/src/gusset.mjs
designs/yuri/src/hoodcenter.mjs
designs/yuri/src/hoodside.mjs
designs/yuri/src/sleeve.mjs

A PR into the v3-stage2 branch.
(This is a straight stage 2 port, without any extra changes like prettier.)

chore(yuri): Port to v3 stage 2

---

designs/walburga/src/back.mjs
designs/walburga/src/base.mjs
designs/walburga/src/front.mjs

A PR into the v3-stage2 branch.

chore(walburga): Port to v3 stage 2

---

designs/wahid/src/back.mjs
designs/wahid/src/front.mjs
designs/wahid/src/frontfacing.mjs
designs/wahid/src/frontlining.mjs
designs/wahid/src/pocketbag.mjs
designs/wahid/src/pocketfacing.mjs
designs/wahid/src/pocketinterfacing.mjs
designs/wahid/src/pocketwelt.mjs

A PR back into the v3-stage2 branch.

chore(wahid): Port to v3 stage 2

---

designs/penelope/src/shape.mjs
designs/penelope/src/utils.mjs

Fix issues with penelope.
dart placement
dart shape
dart size and placement correction
add optional measurements for better fit

Penelope fixes

---

designs/plugintest/src/plugin-title.mjs

(This is a re-submit of https://github.com/freesewing/freesewing/pull/2895 because my original PR branch got messed up with unwanted commits accidentally included.)
I made the code changes to use `store.set()` and `store.unset()`.

chore(plugintest): Convert Title to use v3 "for" store data.

---

markdown/dev/guides/prerequisites/en.md

If someone has questions, might as well arm them with the discord link early on.

Added link to discord

---

packages/new-design/templates/from-bent/design/src/topsleeve.mjs.mustache
packages/new-design/templates/from-bent/design/src/undersleeve.mjs.mustache

The search/replace operation wasn't done for these 2 from-bent source files to change "back" to the correct part.

fix(new-design): Change from-bent topSleeve and underSleeve references to back.

---

markdown/dev/tutorials/pattern-design/adding-measurements/en.md

Format from feedback in https://github.com/freesewing/freesewing/pull/3115

fix: Adjusts wording to suggested format

---

markdown/dev/reference/api/en.md

fix(docs): utils.round() missing from Core API

---

packages/core/src/utils.mjs

The only substantial change is the @return for `curveEdge()`.

fix(core) Small corrections to utils.mjs comments

---

markdown/dev/guides/plugins/loading/en.md
markdown/dev/reference/plugins/bust/en.md

(Minor fixes found when reviewing the Part Plugins page. The majority of plugins documentation is still to be reviewed.)

fix(docs): Corrections to plugin documentation.

---

markdown/dev/reference/api/part/config/measurements/en.md

I am not sure, but I think these are typos that should be fixed.

fix(docs): Part measurements fix

---

markdown/dev/reference/api/part/config/options/counter/en.md
markdown/dev/reference/api/part/config/options/deg/en.md
markdown/dev/reference/api/part/config/options/en.md
markdown/dev/reference/api/part/config/options/extend/en.md
markdown/dev/reference/api/part/config/options/list/en.md
markdown/dev/reference/api/part/config/options/mm/en.md
markdown/dev/reference/api/part/config/options/pct/en.md
markdown/dev/reference/api/part/config/options/pct/fromabs/en.md
markdown/dev/reference/api/part/config/options/pct/snap/en.md
markdown/dev/reference/api/part/config/options/pct/toabs/en.md

(This PR replaces closed PR #3169 . It is the same set of changes after I reverted all edits not related to Core API.)

fix(docs): Part Config Options documentation fixes 

---

config/dependencies.yaml
packages/new-design/lib/utils.mjs
packages/new-design/package.json

Extract/duplicate `capitalize` in new-design/lib/utils.mjs itself

refactor(new-design): Remove dependency on core

---

terraform/README.md

Merging this in dev just because

chore: Created terraform folder

---

markdown/dev/reference/settings/en.md
packages/core/src/config.mjs

Remove `settings.debug` which was left over from v2.

chore(core): Remove debug setting

---

markdown/dev/guides/best-practices/respect-draft-settings/en.md

(For documentation pages with a larger number of changes/updates, like this one, I will submit them as individual PRs. For the ones with small changes, I'll bundle them into one PR.)

fix(docs): Updated Respect Draft Settings documentation.

---

sites/backend/src/models/apikey.mjs
sites/backend/src/models/pattern.mjs
sites/backend/src/models/user.mjs
sites/backend/tests/shared.mjs

These are fixes for the 4 Deepscan issues that I noticed were flagged during my previous PR #3304 :
https://deepscan.io/dashboard/#tid=2114&pid=2993&bid=23256&view=project&subview=pull-request&prid=1494260
I did not test these fixes. They are all fixes in `sites/backend`, and I believe that I am not able to test them.

fix(backend): Fix Deepscan and eslint issues

---

markdown/org/docs/patterns/hi/instructions/en.md
markdown/org/docs/patterns/teagan/instructions/en.md

This is meant to address https://github.com/freesewing/freesewing/issues/3167 , about confusion relating to the pectoral fins on Hi. Put @bobgeorgethe3rd on here as a reviewer since he originally drafted these instructions!

Update en.md with pectoral fin tips

---

markdown/org/docs/patterns/teagan/instructions/Teagan03f.svg
markdown/org/docs/patterns/teagan/instructions/Teagan03g.svg
markdown/org/docs/patterns/teagan/instructions/Teagan03h.svg
markdown/org/docs/patterns/teagan/instructions/Teagan03i.svg
markdown/org/docs/patterns/teagan/instructions/en.md

Adds images to Teagan instructions for knit band finish. Technically, addresses previously resolved issue https://github.com/freesewing/freesewing/issues/2207 with an additional improvement, so noting that here so it'll be linked in the closed issue.

Tangerineshark teagan band pics

---

artwork/linedrawings/lunetius.svg
config/changelog.yaml

Add linedrawing for Lunetius by the fantastic @nataliasayang. Closes #2724 .
I'm not sure if some other file somewhere needs to be pointed to the `.svg`, looking at https://github.com/freesewing/freesewing/commit/cde3fb1709815b01f0f1938fef3a3fd2d4b05083 for reference but the file in question doesn't exist anymore.

feat(lunetius): add linedrawing

---

sites/dev/components/wrappers/page.js
sites/dev/pages/404.js
sites/dev/pages/[...mdxslug].js
sites/dev/pages/contact.js
sites/dev/pages/index.js

chore: Move title to page wrapper for dev site

---

markdown/dev/howtos/environments/browser/en.md
markdown/dev/howtos/environments/en.md
markdown/dev/howtos/environments/nodejs/en.md

1. Added `<ReadMore>` tag to the summary page.
2. Changed wording to the `<Tip`> message, to clarify what "generating a pattern" means versus just "wanting a pattern".
3. Standardized spelling/capitalization for freesewing.org and Node.js.

fix(docs): Updates and corrections for FreeSewing in different environments

---

markdown/org/docs/patterns/simone/instructions/en.md

missing slash in relative link breaks link
as reported by @/lasermonkey12 on discord

fix: missing slash

---

sites/dev/skip_build.mjs
sites/lab/skip_build.mjs
sites/org/skip_build.mjs
sites/sanity/skip_build.mjs

Each site checks pull requests for files changed in its own folder and in shared

(Feature) Refine skip build logic to build relevant pull requests

---

scripts/sync-dependencies.mjs

This is to fix the cases, like with `next`, where a dependency's version is handled in `config/dependencies.yaml` by a constant that is defined for a package not of the same name (in the case of `next`, `@next/bundle-analyzer`). 
The script now looks for a direct match first, and if it doesn't find one, it will look for where the constant is defined and change the version there. 
I believe we want this behavior in all cases because if one package with linked versions needs to be bumped, presumably all packages that use that version number will also have a bumped version available, but I'm not positive.

(Dependabot sync) Sync versions even if they are managed by yaml constants

---

sites/dev/skip_build.mjs
sites/lab/skip_build.mjs
sites/org/skip_build.mjs
sites/sanity/skip_build.mjs

The git command that the skip_build scripts were running worked on my local but apparently not in vercel, so builds we wanted to run were getting skipped. Hopefully this command actually works

[Fix] simpler git diff command in skip_build scripts

---

sites/dev/skip_build.mjs
sites/lab/skip_build.mjs
sites/org/skip_build.mjs
sites/sanity/skip_build.mjs

I tested this one as best I could, and it really should work this time. The difficulty was because the vercel environment is a shallow clone it didn't have any other branches to reference, so I had to fetch develop for the comparison

(Fix) Actually working ignored_build script

---

designs/carlita/src/index.mjs

Carlita's cuffFacing part was inadvertently omitted during the port to v3.

fix(carlita): Restore missing cuffFacing part

---

designs/albert/src/front.mjs
designs/albert/src/pocket.mjs
designs/albert/src/strap.mjs

I've requested a review of this PR from @woutervdub , the pattern designer.

fix(albert): Replace duplicate calculations with store values. Closes #2676

---

packages/new-design/templates/shared/part.mjs.mustache
plugins/plugin-cutlist/src/index.mjs

- update hide config for templated parts
- fix `plugin-cutlist` `instanceof` check to just make sure that points have coordinates

fix (new-design) update for core breaking changes

---

plugins/plugin-bust/tests/plugin.test.mjs
plugins/plugin-cutlist/tests/plugin.test.mjs
plugins/plugin-cutonfold/src/index.mjs
plugins/plugin-grainline/src/index.mjs
tests/reporters/terse.js

fixes #3667, so that terser logs and fails properly
Fixes tests failures that had been hidden by terser passing failed suites

fix (tests) Terser reporter should report failures

---

markdown/org/docs/various/notation/bartack/en.md
yarn.lock

Bartack doc

---

markdown/dev/guides/v3/migration/en.md

Had not been updated from hide, hideDependencies and hideAll.

Updated Hide info for V3 Migration

---

packages/i18n/src/locales/en/options/brian.yml

Solution for #3083 suggested by Benjamin.

Added draftForHighBust brian.yml

---

scripts/skip-build-base.mjs

I just submitted a PR from a branch whose history was apparently so divergent from `develop` that looking for the merge-base in out skip_build script timed out on vercel. This PR changes that so that we only deepen the history 5 times before giving up

fix(vercel) limit the number of times skip_build deepens merge-base check

---

designs/simone/src/fba-front.mjs

fix(simone): Only show notches and logo if complete

---

designs/sandy/src/skirt.mjs

Reverts freesewing/freesewing#3906 Turns out the behavior was intended

Revert "fix(sandy): Correct 100% full circle angle and seam allowance"

---

markdown/dev/tutorials/getting-started-vercel/en.md

Discussion:
https://discord.com/channels/698854858052075530/944926520282054666/1099648128531042415
discord://discord.com/channels/698854858052075530/944926520282054666/1099648128531042415

fix(docs): (vercel tutorial) Add build command override

---

markdown/dev/training/git/audio/en.md
markdown/dev/training/git/en.md
markdown/dev/training/git/video/en.md

fix(docs): (git-training) Documentation review

---

sites/shared/components/workbench/gist.mjs
sites/shared/components/workbench/menu/core-settings/index.mjs
sites/shared/components/workbench/menu/core-settings/setting.mjs

(As I understand it, the `debug` setting has been removed in v3. This PR removes the setting from the lab UI.)

fix(workbench): Remove `debug` setting

---

markdown/org/docs/site/draft/core-settings/complete/en.md
markdown/org/docs/site/draft/core-settings/locale/en.md
markdown/org/docs/site/draft/core-settings/margin/en.md
markdown/org/docs/site/draft/core-settings/only/en.md
markdown/org/docs/site/draft/core-settings/paperless/en.md
markdown/org/docs/site/draft/core-settings/renderer/en.md
markdown/org/docs/site/draft/core-settings/scale/en.md
markdown/org/docs/site/draft/core-settings/units/en.md

This PR is merging into the `joost` branch. I'll change that once #3636 is merged. But this makes it easier to review.

[docs] Added docs for core settings

---

designs/bella/src/back.mjs

Fixes #3111.
(The negative back dart issue will be handled separately.)
Example set of measurements used to test:
```yaml
measurements:
chest: 1397
waist: 1371.6
waistBack: 660.4
neck: 425.45
hpsToWaistFront: 482.59999999999997
hpsToWaistBack: 342.9
shoulderToShoulder: 431.79999999999995
shoulderSlope: '13'
highBust: 1244.6
underbust: 1219.1999999999998
bustSpan: 292.09999999999997
hpsToBust: 381
```
Before:
After:

fix(bella): Handle HPS-to-bust > HPS-to-waist-back

---

markdown/org/docs/designs/bella/instructions/en.md

(This PR should be merged after PR #4002, the PR that implements the described behavior.)

fix(bella): (docs) The back dart is sometimes omitted

---

packages/new-design/lib/utils.mjs
scripts/add-software.mjs

Added digits and underscore as acceptable characters for new design names. Names must start with a lowercase letter.
Discord discussion:
https://discord.com/channels/698854858052075530/944926520282054666/1109140022151622787
discord://discord.com/channels/698854858052075530/944926520282054666/1109140022151622787
https://discord.com/channels/698854858052075530/944926520282054666/1110088208701739058
discord://discord.com/channels/698854858052075530/944926520282054666/1110088208701739058
https://discord.com/channels/698854858052075530/944926520282054666/1111874743948284057
discord://discord.com/channels/698854858052075530/944926520282054666/1111874743948284057

fix(new-design): Changed design name acceptable characters

---

config/exceptions.yaml
packages/react-components/CHANGELOG.md
packages/react-components/README.md
packages/react-components/build.mjs
packages/react-components/data.mjs
packages/react-components/package.json
packages/react-components/src/index.mjs
packages/react-components/src/pattern/circle.mjs
packages/react-components/src/pattern/defs.mjs
packages/react-components/src/pattern/grid.mjs
packages/react-components/src/pattern/group.mjs
packages/react-components/src/pattern/index.mjs
packages/react-components/src/pattern/part.mjs
packages/react-components/src/pattern/path.mjs
packages/react-components/src/pattern/point.mjs
packages/react-components/src/pattern/snippet.mjs
packages/react-components/src/pattern/stack.mjs
packages/react-components/src/pattern/svg.mjs
packages/react-components/src/pattern/text.mjs
packages/react-components/src/pattern/utils.mjs

This depends on #4202. Basing this on the `joost` branch because that's what it's based on.

feat(react-components): Added Pattern component

---

markdown/dev/reference/plugins/timing/en.md

Fixes #3206.
(If I am incorrect about the units or variable types, please let me know.)

fix(docs): (timing) Add details and examples

---

sites/lab/components/header/index.mjs
sites/lab/pages/new/pattern/[design]/[type]/[id].mjs

This puts the lab back on the rails

fix(lab): Fix after renaming icon and workbench navigation changes

---

sites/shared/components/workbench/pan-zoom-pattern.mjs
sites/shared/components/workbench/pattern/pan-zoom-context.mjs
sites/shared/components/workbench/views/test/options.mjs
sites/shared/components/workbench/views/view-header.mjs
sites/shared/components/wrappers/layout.mjs

- fewer clicks in the test view
- wb header won't be covered by nav header
- fix pan-zoom infinite loop

More UI Tweaks. Fixes Infinite Loop

---

sites/shared/components/sets/set-candidate.mjs

also I guess something's up with the Next/Image import, and apparently this is the only place we're using it right now (probably also my fault), so I've changed it to a regular img on the `SetCandidate` and I swear the page really loads now

fix (Workbench) Measies view fix 2

---

.github/pull_request_template.md
config/build-order.mjs
crowdin.yml
designs/unice/i18n/en.json
designs/unice/src/index.mjs
designs/ursula/package.json
nx.json
packages/new-design/lib/cli.mjs
packages/new-design/prebuild.mjs
sites/shared/prebuild/runner.mjs

This was a surprise to me :shrug:

fix: Unice does not extend Ursula

---

crowdin.yml
sites/shared/components/modal/locale-picker.mjs
sites/shared/components/modal/theme-picker.mjs
sites/shared/components/wrappers/modal.mjs

The names of the translation files created by Crowdin are incorrect.

fix: Issue with crowding file names and UI tweaks

---

yarn.lock

Something was stuck in the yarn.lock breaking all the tests

chore (yarn) generate new yarn.lock

---

.gitignore
sites/lab/pages/docs/index.mjs
sites/lab/pages/index.mjs
sites/lab/prebuild.mjs
sites/shared/prebuild/markdown.mjs
sites/shared/prebuild/sitenav-lab.mjs
sites/shared/prebuild/sitenav-org.mjs

- get translations working in nav prebuilds
- get dev prebuild working
- get lab prebuild working

fix (prebuild) fix dev and lab prebuild, nav prebuild translations

---

artwork/linedrawings/albert.svg

This is the .svg for the `albert` design.

Adding `albert` line drawing

---

markdown/org/docs/designs/ursula/instructions/en.md

Clarifies that Step 1 and Step 3 involve pinning/basting, not sewing. Thanks to Ben on Discord for pointing out the error: https://discord.com/channels/698854858052075530/757632180980547686/1126254091631349790

Update Ursula instructions

---

markdown/org/docs/sewing/knit-binding/en.md

This PR attempts to improve the knit binding documentation, especially to add information about the approximate expected length of binding that will be used. I also removed instances of "I" and "my" language, since the documentation has no listed author.
This documentation update came from the Discord discussion on/about April 1, 2023 in #sewing-help:
https://discord.com/channels/698854858052075530/757632180980547686/1092482399973163118
discord://discord.com/channels/698854858052075530/757632180980547686/1092482399973163118

fix(docs): Improve knit binding information and instructions

---

markdown/org/docs/faq/newsletter/why-subscribe-multiple-clicks/en.md
sites/shared/i18n/locales/en.yaml

Update Newsletter FAQ

---

sites/backend/src/models/admin.mjs
sites/backend/src/models/set.mjs
sites/backend/tests/index.mjs
sites/backend/tests/set.mjs
sites/org/pages/blog/page/[page].mjs

Shout out to discord user Lin for reporting this 💜

fix(backend): Bug in handling measurements updates

---

markdown/dev/tutorials/pattern-design/completing-our-pattern/en.md
markdown/dev/tutorials/pattern-design/our-first-part/en.md
sites/dev/pages/index.mjs

In anticipation of a more overal QA check. See #4774

fix(dev): Small fixed required to make the tutorial work

---

sites/shared/config/freesewing.config.mjs

fix(shared): Typo in export declaration

---

sites/shared/components/dynamic-docs/org.mjs

gets custom components working in dynamic docs

fix (dynamic docs) pass correct components to dynamic org docs

---

sites/shared/components/account/sets.mjs

fix (curated set picker) get language from i18n for curated set picker

---

designs/benjamin/i18n/en.json
sites/shared/components/workbench/menus/design-options/inputs.mjs
sites/shared/components/workbench/menus/design-options/values.mjs
sites/shared/components/workbench/menus/shared/inputs.mjs
sites/shared/components/workbench/menus/shared/menu-item.mjs

Also adds missing translations for Benjamin

fix(shared): Handle design list options in workbench

---

designs/benjamin/i18n/en.json
designs/benjamin/src/bow1.mjs
designs/benjamin/src/bow2.mjs
designs/benjamin/src/bow3.mjs
designs/benjamin/src/collar-band.mjs
packages/react-components/src/pattern/point.mjs
plugins/plugin-annotations/src/cutlist.mjs
plugins/plugin-annotations/src/title.mjs
sites/shared/components/workbench/en.yaml
sites/shared/components/workbench/menus/design-options/values.mjs
sites/shared/components/workbench/menus/shared/inputs.mjs
sites/shared/components/workbench/menus/shared/menu-item.mjs
tests/designs/config.mjs
tests/designs/i18n.mjs

Changes the title macro to always render points.
Makes the cutlist's addCut method accept mutliple configs

chore(benjamin): Migrated for v3 beta + plugin tweaks

---

config/software/designs.json
designs/tamiko/i18n/en.json
designs/tamiko/src/top.mjs
designs/teagan/i18n/en.json
designs/teagan/src/back.mjs
designs/teagan/src/front.mjs
designs/teagan/src/sleeve.mjs
designs/tiberius/i18n/en.json
designs/tiberius/src/tunica.mjs

This includes:
- Tamiko (closes #4993)
- Teagan (closes #4994)
- Tiberius (closes #4996)

chore: Prepare more designs for v3 beta

---

config/software/designs.json
designs/trayvon/i18n/en.json
designs/trayvon/src/fabric.mjs
designs/trayvon/src/interfacing.mjs
designs/trayvon/src/lining.mjs
designs/trayvon/src/loop.mjs
designs/trayvon/src/shared.mjs

chore(trayvon): Prepare for v3 beta

---

config/software/designs.json
designs/wahid/i18n/en.json
designs/wahid/src/back.mjs
designs/wahid/src/front.mjs
designs/wahid/src/frontfacing.mjs
designs/wahid/src/frontlining.mjs
designs/wahid/src/pocketbag.mjs
designs/wahid/src/pocketfacing.mjs
designs/wahid/src/pocketinterfacing.mjs
designs/wahid/src/pocketwelt.mjs
designs/wahid/src/shared.mjs
sites/shared/components/workbench/menus/design-options/inputs.mjs

Closes #5013 
Also includes fix where workbench would only run toAbs when measurements were set.

chore(wahid): Prepare for v3 beta

---

config/software/designs.json
designs/yuri/i18n/en.json
designs/yuri/src/back.mjs
designs/yuri/src/front.mjs
designs/yuri/src/gusset.mjs
designs/yuri/src/hoodcenter.mjs
designs/yuri/src/hoodside.mjs
designs/yuri/src/shared.mjs
designs/yuri/src/sleeve.mjs

chore(yuri): Prepare for v3 beta

---

config/software/designs.json
designs/penelope/i18n/en.json
designs/penelope/src/back.mjs
designs/penelope/src/front.mjs
designs/penelope/src/shape.mjs
designs/penelope/src/utils.mjs
designs/penelope/src/waistband.mjs
markdown/org/docs/designs/penelope/options/curveddarts/en.md
markdown/org/docs/designs/penelope/options/waistbandoverlap/en.md

You're submitting a pull request to FreeSewing, that's awesome :tada:
Before doing so, please take a moment to read up on what sort of pull requests
are **not accepted** (don't worrry, it's short list):
- A pull requests that includes a **major overhaul or refactor** and was not
discussed or requested beforehand.
- A pull requests that **changes infrastructure code** (changes to pipelines,
dependency management, monorepo-wide config and so on) that was not discussed
or requested beforehand.
I welcome contributions big and small, but these kinds are usually more hassle
than they are worth, so let's just not, ok?
tx,  
joost

Implements #4954 ([penelope]: Prepare for v3 beta)

---

config/software/designs.json
designs/noble/i18n/en.json
designs/noble/src/backinside.mjs
designs/noble/src/backoutside.mjs
designs/noble/src/backpoints.mjs
designs/noble/src/frontinside.mjs
designs/noble/src/frontoutside.mjs
designs/noble/src/frontpoints.mjs
designs/noble/src/options.mjs

You're submitting a pull request to FreeSewing, that's awesome :tada:
Before doing so, please take a moment to read up on what sort of pull requests
are **not accepted** (don't worrry, it's short list):
- A pull requests that includes a **major overhaul or refactor** and was not
discussed or requested beforehand.
- A pull requests that **changes infrastructure code** (changes to pipelines,
dependency management, monorepo-wide config and so on) that was not discussed
or requested beforehand.
I welcome contributions big and small, but these kinds are usually more hassle
than they are worth, so let's just not, ok?
tx,  
joost

Implements #4952 [noble]: Prepare for v3 beta

---

markdown/dev/guides/designs/stacks/en.md
markdown/dev/reference/api/part/config/en.md
markdown/dev/reference/api/part/config/stack/en.md
markdown/dev/reference/api/pattern/en.md
markdown/dev/reference/api/stack/addPart/en.md
markdown/dev/reference/api/stack/asProps/en.md
markdown/dev/reference/api/stack/attr/en.md
markdown/dev/reference/api/stack/en.md
markdown/dev/reference/api/stack/generateTransform/en.md
markdown/dev/reference/api/stack/getAnchor/en.md
markdown/dev/reference/api/stack/getPartList/en.md
markdown/dev/reference/api/stack/getPartNames/en.md
markdown/dev/reference/api/stack/home/en.md
markdown/dev/reference/settings/stackprefix/en.md

I am especially requesting that @joostdecock and @eriese look at this PR. This is because I did not understand stacks before starting to write this documentation. I had to learn as I went along.

chore(docs): Add Stack documentation

---

plugins/plugin-annotations/src/banner.mjs
sites/dev/pages/[...slug].mjs

This fixes hydration errors on the dev site.
Also includes a typo fix in a comment in plugin-annotations

fix(dev): Add missing namespace

---

markdown/org/docs/designs/onyx/instructions/en.md
markdown/org/docs/designs/onyx/notes/en.md

This PR provides the designer's notes, and adds in some instructions that I had neglected to add, specifically rib knit cuffs and the skirt.

Onyx - Designer notes and additions to the sewing instructions.

---

markdown/org/docs/designs/shelly/notes/en.md
markdown/org/docs/designs/shelly/options/armpitease/en.md

Contains the designer notes for the Shelly design. This also contains armpitease/en.md, which I believe got left out of the previous PR by mistake.

Shelly -  designer notes

---

markdown/org/docs/designs/bee/notes/en.md

Designer notes for Bee  #5364
Hopefully the links work.

add(docs) Designer Notes for Bee

---

markdown/org/docs/designs/lucy/notes/en.md

Adding designer notes for Lucy

Designer Notes for Lucy

---

markdown/org/docs/designs/lunetius/notes/en.md
markdown/org/docs/designs/tiberius/notes/en.md
markdown/org/docs/designs/walburga/notes/en.md

Addresses part of issue https://github.com/freesewing/freesewing/issues/5364.

feat: add designer notes for Lunetius, Tiberius and Walburga

---

markdown/org/docs/designs/albert/notes/en.md
markdown/org/docs/designs/benjamin/notes/en.md
markdown/org/docs/designs/cornelius/notes/en.md
markdown/org/docs/designs/gozer/en.md
markdown/org/docs/designs/hi/notes/en.md
markdown/org/docs/designs/hortensia/en.md
markdown/org/docs/designs/noble/notes/en.md
markdown/org/docs/designs/octoplushy/notes/en.md
markdown/org/docs/designs/otis/notes/en.md
markdown/org/docs/designs/penelope/notes/en.md
markdown/org/docs/designs/skully/notes/en.md
markdown/org/docs/designs/waralee/notes/en.md

Added designer notes to all my patterns

---

README.md
config/templates/readme.main.md

simple typo fix to close #5350

typo fix #5350

---

markdown/dev/howtos/editors/showcase/en.md
markdown/dev/howtos/ways-to-contribute/community-building/en.md
markdown/dev/howtos/ways-to-contribute/showcase-our-patterns/en.md
markdown/dev/howtos/ways-to-contribute/translation/en.md

- Updating showcase submission info
- Replacing broken link on Community Building page with direct links to our socials
- Adding Ukrainian to list of languages

Updating freesewing.dev howtos

---

designs/skully/src/cheekbone.mjs

Simple change to fix SVG render error.

Fix bug #5524

---

sites/shared/components/workbench/views/draft/header.mjs

fix(shared): Don't make assumptions about saveAs

---

markdown/dev/reference/measurements/en.md
markdown/org/docs/measurements/hpstobust/en.md
markdown/org/docs/measurements/hpstowaistback/en.md
markdown/org/docs/measurements/hpstowaistfront/en.md

This was missed when HPS doc was moved. Closes #5568

Fix links to HPS after HPS doc was moved

---

packages/rehype-jargon/README.md

FIX: jargon manual is not quite correct

---

markdown/dev/guides/markdown/jargon/en.md

chore(markdown): Add jargon glossary

---

markdown/org/docs/designs/paco/instructions/en.md

fix(markdown): Correct Paco waistband sewing instructions

---

designs/brian/i18n/en.json
designs/brian/src/base.mjs

fix(brian): Flag.warn if shoulder width too large

---

markdown/org/docs/designs/simone/options/roundback/en.md

(I simply copied the text from Simon's roundback documentation.)

fix(simone): Add roundback option documentation

---

designs/carlton/src/collar.mjs

fix(carlton) Fix stray seam allowance path

---

sites/shared/i18n/docs/en.yaml

Per Discord discussion, "User Experience" is the correct term to use.
https://discord.com/channels/698854858052075530/757631165531291771/1200455095356244078
discord://discord.com/channels/698854858052075530/757631165531291771/1200455095356244078

fix(shared): Correct ControlTip tag text to use User Experience wording

---

designs/bent/src/sleeve.mjs
designs/breanna/src/base.mjs
designs/simon/src/options.mjs
sites/shared/components/workbench/views/test/menu.mjs

Closes #5975
The following patterns were crashing the test view due to the implementation of conditional options:
- Bent
- Breanna
- Carlita
- Carlton
- Simon(e)
The test view was also not properly changing to hide/show options as needed, so this was also fixed.

Fix bugs with test view and conditionally hidden options

---

designs/sandy/src/skirt.mjs

1. Corrected the vertical dimensions on the right.
2. Added horizontal dimensions at the top.
Previous Discord discussion:
https://discord.com/channels/698854858052075530/757631205804998759/1197990109568565339
discord://discord.com/channels/698854858052075530/757631205804998759/1197990109568565339
Before:
After:

fix(sandy): Correct vertical dimensions, and add horizontal dimensions

---

designs/jaeger/i18n/en.json
designs/jaeger/src/undercollar.mjs
markdown/org/docs/designs/jaeger/cutting/en.md
markdown/org/docs/designs/jaeger/instructions/en.md

Fixes #3820.
- I am questioning whether the seam allowance is correct for the under-collar-and-stand. The previous version of the part had seam allowance only on the 2 short sides. I re-added full seam allowance around all 4 sides. I asked on Discord but didn't get a reply.
- I also rewrote the sewing instructions, but I had to guess at some of the procedures and the order of operation.
- I also renamed the part to "under-collar-and-stand". The name is a bit awkward, but I think it will help customers better understand what the part is and where it goes.
- I did not add any **expand** functionality to this part. I think that could be done later.
(I added the arrows on the below screenshot so I could use it to ask whether the seam allowance is correct for the top and bottom sides.)

fix(jaeger): Fix undercollar to correct shape

---

markdown/org/docs/designs/carlita/cutting/en.md
markdown/org/docs/designs/carlton/cutting/en.md
markdown/org/docs/designs/jaeger/cutting/en.md

fix(carlita, carlton, jaeger): In cutting doc, add comment with non-nett canvas method

---

sites/shared/components/account/sets.mjs

This was the best I could come up with, in terms of UI.
Fixes #5822.

fix(shared): Show missing measurements for sets for new patterns

---

sites/shared/components/account/en.yaml
sites/shared/components/account/sets.mjs

fix(shared): Add translations to missing measurements string

---

designs/hugo/src/front.mjs

fix(hugo): Add missing dimension id attributes

---

sites/shared/components/curated-sets.mjs

feat: Add name to curated sets, using flexbox

---

sites/shared/components/account/en.yaml
sites/shared/components/workbench/views/measies/editor.mjs

fix(shared): Add i18n for pattern measurements UI

---

designs/brian/src/sleevecap.mjs
plugins/plugin-annotations/src/cutlist.mjs

fix(brian): Eliminate warning message

---

sites/shared/components/account/en.yaml

Added missing `yourApikeys` text key. (Also fixed a small typo.)
After:
Before:

fix(shared): Add yourApikeys text key

---

sites/shared/components/workbench/menus/ui-settings/en.yaml

fix(shared): Add Kiosk Mode text keys

---

markdown/org/showcase/a-modified-holmes/en.md

Add author for Holmes Showcase

---

markdown/org/showcase/3d-skully/en.md
markdown/org/showcase/a-warm-weather-pair-of-waralees/en.md
markdown/org/showcase/albert-by-wouter/en.md
markdown/org/showcase/cornelius-by-wouter/en.md
markdown/org/showcase/florent-by-wouter/en.md
markdown/org/showcase/four-versions-of-otis-and-a-bonus-bob/en.md
markdown/org/showcase/hi-the-shark-has-our-hearts/en.md
markdown/org/showcase/hortensia-by-wouter/en.md
markdown/org/showcase/lightweight-waralees-for-summer/en.md
markdown/org/showcase/lumira-leggings-with-cycling-chamois/en.md
markdown/org/showcase/meet-octoplushy/en.md
markdown/org/showcase/octopus-variant-octoplushy/en.md
markdown/org/showcase/waralee-by-wouter/en.md
markdown/org/showcase/waralee-wrap-pants-by-wouter/en.md

#6178 
#6179 
#6180 
#6181 
#6182 
#6183 
#6184 
#6185 
#6186 
#6188 
#6189 
#6190 
#6191
#6192

Add Author woutervdub

---

markdown/org/showcase/two-tone-teagan/en.md

Add Author Imunar

---

markdown/org/showcase/100percent-full-sandy-by-lasermonkey12/en.md
markdown/org/showcase/a-delightfully-drapey-teagan-by-lasermonkey12/en.md
markdown/org/showcase/a-squid-friend-for-octopus/en.md
markdown/org/showcase/florent-lined-with-lasermonkey12s-favorite-dr-seuss-book/en.md
markdown/org/showcase/surprise-giant-hi-by-lasermonkey12/en.md
markdown/org/showcase/two-short-sleeved-simons-by-lasermonkey12/en.md
markdown/org/showcase/xl-octoplushy-by-lasermonkey12/en.md

#6165 
#6166 
#6167 
#6168 
#6169 
#6170 
#6171

Add Author lasermonkey12

---

markdown/org/showcase/a-simone-sandy-mashup-with-a-handkerchief-hem-by-rockerkitten/en.md
markdown/org/showcase/a-very-modified-yuri/en.md
markdown/org/showcase/a-wearable-sandy-muslin/en.md
markdown/org/showcase/rockerkittens-simone-muslin-with-a-few-modifications/en.md
markdown/org/showcase/the-bella-block-by-rockerkitten/en.md

#6159 
#6160 
#6161 
#6162 
#6163

Add RockerKitten Author

---

markdown/org/showcase/a-lovely-reversible-tristan-top-by-paula/en.md

Add paula_ Author

---

markdown/org/showcase/hand-stitched-teagans-by-vili-with-explanation-of-the-stitches/en.md

Add VSinerva Author

---

markdown/org/showcase/carlton-coat/en.md

Add Vlad Author

---

markdown/org/showcase/hortensia-by-saber/en.md

Add saber Author

---

markdown/org/showcase/bruce-with-a-flat-front-and-lengthened-legs/en.md

Add halbmoki Author

---

markdown/org/showcase/blue-wahid-by-bjeppson/en.md

Add user71677 Author

---

markdown/org/showcase/blue-wahid-by-bjeppson/en.md

Reverts freesewing/freesewing#6221
Merged too quick, before realizing the author claim is disputed (as pointed out by @bobgeorgethe3rd but I was too hasty and missed it)

Revert "Add user71677 Author"

---

markdown/org/showcase/another-splendid-simon/en.md
markdown/org/showcase/blue-geometric-simon/en.md
markdown/org/showcase/brown-geometric-simon/en.md
markdown/org/showcase/bruce-by-ferdi/en.md
markdown/org/showcase/bruce-three-pack/en.md
markdown/org/showcase/ferdis-first-simon-shirt/en.md
markdown/org/showcase/florent-cap-by-ferdi/en.md
markdown/org/showcase/just-another-simon-shirt/en.md
markdown/org/showcase/simon-as-overshirt/en.md

#6200 
#6202 
#6203 
#6204 
#6205 
#6206 
#6207 
#6208 
#6209

Add ferdi Author

---

designs/bruce/src/back.mjs

edited back cutting pattern label to be cut 1 to match the cutting instructions

correct back cutting instructions

---

markdown/org/showcase/a-full-body-onyx-swimsuit-with-swim-skirt/en.md
markdown/org/showcase/onyx-by-thrunic/en.md
markdown/org/showcase/onyx-full-body-unisuit/en.md
markdown/org/showcase/short-sleeve-shelly-rash-guard/en.md
markdown/org/showcase/short-sleeve-short-leg-onyx-swimsuit/en.md

closes #6249 
closes #6250 
closes #6251 
closes #6252 
closes #6253

Add Thrunic Author

---

markdown/org/showcase/aaron-dress-by-ts/en.md
markdown/org/showcase/bee-by-ts/en.md
markdown/org/showcase/bee-teagan/en.md
markdown/org/showcase/bella-by-karen/en.md
markdown/org/showcase/bella-sandy-by-ts/en.md
markdown/org/showcase/charlie-by-karen/en.md
markdown/org/showcase/formal-aaron/en.md
markdown/org/showcase/paco-by-karen/en.md
markdown/org/showcase/teagan-by-karen/en.md
markdown/org/showcase/teagan-karen/en.md
markdown/org/showcase/ursula-by-karen/en.md

closes #6254 
closes #6255 
closes #6256 
closes #6257 
closes #6258 
closes #6259 
closes #6260 
closes #6261 
closes #6262 
closes #6263 
closes #6264

Add TangerineShark Author

---

markdown/org/showcase/aaron-a-shirt-by-pecatrix/en.md

Add talatrix Auhtor

---

markdown/org/showcase/wahid-waistcoat-by-womp/en.md

Add amaan hammadi Author

---

markdown/org/showcase/stripey-teagan/en.md

Add Anonymous Author

---

markdown/org/showcase/lunetius-walburga-tiberius-ensemble/en.md

Add starfetch Author

---

sites/shared/components/designs/linedrawings/index.mjs

FlorentBack doesn't actually exist, so no need to import it.

Remove unused import (fix ESLint warning)

---

sites/shared/components/account/sets.mjs

fix(shared): Allow bookmarking measurement sets from other users.

---

markdown/org/docs/designs/uma/measurements/de.md
markdown/org/docs/designs/uma/measurements/en.md
markdown/org/docs/designs/uma/measurements/es.md
markdown/org/docs/designs/uma/measurements/fr.md
markdown/org/docs/designs/uma/measurements/nl.md
markdown/org/docs/designs/uma/measurements/uk.md

fix(markdown): Link Uma design measurements in documentation properly

---

markdown/dev/tutorials/pattern-design/part2/drawing-the-straps/en.md

fix(markdown): Fix order of steps in dev pattern design tutorial

---

markdown/org/showcase/a-jaeger-and-charlie-set/en.md
markdown/org/showcase/a-mini-hi-with-embroidered-eyes/en.md
markdown/org/showcase/aaron-a-shirt-by-gaelle/en.md
markdown/org/showcase/hi-by-gaelle/en.md
markdown/org/showcase/hugo-by-gaelle/en.md
markdown/org/showcase/pyjama-paco-by-gaelle/en.md
markdown/org/showcase/simone-by-gaelle/en.md
markdown/org/showcase/tamiko-by-gaelle/en.md

Closes #6294
Closes #6293
Closes #6292
Closes #6291
Closes #6290
Closes #6289
Closes #6288
Closes #6287

chore(markdown): Author updates for Gaelle

---

markdown/org/showcase/ramoth-cathrin-corset/en.md
markdown/org/showcase/ramoth-short-sleeve-simon/en.md
markdown/org/showcase/ramoth-simon-flannel/en.md
markdown/org/showcase/simon-by-ramoth/en.md

The real ones:
Closes #6386
Closes #6385
Closes #6384
Closes #6383
And the fake one:
Closes #6369

chore(markdown): Attribution for Ramoth's showcases

---

designs/jaeger/src/front.mjs
designs/paco/src/back.mjs
designs/sandy/src/straight-waistband.mjs

(After seeing the "farbic" typo fix in #6404, I searched for the same typo and found these 3 others.)

fix(jaeger,paco,sandy): Typo

---

markdown/dev/tutorials/pattern-design/part2/adding-measurements/en.md
markdown/dev/tutorials/pattern-design/part2/adding-options/en.md
markdown/dev/tutorials/pattern-design/part2/avoiding-overlap/en.md
markdown/dev/tutorials/pattern-design/part2/completing-the-neck-opening/en.md
markdown/dev/tutorials/pattern-design/part2/constructing-the-neck-opening/en.md
markdown/dev/tutorials/pattern-design/part2/creating-the-closure/en.md
markdown/dev/tutorials/pattern-design/part2/draft-method/en.md
markdown/dev/tutorials/pattern-design/part2/drawing-the-bib-outline/en.md
markdown/dev/tutorials/pattern-design/part2/drawing-the-straps/en.md
markdown/dev/tutorials/pattern-design/part2/en.md
markdown/dev/tutorials/pattern-design/part2/fitting-the-neck-opening/en.md
markdown/dev/tutorials/pattern-design/part2/our-first-design/en.md
markdown/dev/tutorials/pattern-design/part2/our-first-part/en.md
markdown/dev/tutorials/pattern-design/part2/rounding-the-corners/en.md
markdown/dev/tutorials/pattern-design/part2/shaping-the-straps/en.md

Minor edits to pattern design tutorial for clarity and consistency.

Edits to pattern design tutorial

---

config/changelog.yaml
config/software/designs.json

Because @HaasJona says so (and he's right)

chore: bump Uma difficulty to 2

---

markdown/org/docs/designs/wahid/instructions/en.md

For some reasons some images were duplicate and some were missing

fix(wahid): Fix images in sewing documentation

---

sites/shared/i18n/sections/en.yaml

Fixes #6438
~This is untested.~
Now tested:

Add missing i18n string. 

---

markdown/org/showcase/bruces-by-paul/en.md
markdown/org/showcase/huey-by-paul/en.md
markdown/org/showcase/linnen-jaeger-by-paul/en.md
markdown/org/showcase/outfit-wahid-theo-florent-by-paul/en.md
markdown/org/showcase/outfit-wahid-theo-simon-by-paul/en.md
markdown/org/showcase/yoga-set-by-paul/en.md

Closes #6451
Closes #6452
Closes #6453 
Closes #6454 
Closes #6455 
Closes #6456

Add tiger751023 Author Claims

---

designs/huey/src/shared.mjs

fix(huey): multiply the ribbing width in the flag message by 2.

---

sites/org/pages/admin/subscribers.mjs

Cherry-picked the fix by @HaasJona

chore: Fix eslint complaints

---

markdown/org/showcase/a-lined-tristan-top-with-front-lacing/en.md

Add upcyclinguser Author

---

markdown/org/showcase/shorts/en.md

Closes #6556
- Also small typo

Add Galit Author

---

markdown/org/docs/designs/simon/instructions/en.md

The link to the site mentioned at the beginning of Simon is still up. it just changed its sub-domain.

Link just changed sub-domain.

---

designs/wahid/src/back.mjs

Sewing instructions say to also cut back part from lining, but this is missing in the pattern

fix(wahid): The back part needs also two cuts from lining fabric

---

sites/shared/components/mdx/read-more.mjs
sites/shared/prebuild/sitenav-org.mjs
sites/shared/utils.mjs

Fix various small issues with the sitenav structure

---

markdown/org/showcase/a-lined-tristan-top-with-front-lacing/en.md
markdown/org/showcase/a-noble-top-for-the-renaissance-festival/en.md
markdown/org/showcase/bella-block/en.md
markdown/org/showcase/green-cathrin/en.md
markdown/org/showcase/lower-rise-ursula/en.md
markdown/org/showcase/mini-shin-swim-trunks/en.md
markdown/org/showcase/modified-tamiko-nursing-cover/en.md
markdown/org/showcase/ursula-test-pairs/en.md

Closes #6587
Closes #6586
Closes #6585
Closes #6584
Closes #6583
Closes #6582
Closes #6581
Closes #6580

chore(markdown): Claim showcase posts of Natalia

---

CHANGELOG.md
config/changelog.yaml
designs/simone/i18n/en.json

fix(simone): Add translation for missing options

---

CHANGELOG.md
config/changelog.yaml
designs/simon/src/options.mjs

Fixes #6508
Shout-out to @karlnippoldt for reporting this.

feat(simon): Allow negative values for buttonFreeLength option

---

CHANGELOG.md
config/changelog.yaml
designs/charlie/src/fly-facing.mjs
markdown/org/docs/designs/charlie/cutting/en.md

Fixes #6392
Shout-out to @jpmunic for reporting this.

fix(charlie): Cutting instructions for the fly facing

---

sites/shared/components/account/patterns.mjs

Fixes #6477
This was a feature request by FreeSewing user 23364 (Renee-mariposa)

feat(shared): Allow sorting of patterns by various fields.

---

markdown/org/docs/about/site/en.md

Thanks to Discord user FrostCow for reporting this 🙏

fix(org): Broken link to docs

---

markdown/org/showcase/sleeveless-simon-by-lasermonkey12/en.md

Update with user ID and correcting design to Simone (not Simon).
Resolves https://github.com/freesewing/freesewing/issues/6668

Update Sleeveless Simon by lasermonkey12 showcase

---

designs/jane/i18n/en.json
designs/jane/src/body.mjs
designs/jane/src/gusset.mjs
designs/jane/src/sleeve.mjs

Closes #6698 
I forgot to add store to the shorthand list after adding the cutlist plugin.

bug fix: Fixes Jane's failing tests

---

designs/lily/i18n/en.json

Fixes Lily's failing tests by adding 'Leggings' to title and adding the missing options to the translation file from Titan. 
Closes #6697
@anna-puk is this good for you? We can change the wording if you want to!

Bug fix: Add Lily translations from Titan

---

markdown/org/showcase/a-sturdy-albert-apron-by-ojensen/en.md

Add ojensen author

---

markdown/org/showcase/simone-by-jackseye/en.md

Add Jacques Author

---

designs/onyx/src/base.mjs

Fixed onyx to properly generate instructors for cutting the crotch gusset and skirt when both expand and sa are set off.

[Onyx] Fixes issue #6721

---

sites/shared/components/account/import.mjs

fix(org): Handle errors when importing measurements"

---

config/software/designs.json

fix(bruce) Fixing Bruce's filter labels

---

config/software/designs.json
sites/shared/i18n/tags/en.yaml

- Adds missing filter tags
- Fixs `curvedSeams` to `curvedSeam` tags in config

fix(tags) Add and fixes filter tag translations

---

designs/jane/src/body.mjs

Sets SA to the correct seam path name

(fix) Fixes breaking SA in Jane

---

CHANGELOG.md
config/changelog.yaml
designs/teagan/src/front.mjs

- **chore(teagan): Increase length bonus to 15%. Fixes #6820**
- **chore: changelog update**

fix(teagan): Increase length bonus. Fixes #6820

---

markdown/org/showcase/watermelon-charlie-chinos/en.md

feat: New showcase post watermelon-charlie-chinos by posh tunic

---

markdown/org/showcase/comixminx-shins/en.md
markdown/org/showcase/flat-front-bruces/en.md
markdown/org/showcase/hugo-with-cats/en.md
markdown/org/showcase/small-calico-skully-and-a-bit-of-a-pattern-test-too/en.md
markdown/org/showcase/teagans-for-swimming/en.md

Fixes #6860
Fixes #6859
Fixes #6858
Fixes #6857
Fixes #6856

fix(markdown): Author fixes for posts by comixminx

---

markdown/org/showcase/woolen-wahid/en.md

feat: New showcase post woolen-wahid by Adridne

---

markdown/org/showcase/a-dinosaur-themed-aaron-with-some-customizations/en.md

feat: New showcase post a-dinosaur-themed-aaron-with-some-customizations by natalia

---

markdown/org/showcase/waralees-by-gaelle/en.md

feat: New showcase post waralees-by-gaelle by natalia

---

config/changelog.yaml
designs/uma/src/base.mjs

See issue report on Discord: https://discord.com/channels/698854858052075530/757631165531291771/1257835305143111775

fix(uma): multiply toAbs() value of gusset slider by two

---

designs/bibi/i18n/en.json
designs/bibi/src/back.mjs
designs/bibi/src/shared.mjs
designs/bibi/src/waistband.mjs
markdown/org/docs/designs/bibi/options/lengthadjustment/en.md
markdown/org/docs/designs/bibi/options/waistadjustment/en.md

Improve some minor issues of Bibi, [partially discussed on Discord](https://discord.com/channels/698854858052075530/698854858496802868/1257711807410208888).
- Add advanced option to control length adjustment, so you can remove the dart/gathering in some cases with the side effect to make the garment longer on the back
- Add advanced option to make the hourglass shape around the waist less extreme
- Fix sharp corner issue when the waistband is exactly on the waist
- Remove default 20% flare (0% flare should be zero flare)
- Tweak some default options (increase waist and hips ease, tune curve at hem)
- Hide fold lines on knit bands if complete is disabled

Some minor Bibi improvements

---

config/changelog.yaml
designs/sandy/src/curved-waistband.mjs
markdown/dev/reference/api/path/circlesegment/en.md
packages/core/src/path.mjs
packages/core/tests/path.test.mjs
plugins/plugin-ringsector/src/index.mjs

See discussion on Discord. 
Todo:

Add path.circleSegment() function

---

markdown/org/showcase/suit/en.md

feat: New showcase post suit by Tinker-Tim-The-Toolman-Taylor-Soldier-Spy

---

markdown/org/showcase/meine-erste-badehose/en.md

**Warning:** This was submitted by a non-English user.
Due to the way out translation software works, the original content
must alway be English. So it is possible this needs to be translated
to English prior to merging.

feat: New showcase post meine-erste-badehose by Karlo

---

markdown/org/blog/the-refashioners-2017/en.md

Closes #6954, seems someone thought Joost should get proper credit :sweat_smile:

Set author for refashioners blog

---

.all-contributorsrc

Edited my (Lexander) name and contribution types :) And added "blog" to BG3
Thanks!

Update Lexander (and BG3) in .all-contributorsrc 

---

designs/sandy/src/skirt.mjs
designs/tristan/src/peplumFront.mjs

Fixes regression from #6955
See https://discord.com/channels/698854858052075530/698862765053575188/1273809150450729001

fix(sandy): fix seam allowance construction to work with new ringsector changes

---

designs/paco/src/waistband.mjs

fix(paco): fix dimensions in expand message

---

designs/jaeger/src/chest-piece.mjs

fix(jaeger): Remove lapel from Chest part

---

markdown/org/showcase/first-attempt-sewing-undies/en.md

feat: New showcase post first-attempt-sewing-undies by AuxSuivants

---

markdown/org/showcase/joshs-numeric-simon/en.md

feat: New showcase post joshs-numeric-simon by JoshShabtaiCa

---

sites/shared/components/workbench/views/save/index.mjs

https://discord.com/channels/698854858052075530/944926520282054666/1285476628545142795
discord://discord.com/channels/698854858052075530/944926520282054666/1285476628545142795
> gremlynn — Yesterday at 10:45 PM
> Can somebody who uses github commit this for me? ^^;
(I filed this PR per request from Discord. I haven't tested the changes.)

fix(shared): Change workbench pattern save URL

---

markdown/org/showcase/short-sleeved-simon/en.md

feat: New showcase post short-sleeved-simon by starfirebird

---

designs/simone/src/fba-front.mjs

fix(simone): Move bust point creation ahead of no-FBA return

---

markdown/org/docs/about/faq/measurements-issues/en.md

Some improvements to the "I'm having trouble with measurements. What should I check?" measurements FAQ https://freesewing.org/docs/about/faq/measurements-issues
With input from the community:
https://discord.com/channels/698854858052075530/1101975649419268186/1285298538078666905
discord://discord.com/channels/698854858052075530/1101975649419268186/1285298538078666905
(These are just my suggested improvements. People should feel free to subsequently change or add anything as needed.)

fix(docs): Changes and additions to measurements FAQ

---

designs/hugo/i18n/en.json

fix(hugo) Correct expand info

---

markdown/org/showcase/doll-cathrin/en.md

add(docs) MagicantAce Author Cathrin

---

markdown/org/showcase/colorful-hi-by-zag/en.md
markdown/org/showcase/gender-euphoric-bruces/en.md

add(docs) Zag Author

---

markdown/org/showcase/watermelon-charlie-chinos/en.md

add(docs) posh tunic author

---

designs/sandy/src/skirt.mjs
designs/tristan/src/peplumFront.mjs

Reverts freesewing/freesewing#7012
With the reversion of ringsector. #7012 should also have been reverted.

Revert "fix(sandy): fix seam allowance construction to work with new ringsector changes"

---

sites/orgdocs/docs/designs/brian/options/readme.mdx

(I changed only the "Sleevecapfrontfactory" line. All the other changes were made by `prettier`.)

fix(docs): Typo in Brian options

---

i18n/optiongroups.yaml

fix(i18n): Add "Armhole" translation to option menus

---

sites/orgdocs/docs/designs/bob/instructions/readme.mdx
sites/orgdocs/docs/designs/bob/options/headsize/readme.mdx
sites/orgdocs/docs/designs/bob/options/lengthratio/readme.mdx
sites/orgdocs/docs/designs/bob/options/neckratio/readme.mdx
sites/orgdocs/docs/designs/bob/options/readme.mdx
sites/orgdocs/docs/designs/bob/options/widthratio/readme.mdx
sites/orgdocs/docs/designs/bob/readme.mdx

See https://github.com/freesewing/freesewing/issues/7168

chore(docs): Port Bob to Docusaurus

---

sites/shared/components/account/en.yaml
sites/shared/components/workbench/menus/core-settings/en.yaml
sites/shared/components/workbench/menus/ui-settings/en.yaml

fix(shared): Add missing English translations

---

sites/org/components/genimg/index.mjs

Fixes #7142
Web browsers can have call stack limitations that prevent calling functions with large arrays as parameters. (The bug was seen on the Safari desktop web browser. It is unclear if the bug affects any other browsers, but it is possible.)
This PR fixes the issue by iterating the array instead of calling a function with the entire array.
Iterating is a slower operation, and there is a noticeable delay between pressing the generate button and seeing the result. For this reason, this PR also adds loading status dialogs so the user is kept informed about the progress of the operation. (The "nailed it" success dialog is shown after the array iteration rather than immediately after the backend response. This is because the backend response is relatively quick. It is the iteration has …

fix(org): Fix generate a social media image

---

markdown/org/showcase/rainbow-fleece-hi/en.md

feat: New showcase post rainbow-fleece-hi by starfirebird

---

designs/lily/i18n/en.json
designs/titan/i18n/en.json
designs/titan/src/back.mjs
sites/orgdocs/docs/designs/titan/options/usewaistanglefor/readme.mdx
sites/orgdocs/docs/designs/titan/options/waistangle/readme.mdx

Add i18n strings and docusaurus documentation for titan waistband angle.
This is similar to the previous PR #7228 but I've left out the calculation and suggestion of a waistband angle for now as that was kinda dubious and experimental.

Add missing descriptions for titan waistband balance

---

scripts/add-software.mjs
scripts/help.mjs

I've used the term "org development environment". I'm not sure if there might be a better term for it.

fix(scripts): Remove references to lab development environment

---

markdown/org/showcase/trayvon-tie-square/en.md

Add GursMan123 Author

---

packages/react/components/Editor/components/menus/Container.mjs
packages/react/components/Editor/components/menus/Input.mjs

- Handle mission i18n better
- The t() function is not available in this scope
- set config.choiceTitles for the menu so the menuitems get labels

Fix the part selection ("only") menu

---

packages/react/components/Xray/path.mjs

Dumb fix for the inspector/xray view
