freesewing/freesewing

packages/plugin-cutonfold/src/index.js

the offset property was not used appropriately. Instead of being offset from the point that is the start of the CoF, it was offset from the original starting point. This point has already been shifted by the margin property. 
This change also swaps the names of the cutonfoldFrom and cutonfoldTo points to be consistent with the to: and from: properties of the macro.

Fixed offset issue.

---

packages/core/src/pattern.js

Closes #692 
There was an extra space in the second `translate(x, y)` for SVG group tags, causing Illustrator to ignore that translation and render all pattern pieces in the same spot.

Remove extra space in svg group translate

---

.github/ISSUE_TEMPLATE/documentation-update.md

Might be too dry? Happy to have the wording/format changed. I based this off the showcase template as that appeared most suitable for content changes.
Addresses https://github.com/freesewing/freesewing/issues/754
I haven't updated the changelog as I'm not sure what the convention is with keeping that up to date (do it before or after the merge?) or what you'd classify this sort of change as...

Add template for documentation/content updates

---

packages/albert/config/index.js

This change updates the config file of Albert to use the same
name as other patterns by @woutervdub
I literally copy-pasted in the relevant lines from the
Benjamin config file

chore: Make author info consistent with other patterns

---

packages/create-freesewing-pattern/lib/create-library.js
packages/create-freesewing-pattern/package.json

Fixes https://github.com/freesewing/freesewing/issues/781
globby() expects forward slash characters as path separators, so calling normalize-path transforms backslashes to forward slashes on windows while preserving the drive letter (handles the case where node packages are installed on a different drive to where the command is being run).
The unixify package could be an alternative but in testing it was overly destructive on the path (stripping the drive letter) which caused issues with multi-drive environments.
When run on unix this effectively does nothing, so I didn't bother trying to test for the platform to see if calling normalize was necessary, it works fine in both environments.

Normalise source directory when passing it to globby

---

config/dependencies.yaml

The previous pull request manually edited the package.json file, I didn't realise it was autogenerated at the time.

Add normalize-path dependency to support #781

---

LATEST_NEWS.md

Updated LATEST_NEWS.md with the new 6 February 2021 contributor call date. I also fixed the link to the r/freesewing subreddit.

Update LATEST_NEWS.md with 6 February 2021 contributor call date

---

.github/ISSUE_TEMPLATE/showcase-template.md

@joostdecock let me know that we no longer list the FreeSewing username on the showcase but we can still give credit to Instagram, Twitter, Discord, or wherever the picture is from. I'm suggesting changes to the issue template based on this.
I also updated the link to the showcase how-to.

Updated showcase issue template with new how-to link and credit text

---

LATEST_NEWS.md

I updated with the next call date, 17 April 2021. (Didn't link to an agenda, but I can once the new one has been created.)

Updated next contributor call date

---

packages/create-freesewing-pattern/template/freesewing/example/src/layout.css
packages/create-freesewing-pattern/template/freesewing/example/src/layout.scss

Improves the css around box sizing and horizontal scrolling

---

packages/create-freesewing-pattern/template/freesewing/config/index.js
packages/create-freesewing-pattern/template/freesewing/example/src/App.js
packages/create-freesewing-pattern/template/freesewing/package.json
packages/create-freesewing-pattern/template/freesewing/rollup.config.js
packages/create-freesewing-pattern/template/freesewing/src/box.js

Add eslint to the dev dependencies for create-freesewing-pattern templates. When firing up a new pattern I was getting some eslint errors/warnings -- because the dependencies weren't clear, and so I've added the relevant plugins and standard configurations.
After installing the eslint dependencies, I resolved any violations that I found.

Adds eslint to dependencies and resolves code to match rules

---

packages/create-freesewing-pattern/template/freesewing/.gitignore

When I initially generated a pattern, and wanted to add my initial commit, I needed to create a `.gitignore` and add the `node_modules/` and `dist/` paths.
This simply adds a base one so others don't need to do this, and if they're not using git, they can remove it. =)
Note: This new `.gitignore` file needed to be "hard" added, since it's ignored in the [root `.gitignore`](https://github.com/freesewing/freesewing/blob/6163deb1c97dc098cd28ea27e186f78a8666ec99/.gitignore#L87).

Add base .gitignore to create-freesewing-pattern template

---

packages/i18n/src/locales/en/patterns.yml

remove references to "womenswear"/"menswear"/"men"/"women" in descriptions of patterns, and replace with "with/without breasts"

remove departments in pattern descriptions

---

packages/examples/src/point_dist.js
packages/examples/src/point_dx.js
packages/examples/src/point_dy.js

As mentioned in issue #1111, I have rewritten the examples given in the `dist()`, `dx()` and `dy()` dev docs to show the usage of these methods. It doesn't look as nice as before, but is hopefully useful as an example.
This is the corresponding PR for `freesewing`. (PR for `markdown` [here](https://github.com/freesewing/markdown/pull/246))
Feedback and improvements welcome :)

dev docs: change dx(), dy(), dist() examples -- code

---

packages/create-freesewing-pattern/lib/prompt-library-params.js

removed old departments from initial create-freesewing-pattern prompt and replaced with `tops` and `bottoms`
Not sure if anything else depends on those values, so kindly requesting review from @joostdecock once he is back from his code vacation :)
(Also: Not sure what the changelog policy is, so I didn't touch it for now.)

fix(create-freesewing-pattern): remove old departments

---

markdown/org/docs/patterns/lunetius/options/length/en.md
markdown/org/docs/patterns/lunetius/options/lengthratio/en.md
markdown/org/docs/patterns/lunetius/options/widthratio/en.md
markdown/org/docs/patterns/tiberius/options/armholedrop/en.md
markdown/org/docs/patterns/tiberius/options/clavi/en.md
markdown/org/docs/patterns/tiberius/options/clavuslocation/en.md
markdown/org/docs/patterns/tiberius/options/clavuswidth/en.md
markdown/org/docs/patterns/tiberius/options/forcewidth/en.md
markdown/org/docs/patterns/tiberius/options/headratio/en.md
markdown/org/docs/patterns/tiberius/options/length/en.md
markdown/org/docs/patterns/tiberius/options/lengthbonus/en.md
markdown/org/docs/patterns/tiberius/options/width/en.md
markdown/org/docs/patterns/tiberius/options/widthbonus/en.md
markdown/org/docs/patterns/walburga/options/headratio/en.md
markdown/org/docs/patterns/walburga/options/length/en.md
markdown/org/docs/patterns/walburga/options/lengthbonus/en.md
markdown/org/docs/patterns/walburga/options/neckline/en.md
markdown/org/docs/patterns/walburga/options/neckoratio/en.md
markdown/org/docs/patterns/walburga/options/widthbonus/en.md

Noticed that the pattern options for Lunetius, Tiberius and Walburga had title formats that were redundant. This simply removes them.

Title re-formatting, Lunetius, Tiberius and Walburga pattern options

---

.gitignore
markdown/dev/reference/api/point/angle/en.md
markdown/dev/reference/api/point/attr/en.md
markdown/dev/reference/api/point/clone/en.md
markdown/dev/reference/api/point/copy/en.md
markdown/dev/reference/api/point/dist/en.md
markdown/dev/reference/api/point/dx/en.md
markdown/dev/reference/api/point/dy/en.md
markdown/dev/reference/api/point/flipx/en.md
markdown/dev/reference/api/point/flipy/en.md
markdown/dev/reference/api/point/rotate/en.md
markdown/dev/reference/api/point/shift/en.md
markdown/dev/reference/api/point/shiftfractiontowards/en.md
markdown/dev/reference/api/point/shiftoutwards/en.md
markdown/dev/reference/api/point/shifttowards/en.md
markdown/dev/reference/api/point/sitson/en.md
markdown/dev/reference/api/point/sitsroughlyon/en.md
markdown/dev/reference/api/point/translate/en.md

- Changed all titles to `Point.method()` instead of just `method()`
- Added a brief first paragraph description of each method
- Added subheadings to divide the page (to match what Joost did for some other docs)
- Added `Point.dist()` docs that got gitignored into oblivion
- Added a bit more detail to some of the docs that were a little confusing to me.
Closes #1426

Chore: Update `Point` dev docs

---

packages/titan/src/back.js
packages/titan/src/front.js

Fix for Issue #1467 
On inspection found the option had been removed from front.js and back.js in commit 8252b12 
Made a comment on the commit but decided it was just best to make a pull request with the fix and have it be closed if the removal of the option was intentional.
This just undoes the removal of the options on front.js and back.js
Hope this helps.

Fix for #1467 Titan Waist Height not Working

---

packages/bee/src/cup.js

As I am working on Peach again I have realised that the points.waistDartRightNew could of easily been a .rotate() rather than the nonsence that it was. I made the change as I assume it will be less of a stress to run but it certainly tidies up the code a little.
To reflect this waistDartRightNew has been changed to waistDartRightRotated.

Technical Change to Bee cup.js

---

markdown/dev/howtos/code/macros/en.md

Just a quick pull request to fix a broken link I encountered while reading the documentation.

Fix broken macros documentation link

---

markdown/dev/guides/best-practices/reuse-measurements/en.md

I ran across [this page](https://freesewing.dev/guides/best-practices/reuse-measurements) while going through the design pattern tutorial. The original link to the @freesewing/models package threw a 404. I opted to update it with a link to the measurements reference page instead.

Update link on reuse-measurements page

---

packages/simon/src/frontleft-classic-cuton.js
packages/simon/src/frontleft-seamless.js
packages/simon/src/frontright-classic-cuton.js
packages/simon/src/frontright-seamless.js

I recently attempted the Simon pattern and ran into a small issue with pattern matching. As I am very new to sewing and this was my first time ever sewing from a pattern, I think it is likely that I have misunderstood something or made a mistake.  Would you mind reviewing my issue and proposed change to see whether it makes sense?
The issue is with the pattern matching between the two front pieces. When my shirt is fully buttoned, the pattern alignment is off by around six millimeters:
You can see how the pattern should match if I unbutton the shirt and shift the sides:
Looking at the generated pattern pieces and aligning the button and buttonhole lines, I see that the match lines are indeed misaligned:
As far as I can tell, this is caused by the fact that the position of the match line …

Address misaligned match lines on Simon front and left pieces

---

markdown/dev/howtos/dev/freesewing-dev/en.md

Updating to reflect that freesewing.dev is now built from the monorepo. Using instructions shared by Joost in Discord.

freesewing.dev environment setup documentation update

---

markdown/dev/tutorials/pattern-design/fitting-the-neck-opening/en.md

I was seeing this error in my browser while going through the pattern design tutorial:
Fixed the code block in the tutorial to refer to the quarterNeck that had been created beforehand and it did the trick.

Update tutorial code block

---

markdown/dev/tutorials/pattern-design/creating-the-closure/en.md

The link was broken in the docs. I updated it with the current path to the macro docs.

Update path to macros docs in tutorial

---

packages/simon/src/sleeveplacket-underlap.js

Opening this as a draft since I have low confidence I am doing the right thing.
I recently created a Simon shirt for myself. It had the following sleeve placket underlap and overlap:
Next I started working on a Simone for my wife. It had the following sleeve placket underlap and overlap:
The difference in the ratio between the underlap and overlap was very surprising to me and I found the underlap very hard to work with given its size. Looking at [the code](https://github.com/freesewing/freesewing/blob/develop/packages/simon/src/sleeveplacket-underlap.js#L18), I wondered whether maybe this was a bug:
```javascript
const width = store.get('sleevePlacketWidth') > 20 ? 10 : store.get('sleevePlacketWidth') / 4
```
This results in the following relationships:
My best guess was that the …

Use 2:1 overlap to underlap ratio for Simon sleeve placket

---

packages/plugin-scalebox/src/miniscale.js
packages/plugin-scalebox/src/scalebox.js
packages/plugin-scalebox/tests/plugin.test.mjs

1. Bound scale to the nearest of the following: 0.1, 0.2, 0.3, 0.4, 0.5. 0.6. 0.7, 0.8, 0.9, 1.0. 
2. Choose an appropriate metric and imperial scalebox size, limited to half centimeter / eighth inch precision. 
[minibox-plus-scalebox.pdf](https://github.com/freesewing/freesewing/files/7908784/minibox-plus-scalebox.pdf)

Honor scale setting in scalebox.

---

packages/freesewing.lab/package.json

This was breaking for me with:
```
error There are more than one workspace with name "freesewing.dev"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Fix typo in freesewing.lab

---

markdown/org/docs/patterns/simon/options/yokeheight/en.md
markdown/org/docs/patterns/simone/options/bustdartangle/en.md
markdown/org/docs/patterns/simone/options/bustdartlength/en.md
markdown/org/docs/patterns/simone/options/contour/en.md
markdown/org/docs/patterns/simone/options/frontdartlength/en.md
markdown/org/docs/patterns/simone/options/frontdarts/en.md
markdown/org/docs/patterns/simone/options/yokeheight/en.md

Added
- Simon(e) Yoke Height
- Simone Front Darts
- Simone Contour
- Simone Bust dart length
- Simone Bust dart angle
- Simone front dart Length
Upon re-looking through the options to compile the list of incorrect pattern options I stumbled upon these ones missing and was like oh crap they weren't on the list so quickly added to the list and made.

add(docs) Missing Simon(e) Pattern Options

---

packages/core/src/design.js
packages/core/tests/design.test.js

This adds a default `hide()` method to all pattern options
(that are not a constant) which always returns false.
The idea is that this can/will be used for conditional display
of options based on the user's input.
See Issue #1723 and PR #1798 for background info

feat(core): Add a default hide() method to options

---

config/scripts.yaml
packages/core/package.json
packages/i18n/package.json

Randomly noticed there were tests in the i18n dir that couldn't be run. Also core was missing a testci script.

Enable tests in i18n. Add missing testci to core.

---

packages/components/src/DraftConfigurator/OptionGroup/index.js
packages/components/src/Workbench/DraftConfig/index.js
packages/simon/config/index.js
packages/simon/src/buttonholeplacket.js
packages/simon/src/buttonplacket.js
packages/simon/src/frontleft.js
packages/simon/src/frontright.js

See #1723
- Update Simon to always honor `seperateButtonPlacket` and `seperateButtonholePlacket`.
- Update `DraftConfig` to pass the pattern to `DraftConfigurator` so that it can be used when configuring options to display.
- Update `OptionGroup` to hide options based on configuration.
- Update Simon to hide `buttonPlacketStyle` and `buttonholePlacketStyle` based on `seperateButtonPlacket` and `seperateButtonholePlacket`.
If this approach ends up being reasonable, I think the next steps will be to:
- Add tests (I couldn't figure out where to do this).
- Maybe add this functionality to other patterns which would benefit.
- Update the options docs to describe this functionality.

Enable conditional display of options (Use in Simon)

---

.github/workflows/tests.all.yml
.gitignore
package.json
scripts/test-failure-collector.js
scripts/testall.js

I recently made a cross-cutting change and needed to run all tests in order to verify the change was safe. While doing this I noticed that the `testall` script exits after one or more tests fail in a single package. This means you must fix issues one package at a time, then rerun all tests to find the next failure. I tried using the `--no-bail` flag to avoid this problem, but that does not make it easy to find which tests failed as failures are buried in thousands of lines of logs.
In this change I am suggesting we do the following:
- Use the `--no-bail` option by default (all tests only take 50 seconds to run).
- Introduce a way to aggregate failures from all packages (writing to a file).
- Print a summary of failures after all tests complete.
- Introduce an All Tests workflow which …

Update testall to report all failures. Add All Tests workflow.

---

markdown/dev/reference/api/config/options/en.md

chore(markdown): fix typo in options/en.md

---

markdown/org/docs/patterns/lunetius/cutting/en.md

Moved the cutting list to the top of the page, as that reads easier than having it interspersed in the text.

Moved cutting list to top

---

packages/components/src/Workbench/index.js

Attempting to address https://github.com/freesewing/freesewing/issues/1843.
See https://stackoverflow.com/questions/65849051/calc-not-working-with-stroke-dashoffset-in-safari-and-firefox
This might not get us all the way but it at least resulting in paths being rendered in my local Simon.

#1843 Use units in css scale var.

---

config/scripts.yaml
packages/create-freesewing-pattern/package.json
packages/create-freesewing-pattern/tests/cli.test.mjs

#1891 breaks the `create-freesewing-pattern` package but All Tests is green. Adding a test which simply runs `node ./lib/cli.js -h` and asserts that the command runs successfully.

Add smoke test for create-freesewing-pattern.

---

packages/components/src/Workbench/Measurements/index.js

This fixes a regression bug introduced in 283fa4f884dce01b007f11a84718da870ed6feb8 and in doing so will close #1918.
The issue is that we just copied the code block from the required measurements.
But those are always set, whereas `optionalMeasurements` is not.
We could do the whole of making sure they are always set, but I went for the simple solution by just adding a check here.
My reasons for doing so is that once the new website is up, the entire `components` package will get deprecated and dropped :fire:

fix(workbench): Type-check optionalMeasurements. Closes #1918

---

packages/yuri/src/gusset.js

As pointed out by sean#4312 in discord https://discord.com/channels/698854858052075530/757632180980547686/959311669841002566 . Yuri's grainline was indicating cut on fold whereas the seam allowance was indicating a seam. After discussing with @hellgy it was determined to be cut on fold and I was giving permission to quickly patch it. 
From:
To:
Note: The difference in letter sizing is due to my components workaround and is not part of this pr.
Changes
- paths.sa has been changed to show cut on fold.
Additions
- Added path.saBase to alter seam allowance correctly.

Correcting Yuri's Gusset Seam allowance.

---

packages/i18n/src/locales/en/options/lunetius.yml

changed the option description for `toUpperLeg` from "Below the hips" to "To the upper leg", as that is technically correct (it uses the `waist to upper leg` measurement). It sounds a bit more clunky, so opinions? (I'm also not sure if changing this here impacts anything else apart from the translation files, hence a PR and not a direct commit.)

fix(lunetius-option-desc): to upper leg

---

markdown/dev/reference/api/config/options/en.md
markdown/dev/reference/api/snippets/buttonhole-end/en.md
markdown/dev/reference/api/snippets/buttonhole-start/en.md
markdown/dev/reference/api/snippets/buttonhole/en.md

Noticed this when trying to look it up. The counter page exists it is just not registered as count so the link needed changing :)
Edit: Noticed the buttonhole pages had broken links as well
Changes
- Changed link from "count" to "counter"
- Added api to buttonhole links

fix(link) Broken Links, Counter and ButtonHoles

---

packages/shin/src/back.js
packages/shin/src/front.js
packages/shin/src/waistband.js

For issue #2165 
Using the grainlines from https://freesewing.org/docs/patterns/shin/cutting/ as reference.
Additions
- Added grainline on back,js
- Added grainline on front.js
- Added grainline on waistband.js
Changes
- Tweaked the horizontal distance of the scalebox on back.js to reduce chance of overlap with the new grainline.
I was up and simple fix, understand though if you don't like the way I have done it.

Shin - Adding Grainlines

---

packages/titan/src/front.js

Had noticed this a couple times that with certain configurations of options the sideSeam on Titan's Front would extend beyond the waist seam. Originally I didn't think too much off it as I thought it would simply be something compensated for when extending the block but since I was dabbling in that atm and since I prefer lower rise trousers it was bothering me. after a bit of sloothing I found that once again it was an accidental oversight when the waistband was changed to pct snap option with options.waistHeight on points,seatOutCp1 being removed. This commit simply re-adds it. Have tested it too :)
Changes
Re-added options.waistHeight on point,seatOutCp1
Edit: Hit Enter too soon gg me.

Fixing Titan's Waist

---

packages/freesewing.lab/components/pattern-picker.js
packages/freesewing.lab/hooks/useApp.js
packages/freesewing.lab/page-templates/pattern-list.js
packages/freesewing.shared/components/navigation/primary.js

Another fix to make it easier to use freesewing as a library. set what you can navigate to in useApp and then use that everywhere instead of re-generating it for various nav interfaces.
Also allow an icon list to be passed in to the pattern list, for easier customization

Use single source of truth for navigation

---

designs/wahid/src/back.js
designs/wahid/src/front.js

Currently, when seam allowance is drawn on the patterns, a triple allowance is given on the bottom of the Wahid pieces, as they are labeled "hem allowance". However since Wahid has a lining rather than a rolled hem this is unnecessary and potentially confusing.

Change hem allowance on Wahid to standard SA

---

designs/bee/src/cup.js

Saw that this was possible https://discord.com/channels/698854858052075530/698862765053575188/995694438250708993
Immediatedly updated.
Changes
- Manual removal of macros changed to automatic.

chore(bee): Remove macros through the API, not manually

---

sites/lab/components/layouts/lab.js
sites/lab/components/pattern-picker.js
sites/shared/components/locale-picker.js
sites/shared/components/navigation/primary.js
sites/shared/components/picker.js
sites/shared/components/theme-picker.js

- add missing design names to mobile nav
- remove pattern picker from mobile nav because the patterns are listed
- add key to pattern picker spans to get rid of no key error
- don't put `dropdown-end` class on pickers on left hand side of header to make sure the whole width of the picker is visible on narrower screens

Menu fixes

---

.gitignore
config/dependencies.yaml
config/scripts.yaml
packages/i18n/package.json
packages/i18n/scripts/prebuilder.mjs
packages/i18n/src/next.mjs
packages/i18n/src/prebuild.mjs
packages/pattern-info/package.json
packages/rehype-jargon/CHANGELOG.md
packages/rehype-jargon/README.md
packages/rehype-jargon/package.json
packages/rehype-jargon/src/index.js
packages/remark-jargon/package.json
packages/remark-jargon/src/index.js
scripts/reconfigure.mjs
sites/shared/mdx/loader.js
sites/shared/prebuild/i18n.mjs
yarn.lock

- reconfigure script now checks if packages have a prebuild script when writing cibuild steps, and adds that as `precibuild_stepx` to the package.json of that package
- `sites/shared/prebuild/i18n.mjs` now calls the build method in `packages/i18n/src/prebuild.mjs` to reduce maintenance

Fix: Prebuild scripts for cibuild_step scripts

---

.github/workflows/tests.all.yml
config/scripts.yaml
markdown/dev/reference/api/part/en.md
package.json
packages/core/.nycrc.yaml
packages/core/package.json
packages/core/src/part.js
packages/core/src/path.js
packages/core/src/point.js
yarn.lock

This started out as me working on keeping grainline and cut info in the part properties. 
But then I added some utility methods to core. And then I was like, hmm tests. 
And then I realized we don't have coverage reports integrated in the repo. So now it's all that.

core: Code coverage and grain/cut changes

---

CHANGELOG.md
config/changelog.yaml
designs/simon/src/buttonholeplacket.js
designs/simon/src/buttonplacket.js
designs/simon/src/yoke.js

This fix removes the superfluous notches in Simon's button and buttonhole plackets. 
It also removes the floating bnotch that appears with a split yoke. I came to the conclusion that the bnotch was probably a leftover debug tool or otherwise unintended.
(I am not sure whether I also need to update `designs/simon/CHANGELOG.md`, but I didn't see it updated in a similar previous PR.)

fix(simon): Remove superfluous notches. Fixes #2399

---

markdown/dev/tutorials/getting-started-linux/dev-setup/en.md
markdown/dev/tutorials/getting-started-mac/dev-setup/en.md

A few corrections for the tutorial pages. Most are minor, but the incorrect npm `-G` option causes the tutorial to fail.

Correct dev setup tutorial for Mac and Linux

---

markdown/dev/reference/plugins/banner/en.md
markdown/dev/reference/plugins/bartack/en.md
markdown/dev/reference/plugins/bundle/en.md
markdown/dev/reference/plugins/measurements/en.md
markdown/dev/reference/plugins/mirror/en.md

Some plugin-bundle plugins (the ones added later?) weren't listed in the documentation. This PR fixes that situation.

Document all plugin-bundle plugins.

---

markdown/dev/reference/api/snippets/bnotch/en.md
markdown/dev/reference/api/snippets/notch/en.md

As I understand it, at one time notch and bnotch were in plugin-theme, but they were subsequently moved to plugin-notches. (A minor documentation issue, but it did cause me some grief spending time looking through the plugin-theme source code, trying to find where notch was defined.)

notch/bnotch snippets come from plugin-notches, not plugin-theme

---

markdown/dev/reference/api/snippet/attr/en.md

https://freesewing.dev/reference/api/snippet/attr
The current web page links to 404 pages:
https://freesewing.dev/reference/api/snippet/attributes#add
https://freesewing.dev/reference/api/snippet/attributes#set

Fix Snippet.attr() webpage URLs.

---

sites/shared/components/picker.js

fixes #2487 
Something about the Daisy dropdown styling still being on the menus was messing them up in safari, I guess competing concerns? They work now

Fix #2487: picker menus work in safari

---

packages/core/src/part.js
packages/core/src/pattern.js
packages/core/tests/part.test.js
packages/core/tests/pattern.test.js
packages/core/tests/snippet.test.js
packages/core/tests/store.test.js
packages/core/tests/svg.test.js
plugins/plugin-cutonfold/src/index.js
plugins/plugin-grainline/src/index.js

> Note that this includes changes in some open PRs since I was blocked by the pending reviews.
But this adds a `pattern.getCutList()` method that returns the `cut` properties of all parts that were included in the most recent `pattern.draft()` call.

feat(core): Added pattern.getCutList() method

---

scripts/reconfigure.mjs

@woutervdub 's merge request was failing because the tests weren't properly configure.
This merge request fixes that by adding the auto-generation of the (shared) test files for designs/plugins to the reconfigure script

chore: Reconfigure generate shared tests for plugins/designs

---

markdown/dev/guides/markdown/custom-components/en.md
markdown/dev/howtos/ways-to-contribute/showcase-our-patterns/en.md
markdown/dev/tutorials/getting-started-gitpod/en.md
markdown/dev/tutorials/getting-started-linux/dev-start/en.md
markdown/dev/tutorials/getting-started-mac/dev-start/en.md
markdown/dev/tutorials/pattern-design/testing-your-pattern/en.md

Fixes the errors returned when running `yarn build` in `sites/dev`. I guess maybe the linting made these changes, but running `yarn fixdocs` in root didn't reset them, so I'm not fully sure where they came from, but they're all from this commit: https://github.com/freesewing/freesewing/commit/265ad404da6763e105be51ec2aa1ca142f9e100f

[fix] fix parsing errors in markdown preventing successful dev build

---

markdown/dev/tutorials/getting-started-linux/dev-setup/en.md
markdown/dev/tutorials/getting-started-linux/dev-start/en.md
markdown/dev/tutorials/getting-started-mac/dev-setup/en.md
markdown/dev/tutorials/getting-started-mac/dev-start/en.md
markdown/dev/tutorials/getting-started-windows/en.md

Some small changes and corrections to the Mac and Linux Getting Started tutorials, and a large change to the Windows tutorial.
- From observation while testing the tutorials, the commands are now `npm run dev` and `yarn dev` (instead of `npm run start` and `yarn start`).
- I changed the "Windows is unsupported" comment to a warning, with wording changes that are hopefully both clearer and friendlier.
- (We could further change the wording from "happy to assist you" to "happy to try to assist you", if we need to promise less.)
- In the Windows tutorial I re-arranged the sections to have a single "Setup/Start the Development Environment" section at the end. For those sections, I updated the instructions (copied from the Mac/Linux tutorials).
I have not tested the Windows tutorial …

Update Getting Started tutorials

---

markdown/org/docs/patterns/simon/instructions/en.md

I replaced "single" and "double" notch with the symbols for these notches (to reflect the with the pattern notation guide https://freesewing.org/docs/various/notation/notches/ ).
I also tweaked the word order of a couple of sentences for clarity.

Fix Simon notch typos

---

LATEST_NEWS.md

No discussion specific to the next CC call exists, so I linked to the Discussions page

Updated contributor call date

---

.gitpod.yml

This improves prebuild times for PRs, and it should also mean that we less frequently have to tell people "just shut down and re-open your workspace". As far as I can tell, it has no adverse effects.

move kickstart out of gitpod prebuild

---

designs/charlie/config/index.js
designs/paco/config/index.js
designs/titan/config/index.js
designs/titan/src/back.js
designs/titan/src/front.js

As mentioned in #2558 this update adds the following notches.
- Cross and Crotch Seam notches
- Hip notches (when the rise is high enough)
- Seat Notches
- Knee notches
Changed logoAnchor.y to fork.y to minimise overlap of new paths.
Another thing I added was Hip Line and Seat Line paths to better identify where the hip line is with the notches.
I have also changed the waistbandWidth option to allow 0%, whilst the waistband being included is awesome for extending it is not the best for those who are using Titan as a physical block or for those who are testing Titan to check their measures.
Whilst not strictly necessary for extending Titan as some of these notches may be in a different place when extended, it will benefit those who are using Titan as it is described in its instructions. …

Titan Notches for #2558

---

designs/unice/example/netlify.toml
markdown/dev/guides/markdown/custom-components/en.md
markdown/dev/howtos/code/adding-instructions/en.md
markdown/dev/howtos/code/extend-pattern/en.md
markdown/dev/howtos/code/hide-paths/en.md
markdown/dev/howtos/code/remove-paths/en.md
markdown/dev/howtos/code/shared-dimensions/en.md
markdown/dev/howtos/code/storing-path-length/en.md
markdown/dev/howtos/design/fit-sleeve/en.md
markdown/dev/howtos/design/seam-allowance/en.md
markdown/dev/howtos/design/slash-spread/en.md
markdown/dev/howtos/design/sprinkle-snippets/en.md
markdown/dev/reference/api/config/en.md
markdown/dev/reference/api/path/trim/en.md
markdown/dev/reference/plugins/bust/en.md

Some of these links were actually broken, since they expect to find designs under the `packages/` directory in the current `develop` branch. Other links were technically okay, since they link to old commits, but updating those links may still help to reduce confusion.
Also fix a reference to `packages/unice` in a `netlify.toml` file. (Untested, but I don't think this is an actual Netlify configuration.)

fix: Broken/misleading links to designs' source code

---

tests/patterns/config.mjs
tests/plugins/shared.mjs

testci is currently failing now that package versions have been [bumped to `3.0.0-alpha.0`](https://github.com/freesewing/freesewing/commit/ae40299#diff-2d72bdead8afa0798d18995311992d684348a694c2d5e214e8e4d2b6153e4821). Alpha and beta version numbers have existed before, but only as recently as `v2.1.0-alpha.0` and `v2.7.0-beta.3` respectively, both of which preceded [the assertions in question](https://github.com/freesewing/freesewing/commit/7ddb023c8d13db4f7afa383378f295a53d38238d).
This PR updates those assertions to accept `alpha` or `beta` package versions, in addition to the already-supported `rc` and stable (non-suffixed) package versions.

fix(testci): Accept `alpha` and `beta` package versions

---

.github/boring-cyborg.yml

In #2619 / 501db1d1d8e3e6f79de084130c25839c261e4a54 I was trying to make `boring-cyborg` work better than before, but I accidentally made things worse. I'm sorry! I've tested this fix by configuring the bot in a personal repo.

fix(boring-cyborg): Fix typo in boring-cyborg.yml

---

markdown/org/docs/patterns/octoplushy/instructions/en.md

One of those classics of github being fancy and not strict. 
There was a accidental line break that breaks the formatting of the bullet points on the website. 
This simply removes it to hopefully fix the formatting otherwise something deeper is going on.

[fix] Octoplushy Instructions incorrect format

---

.nvmrc

chore: Bump .nvmrc up to Node 16 LTS

---

markdown/dev/tutorials/getting-started-linux/installing-node/en.md
markdown/dev/tutorials/getting-started-linux/node-versions/en.md
markdown/dev/tutorials/getting-started-mac/installing-node/en.md
markdown/dev/tutorials/getting-started-windows/en.md

(I do not know if the Node.js "bug in the dependency resolution process" mentioned in the Windows tutorial still exists, but I left that wording intact and updated the suggested Node version to "16.17.0".)

Update tutorial instructions to use Node 16.

---

designs/aaron/src/index.mjs

- This is a PR into the v3 branch.
- This PR removes the plugin info from `index.mjs` for aaron. 
- However, it does _not_ move the plugin info into any other file. 
This is because aaron's `front.mjs` imports `base` from brian, and that part already imports pluginBundle. As I understand it, plugins are configured only once in the first part that uses them, and they should not be re-configured again in other parts. If this is incorrect, please let me know.

Move aaron plugin config to part-level.

---

designs/bee/src/index.mjs
designs/bee/src/neck-tie.mjs
designs/bella/src/back.mjs
designs/bella/src/index.mjs

PR into v3 branch.
There is an issue with bee where the imported bella front and back parts are incorrectly not hidden, and these two parts are appearing by default in the lab.

Move bee and bella plugin config to part-level. Use new data property.

---

designs/albert/src/front.mjs
designs/albert/src/index.mjs
designs/albert/src/pocket.mjs
designs/albert/src/strap.mjs

I was not able to get albert's `crossBox` local plugin to not get `ReferenceError: Cannot access 'crossBox' before initialization` errors. I even tried moving the plugin to a separate file outside of `index.mjs`, but that did not work. For now, the `crossBox` plugin is commented out in `front.mjs`.

Complete porting albert to v3.

---

plugins/plugin-scalebox/src/scalebox.mjs
plugins/plugin-title/src/index.mjs

Before and after for title and scalebox:

v3 updates for plugin-title and plugin-scalebox

---

sites/shared/components/workbench/layout/cut/index.js
sites/shared/components/workbench/layout/print/index.js

Before the fix:
After the fix:

Fix v3 ForPrinting and ForCutting layouts to use design shortname.

---

config/build-order.mjs

This PR just changes `config/build-order.mjs`. It does not contain any `yarn reconfigure` changes. We'll pick up the rest of the build order changes the next time v3 gets reconfigured and put back.
(But, if you think I should include the workspace reconfigure changes in this PR, please let me know and I will add them.)

Move snapseries to earlier build order.

---

designs/waralee/src/backpocket.mjs
designs/waralee/src/cutout.mjs
designs/waralee/src/facings.mjs
designs/waralee/src/mini.mjs
designs/waralee/src/pants.mjs
designs/waralee/src/pantsproto.mjs
designs/waralee/src/pocket.mjs
designs/waralee/src/waistband.mjs

A PR back into the v3-stage2 branch.
`waistband.mjs` is slightly different because the draft method is being passed an extra `type` parameter. I think I did the port okay because it seems to work fine in the lab.

chore(waralee): Port to v3 stage 2

---

designs/ursula/src/back.mjs
designs/ursula/src/elastic.mjs
designs/ursula/src/front.mjs
designs/ursula/src/gusset.mjs

A PR back into the v3-stage2 branch.
This PR also includes an Ursula fix, adding the missing pluginBundle to `front.mjs`.

chore(ursula): Port to v3 stage 2. Also adds pluginBundle fix.

---

packages/i18n/src/locales/en/options/noble.yml
packages/i18n/src/locales/en/options/octoplushy.yml

Fix wrong option name in `octoplushy` (was `length`, should be `width`) and typos in options of `noble`.

fix: wrong option name in octoplushy and typos in noble's options

---

markdown/org/docs/patterns/diana/fabric/en.md
markdown/org/docs/patterns/diana/needs/en.md
markdown/org/docs/patterns/jaeger/cutting/en.md
markdown/org/docs/patterns/jaeger/instructions/en.md
markdown/org/docs/patterns/jaeger/needs/en.md

Fixes multiple minor typos, one markdown issue for a heading and updates the cutting instruction for Jaeger to cut *two* undercollars, not one.

Fix typos in documentation and update cutting instruction for Jaeger

---

designs/tutorial/src/bib.mjs
designs/tutorial/src/configpart.mjs
designs/tutorial/src/step1-4.mjs
designs/tutorial/src/step5-8.mjs
designs/tutorial/src/step8.mjs
designs/tutorial/src/step9-11.mjs

A PR back into the v3-stage2 branch.
There is a `step8.mjs` file that doesn't appear to be used anywhere in the design. I made v3 stage 2 porting changes to this file and included it in the PR, but I am wondering whether it should be deleted?

chore(tutorial): Port to v3 stage 2

---

packages/core/src/index.mjs
packages/core/src/part.mjs
packages/core/src/pattern.mjs
packages/core/src/stack.mjs
packages/core/src/store.mjs
packages/core/src/utils.mjs
packages/core/tests/part.test.mjs
packages/core/tests/pattern-init.test.mjs
packages/core/tests/stacks.test.mjs
packages/core/tests/utils.test.mjs
sites/shared/components/workbench/draft/index.js
sites/shared/components/workbench/draft/stack.js
sites/shared/components/workbench/draft/svg-wrapper.js

This moves from `part` to `stack` as the basic building block for layouts. A `stack` will typically contain just 1 part and thus be a mere wrapper. But a `stack` can contain multiple parts that will be anchored relatively to each other (aka use the same coordinate space) yet from a layout perspective, they will be one block.
In practical terms, things like `width`, `height`, `topLeft`, and `bottomRight` will be set on the `stack`, not the `part`.
The relevant methods have also been renamed so `utils.generateStackTransforms` instead of `utils.generatePartTransforms`.

feat: Stack based layouts in core

---

designs/charlie/src/fly-extension.mjs

The seam was accidentally hidden by c5138aad991d4e1b46ac84cbad0db5f93b8e62ca :
```diff
-    .setRender(false)
-  paths.seam = paths.saBase
-    .clone()
-    .line(points.flyCorner)
-    .close()
-    .setRender(true)
-    .attr('class', 'fabric')
+    .hide()
+  paths.seam = paths.saBase.clone().line(points.flyCorner).close().hide().attr('class', 'fabric')
```

fix(charlie): Unhide accidentally-hidden seam for Fly Extension part.

---

designs/hi/src/body.mjs

Hi's body seam accidentally got hidden during the `setRender()` -> `hide()` change of c5138aad991d4e1b46ac84cbad0db5f93b8e62ca. This PR unhides it.

fix(hi): Unhide accidentally-hidden seam.

---

designs/lunetius/src/lacerna.mjs

Lunetius' Lacerna seam accidentally got hidden during the `setRender()` -> `hide()` change of c5138aad991d4e1b46ac84cbad0db5f93b8e62ca. This PR unhides it.

fix(lunetius): Unhide accidentally-hidden seam.

---

.github/workflows/codeql-analysis.yml
.github/workflows/tests.all.yml

I assume we want some form of CI on the `v2` branch; currently there's none configured in .github/workflows, either on `v2` or on `develop`. This change would be made in both branches.
Technically, we could bifurcate the workflow configuration files such that configs in the `v2` branch target `v2` and configs in the `develop` branch target `develop`; but I think it's safer to have complete configuration files that can be synced from one branch to another.

chore(v2): Run the test and CodeQL workflows on `v2`, not just on `develop`

---

designs/cornelius/src/pocket.mjs
designs/cornelius/src/pocketfacing.mjs

Two seams were accidentally hidden in the `setRender()` -> `hide()` change.

fix(cornelius): Unhide accidentally-hidden seams in Pocket and Pocket Facing

---

designs/yuri/src/index.mjs

Yuri was ported to v3 via 4086f2de1dbb7f4b6275caeea5c004e80d06d556, with the hoodCenter part commented out and the commit comment of:
> wip(yuri): Ported to v3
>  
>    The tests don't pass (for giants) but everything works fine in the lab
so it might be an issue with how the tests are setup.
I'll investigate this later.
I uncommented the hoodCenter part and ran `yarn test` without any errors, including in the "Draft for giant" section. So, it appears that the part might be safely re-added now?

chore(yuri): Re-add the temporarily-removed hoodCenter part.

---

designs/benjamin/src/ribbon.mjs

When I ported Benjamin to v3, I neglected to add the `after: base` dependency in `ribbon.mjs`. This PR corrects that.
(The issue doesn't normally cause problems. The exception is when the Ribbon part is selected in Contents/Only, at which point an error occurs.)

fix(benjamin): Add missing dependency to Ribbon.

---

designs/legend/src/index.mjs

The `develop` localhost lab version of the Legend design is missing the dimension and seam allowance elements that are on the lab.freesewing.dev version. I assume that they were accidentally omitted? If so, this PR re-adds them.

fix(legend): Add missing dimension and sa elements.

---

designs/legend/src/bartack.mjs

The `develop` localhost lab version of the Legend design has unused bartack-related options. I assume that these were accidentally left in when the code was copied over from PluginTest? If so, this PR removes them.

fix(legend): Remove bartack options.

---

designs/plugintest/src/plugin-measurements.mjs

If PluginTest is supposed to actually test plugin functionality, then the design should require the measurements that measurementsPlugin needs.

fix(plugintest): Add measurements required for calculated measurements.

---

sites/shared/components/workbench/draft/error.js

This PR fixes an error in 295d3481f9faa813b8162a8cf8e7cd73629b00ae that caused draft/set errors and warnings to be incorrectly counted against patterns:
```
There are 2 errors in the pattern logs
There are 8 warnings in the pattern logs
```
It also normalizes the variable name from `set` to `sets` (assuming that there will be multiple sets in the future, not just Set 0).

fix(shared): Correct error/warning counts for sets.

---

markdown/dev/guides/v3/en.md
markdown/dev/guides/v3/migration/en.md
markdown/dev/howtos/git/editing-content-on-github/en.md
markdown/dev/reference/api/en.md

There are a few broken links where I could not find where they supposed to go (nothing in the search):
On https://freesewing.dev/reference/api:
`/reference/api/utils/generateStackTransform`
`/reference/api/utils/curveedge`
On https://freesewing.dev/guides/v3:
`/reference/api/attributes/addclass`
`/reference/api/store/remove`
I pointed the `part` links to the `/part/draft` pages, I hope that's correct.
Also, there is no quick start guide, right, @joostdecock? I linked to the tutorials instead.
Additionally, I added a link to the translation guide in the part where we talk about the `en.md` files.

Fix more broken links & typos, add link to translation guide

---

config/changelog.yaml

It resulted in `npm run reconfigure` failing, which in turn made `yarn new design` fail in a spectacular and confusing way.

Remove duplicated `Added:` in changelog

---

sites/email/package.json

A fix to avoid a `yarn kickstart` error: https://github.com/freesewing/freesewing/issues/3052

(fix) Add name to sites/email/package.json. Fixes #3052.

---

config/software/designs.json

This PR changes the two instances of "historic" tags to "historical" in `config/software/designs.json` for consistency. The other two designs use "historical".
I checked with the design author, and they are okay with this change:
https://discord.com/channels/698854858052075530/757631205804998759/1028313790904815719

chore(designs.json): Normalize tags by changing "historic" to "historical".

---

packages/new-design/templates/from-bella/package.json.mustache
packages/new-design/templates/from-bent/package.json.mustache
packages/new-design/templates/from-breanna/package.json.mustache
packages/new-design/templates/from-brian/package.json.mustache
packages/new-design/templates/from-scratch/package.json.mustache
packages/new-design/templates/from-titan/package.json.mustache
packages/new-design/templates/from-tutorial/package.json.mustache

This PR fixes https://github.com/freesewing/freesewing/issues/3050 by specifying Next.js version 12 in the `package.json` files. The version that we previously specified was simply "latest", and this is caused issues after Next.js updated to version 13.
Because the issue is affecting standalone development via `npx @freesewing/new-design@next`, after the code changes are pulled the fix will also need to be deployed, if that is a separate step.

fix(new-design): Use Next.js version 12. Fixes #3050.

---

packages/new-design/templates/from-bella/package.json.mustache
packages/new-design/templates/from-bent/package.json.mustache
packages/new-design/templates/from-breanna/package.json.mustache
packages/new-design/templates/from-brian/package.json.mustache
packages/new-design/templates/from-titan/package.json.mustache

This fixes https://github.com/freesewing/freesewing/issues/3051 for all of the new-design templates by adding the missing dependencies to `package.json`.

fix(new-design): Add missing dependencies to package.json. Fixes #3051.

---

config/software/packages.json

"snapseries" is listed twice in `config/software/packages.json`. This PR removes one of the entries.

(fix) Remove duplicate snapseries package from software config.

---

.github/ISSUE_TEMPLATE/01_bug-report.yaml
.github/boring-cyborg.yml
config/build-order.mjs
config/dependencies.yaml
sites/shared/config/next.mjs

This PR changes instances of `config-helpers` to `snapseries` (or removes it where appropriate). 
For the design dependencies yaml template, it removes `config-helpers` from all designs and adds `snapseries` to the individual designs that require it. (I didn't touch the actual `designs/*/package.json` files. They will just get updated with the next `yarn reconfigure`.)
Additional edits were made by `eslint`.

chore: Change config-helpers to snapseries

---

designs/breanna/src/dart-utils.mjs

This PR fixes the issue of when there is no secondary bust dart (set to none or set to same as primary bust dart), 6 warning messages are logged.

fix(breanna): Eliminate warning messages when there is no secondary dart

---

packages/core/src/path.mjs

Per the comments in https://github.com/freesewing/freesewing/commit/fab1e2f8777e75ef950016b594230435752ccf30, that commit which added `Path.clean()` also introduced 3 test errors:
```
1) Path
offset
Should offset a curve:
ReferenceError: Cannot access 'cur' before initialization
...
2) Path
offset
Should offset a curve where cp1 = start:
ReferenceError: Cannot access 'cur' before initialization
...
3) Path
offset
Should offset a curve where cp2 = end:
ReferenceError: Cannot access 'cur' before initialization
at Path.clean (.../packages/core/src/path.mjs:186:34)
...
```
The issue seems to be limited to the test errors. No problems are seen in the `develop` localhost lab.

fix(core): In Path.clean(), initialize cur variable before use.

---

sites/org/jargon.mjs

From the documentation page https://freesewing.dev/guides/markdown/jargon#adding-jargon , it appears that the intention was that a `sites/org/jargon.mjs` file should exist. However, that file does not exist, and the URL linked on the documentation page points to a 404 page.
This PR adds the missing jargon file.

chore(org): Add jargon file. Fixes #3109.

---

markdown/dev/reference/api/pattern/sampleoption/en.md
packages/core/src/pattern.mjs

This is a more complicated PR, with a number of changes to `packages/core/src/pattern.mjs` to allow `Pattern.sampleOptions()` to work with all option types:
- Return an empty array of sets if the `optionName` does not exist (instead of throwing an error).
- Code refactoring to allow a different numbers of runs/steps (needed for `count` and `mm` options where there might be fewer than 10 values to step through).
- For `count` and `mm` options, adjust the number of runs/steps if needed and `round()` the values to integers.
- Extend `__listOptionSets()` to also work with Boolean options. Rename the method to `__listBoolOptionSets()`.
The PR also includes an update to the `Pattern.sampleOptions()` documentation for the new functionality.
I tested the code changes with every type of option, …

fix(core): Update Pattern.sampleOptions() and documentation

---

sites/dev/package.json
sites/lab/package.json
sites/org/package.json
yarn.lock

- add necessary i18next peer dependencies to lab to get rid of errors
- pin next version to 13.0.5 because 13.0.6 seems to be missing the bin script
- do a little cleanup in the lab's dependencies while I'm in there

chore(deps) fix dependency issues

---

markdown/dev/reference/measurements/en.md

This PR arranges Measurements into a table, along with a short description of each measurement. (The goal is to help developers understand what measurement names represent without having to refer back to the other measurement documentation on the .org site.) It also adds more information about the measurements from `plugin-measurements` and `plugin-bust`.

fix(docs): Arrange measurements into a table with additional information

---

markdown/dev/reference/api/en.md
markdown/dev/reference/api/part/draft/en.md
markdown/dev/reference/api/utils/curveedge/en.md
packages/core/src/part.mjs

This is the documentation that was written by @BenJamesBen for the `utils.curveEdge()` method.
However, the underlying Bezier library is not available in the part's draft method.
Ben worked around this by creating a dedicated method to create a Bezier instance in utils.
However, after giving it some thought, I think it's better to just make the Bezier library available in the part's draft method so that users can use it for whatever.
I have cherry-picked Ben's documentation commits, and adapted the example to use the Bezier library passed to the draft method. And obviously adapted core to pass it in the first place.
This PR replaces #3181

chore(docs): Add Utils.curveedge() documentation. Closes #3143. Replaces #3181

---

packages/core/src/pattern.mjs
plugins/plugin-theme/src/css.mjs
plugins/plugin-theme/src/index.mjs
sites/shared/components/workbench/draft/part/index.js
sites/shared/components/workbench/exporting/export-handler.js
sites/shared/components/workbench/exporting/pdf-maker.js
sites/shared/components/workbench/layout/draft/index.js
sites/shared/components/workbench/layout/draft/stack.js
sites/shared/components/workbench/layout/print/plugin.js
sites/shared/components/wrappers/workbench.js
sites/shared/package.json
yarn.lock

expected behavior:
exporting to SVG and PDF with `paperless: true` will include the gridlines and measurement markup in the export without errors
Resolves #3008

[Fix] Paperless exports to SVG and PDF

---

markdown/dev/reference/api/part/draft/en.md

I am not sure how to explain or document what `context` is. However, it exists and should be documented (unless the intention was that is supposed to be undocumented). 
I note that `context` is the only way to access `settings.debug`, as I understand it.

fix(docs): Add context property to Part.draft()

---

markdown/dev/reference/settings/complete/en.md
markdown/dev/reference/settings/en.md
markdown/dev/reference/settings/layout/en.md
markdown/dev/reference/settings/locale/en.md
markdown/dev/reference/settings/margin/en.md
markdown/dev/reference/settings/measurements/en.md
markdown/dev/reference/settings/only/en.md
markdown/dev/reference/settings/paperless/en.md
markdown/dev/reference/settings/sa/en.md
markdown/dev/reference/settings/scale/en.md
markdown/dev/reference/settings/units/en.md

I've included the previously-undocumented `settings.debug`, though it is unclear whether it was intended to exist. It doesn't seem to be used in `core` or in any designs.

fix(docs): Settings documentation updates

---

markdown/org/docs/measurements/shouldertoelbow/en.md
markdown/org/docs/measurements/shouldertoshoulder/en.md
markdown/org/docs/measurements/shouldertowrist/en.md

This PR updates the documentation for Shoulder to Elbow, Shoulder, to Shoulder, and Shoulder to Wrist measurements to use the same "tip of the shoulder" wording to describe the start point and where it is located.
(I am holding this as a draft PR for 3 days before marking it as ready.)

fix(docs): Harmonize shoulder tip measurement wording

---

config/dependencies.yaml
sites/email/package.json
sites/shared/package.json
yarn.lock

Updated following dependencies in the central config:
- 'tailwindcss-box-shadow': '2.0.0'
- 'tailwindcss-email-variants': '2.0.0'

chore: Updated depdencies

---

.github/ISSUE_TEMPLATE/04_showcase-template.yaml

3 minor corrections to the New Showcase issues template, plus 1 experimental change to the `labels:` property.
Currently, Labels are not populated in the GitHub New Showcase issue form. The change fixes this so the 3 Labels are automatically populated.
The change is experimental because I am not able to test its effect on the [GitHub New Issue page](https://github.com/freesewing/freesewing/issues/new/choose) until the template file is actually put back into the repository. However, I believe that it might be correct based on the fact that the following URL does cause the Labels to be populated correctly:
`https://github.com/freesewing/freesewing/issues/new?assignees=&labels=:%2B1:+good+first+issue%2C+:camera_flash:+showcase%2C+:hugs:+community&template=04_showcase-template.yaml&title=%5Bsh …

fix(github): Showcase issues template updates and corrections

---

.github/ISSUE_TEMPLATE/01_bug-report.yaml
.github/ISSUE_TEMPLATE/02_feature-request.yaml
.github/ISSUE_TEMPLATE/03_documentation-update.yaml
.github/ISSUE_TEMPLATE/05_all-contributors.yaml

This PR changes the GitHub issues templates to use shortcodes for emoji, so the labels get automatically populated on new issues.
(My commit changes only 1 line in each file. All of the other changes were made by `eslint`.)

fix(github): Use shortcodes for labels emoji

---

packages/core/src/part.mjs
packages/core/tests/part.test.mjs

As requested by @BenJamesBen in #3282

feat(core): Make Part.getId() a prototype method

---

markdown/dev/howtos/design/fit-sleeve/en.md
markdown/dev/reference/api/part/config/options/pct/fromabs/en.md
markdown/dev/reference/api/part/config/options/pct/snap/en.md
markdown/dev/reference/api/path/shiftalong/en.md
markdown/dev/reference/api/point/shift/en.md
markdown/dev/reference/api/point/shiftoutwards/en.md
markdown/dev/reference/api/point/shifttowards/en.md
markdown/dev/reference/api/utils/stretchtoscale/en.md
markdown/dev/reference/hooks/inserttext/en.md
markdown/dev/reference/settings/margin/en.md
markdown/dev/reference/settings/paperless/en.md

This PR inserts a space character between numbers and SI units ("8 cm" instead of "8cm", for example).
This conforms to the SI and NIST guidelines:
https://www.bipm.org/en/publications/si-brochure
https://www.nist.gov/pml/owm/writing-si-metric-system-units#spacing
I'm writing a style guide that I am following for FreeSewing, and the guideline currently is:
- There should be a space character between numbers and SI units. For example, "5 cm" and "1.3 mm", rather than "5cm" and "1.3mm". (The exception is for CSS and SVG values. Their specifications say that the space character should not be used.)

fix(docs): Insert space between numbers and SI units

---

markdown/dev/guides/markdown/custom-components/en.md

I changed the terminology from "custom components" to "custom tags" since most authors will think of them as markup tags rather than the underlying React components.
I also changed the `<Tip>` examples to be more neutral since `<Comment>` is supposed to be used for tips that are personal opinions.

fix(docs): Update Custom Tags documentation

---

markdown/dev/guides/markdown/frequent-mistakes/en.md

I changed the title from "Frequent Mistakes" to "Avoiding Frequent Mistakes" to avoid confusion. Previously, it appeared that we were saying that the subheading items were mistakes, when they were not. For example: "Frequent Mistakes: Be mindful of whitespace" could be mis-interpreted as "It is a mistake to be mindful of whitespace."

fix(docs): Update Avoiding Frequent Mistakes documentation

---

markdown/dev/tutorials/getting-started-gitpod/en.md
markdown/dev/tutorials/getting-started-linux/dev-setup/en.md
markdown/dev/tutorials/getting-started-linux/en.md
markdown/dev/tutorials/getting-started-linux/installing-node/en.md
markdown/dev/tutorials/getting-started-linux/installing-nvm/en.md
markdown/dev/tutorials/getting-started-linux/node-versions/en.md
markdown/dev/tutorials/getting-started-mac/dev-setup/en.md
markdown/dev/tutorials/getting-started-mac/en.md
markdown/dev/tutorials/getting-started-mac/installing-node/en.md
markdown/dev/tutorials/getting-started-mac/installing-nvm/en.md
markdown/dev/tutorials/getting-started-mac/installing-xcode/en.md
markdown/dev/tutorials/getting-started-mac/node-versions/en.md
markdown/dev/tutorials/getting-started-windows/en.md
markdown/dev/tutorials/pattern-design/adding-measurements/en.md
markdown/dev/tutorials/pattern-design/avoiding-overlap/en.md
markdown/dev/tutorials/pattern-design/completing-our-pattern/en.md
markdown/dev/tutorials/pattern-design/constructing-the-neck-opening/en.md
markdown/dev/tutorials/pattern-design/draft-method/en.md
markdown/dev/tutorials/pattern-design/drawing-the-straps/en.md
markdown/dev/tutorials/pattern-design/en.md
markdown/dev/tutorials/pattern-design/fitting-the-neck-opening/en.md
markdown/dev/tutorials/pattern-design/structure/en.md
markdown/dev/tutorials/pattern-design/testing-your-pattern/en.md

This is the first half of Tutorials documentation updates. It is mostly spellcheck fixes and spelling standardizations (like "Node.js" instead of "Node" or "NodeJS").
I also changed the documentation to tell stand-alone developers to use `yarn` instead of `npm`, since `npm` currently does not work. I added a `<Fixme>` tag to remind us to update this when the `npm` issue is fixed.
(I will have another PR for Tutorials after I review the documentation for content.)

fix(docs): Tutorials updates and corrections

---

packages/core/src/path.mjs
packages/core/tests/path.test.mjs

This PR fixes a bug in `Path.join()` where it produces the below error if any of the paths contains a `noop()` operation.

fix(core): Fix Path.join() to work with noop

---

packages/new-design/templates/shared/package.json.mustache

When `npm` is selected, installation of `@freesewing/new-design@next` fails due to `react-zoom-pan-pinch` and `react-timeago` dependencies requiring React 17 and not working with React 18. 
For the `package.json` installed by the `new-design` package, this PR:
- Bumps engines Node.js to 16 and `npm` to 8.3.0.
- Bumps `react-timeago` dependency to 7.1.0.
- Adds dependency overrides for `react-zoom-pan-pinch` to allow it to work with React 18.
[`react-zoom-pan-pinch`](https://github.com/prc5/react-zoom-pan-pinch) development has stalled, and there is no updated release for React 18. One possible fix/workaround would have been to use the forked [`@pronestor/react-zoom-pan-pinch`](https://www.npmjs.com/package/@pronestor/react-zoom-pan-pinch) package that does work with React 18. However, …

fix(new-design): React 18 dependency updates

---

markdown/dev/reference/api/path/attr/en.md
markdown/dev/reference/api/path/length/en.md

The `Path.attr()` and `Path.length()` API documentation examples didn't actually use the `Path.attr()` or `Path.lengthI()` methods. This PR fixes that.
The new `Path.length()` example:

fix(docs): Change examples to actually use the documented method

---

packages/i18n/src/locales/en/app.yaml

The v3 lab site changed the terminology used from "patterns" to "designs" instead of "patterns". This PR adds the 4 design categories to i18n translations.

fix(i18n): Add design categories

---

packages/core/src/pattern.mjs
sites/shared/components/workbench/logs.js

JavaScript's `Error.prototype.stack` is a non-standard feature, and different browser JavaScript engines produce error stacks of varying content. 
Chrome produces a stack with useful information:
However, Firefox and Safari's stacks are less useful, specifically missing the `TypeError: part.getId is not a function` (the value of the error's `toString()`:
This PR adds the `TypeError: part.getId is not a function` toString() output to the stack if it is not already there. This improves the error when seen in the logs. For example, on Safari:
References:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack

fix(core): Improve error messages for Firefox and Safari browsers

---

sites/dev/pages/404.js
sites/dev/pages/[...mdxslug].js
sites/dev/pages/contact.js
sites/dev/pages/index.js
sites/lab/page-templates/design-list.js
sites/lab/page-templates/workbench.mjs
sites/lab/pages/index.js

This is a partial fix for #3388 , for the dev and lab sites. (A separate PR will be filed for the org site.)
For freesewing.dev, the titles are the page titles with " - FreeSewing.dev" appended. For example: `Getting started with Gitpod - FreeSewing.dev` and `bartackFractionAlong - FreeSewing.dev`. The index page title is `Welcome to FreeSewing.dev`.
For lab.freesewing.dev, the titles for the lab are the capitalized design name or the design category text with " - FreeSewing Lab" appended. For example: `Simon - FreeSewing Lab` and `Block/Sloper Designs - FreeSewing Lab`. The index page title is `Welcome to the FreeSewing Lab`

fix(dev,lab): Add <title> elements to HTML pages

---

markdown/dev/reference/api/utils/curvesintersect/en.md
packages/core/src/utils.mjs

This is a fix in core and an accompanying documentation fix, for `utils.curvesIntersect()`. 
My understanding is that `utils.curvesIntersect()` is intended to return an `Array` of `Points` if more than 1 intersection exists, a `Point` if exactly 1 intersection exists, and `false` if no intersections exist. 
However:
1. The code was returning an `Array` containing a single `Point` under some circumstances.
2. The code comment for the method said that it returned only an `Array`. It didn't mention the other 2 returns.
3. The documentation signature mentioned that the method returned only an `Array` or `false`. It didn't mention the `Point` return.
4. The documentation didn't mention or explain the expected behavior regarding the 3 different return types.
5. The documentation example was …

fix(core): utils.curvesIntersect correctly has 3 different return types, not 2

---

plugins/plugin-cutonfold/src/index.mjs
plugins/plugin-gore/src/index.mjs
plugins/plugin-round/src/index.mjs

resolves #3198, adds an additional prefix to eliminate generic point names in gore and round plugins
resolves #3197 uses prefix as a prefix instead of suffix in cutonfold macro

(fix) Clean up prefixing issues in plugins

---

markdown/dev/reference/plugins/svgattr/en.md
sites/shared/prebuild/md-intro.mjs

Resolves #3419 
Also it turned out that the text of reference links was being tossed, so that's fixed here too

[Feature] Escape inline code while parsing it for og images

---

.prettierignore

I assume that we want `.yaml` files ignored, since `.yml` was already included.

fix(prettier): Ignore .yaml, .gif, .ico, and .jpg files

---

sites/org/components/footer/footer.en.yaml
sites/org/components/footer/footer.nl.yaml
sites/org/components/footer/index.js
sites/org/components/wrappers/layout.js
sites/shared/prebuild/i18n.mjs

This doesn't do much, just replaced the hard-coded translations with the new approach as outlined in #3418 
Oh, and a small fix in the prebuild script

Example of using the new code-adjacent translation approach in a React component

---

config/dependencies.yaml
config/scripts.yaml
sites/dev/package.json
sites/lab/package.json
sites/org/package.json

- dependencies in `dependencies.yaml` match current state of dependencies from `package.json` files
- scripts use `next` directly because we no longer need experimental json modules

(chore): update dependencies and scripts

---

.github/workflows/dependabot-sync.yml
scripts/sync-dependencies.mjs

A very simple action/script to automate the frustrating chore of updating `dependencies.yaml` on each dependabot branch before merging, and prevent the updates from being clobbered if one slips through the cracks.
I've tested the action in my fork and it works when dependabot opens a new PR or rebases an existing one.
I've identified at least one case where it does not work, which is the case where dependabot only changes the `yarn.lock`, because in that case there is nothing to update in the `dependencies.yaml`. Right now I'm letting it fail because, for the pull request it failed on, dependabot had also bumped a top level dependency in the lock file and I figured a red x could warn us that there might still be something to do before the PR can be merged.

(Feature) Add action to sync dependencies bumped by dependabot

---

.github/workflows/dependabot-sync.yml

Because we are tying a bunch of related packages' versions together in `dependencies.yaml`, but each dependabot pull request only updates one package, the sync should make sure that anything that's version is changed in `dependencies.yaml` is also updated in `yarn.lock` and in their various `package.json`s, so we have to run `yarn reconfigure` and `npx lerna bootstrap` to make sure that happens

Dependabot sync action runs reconfigure after syncing updates

---

sites/shared/components/workbench/layout/print/plugin.js

Make the units for the metric scalebox 10cm, so there's a larger area to check for scaling issues with the printer. Imperial is left at 2 inches.

Change scalebox

---

sites/shared/components/workbench/draft/path.mjs

- Bug
When clicking on a path (hover red) in X-ray mode this error would appear and no information would appear.
Upon inspection found that it was not calling the attributes from the path causing the error
- Fix
Changing `bbox` to `prop.path` so the Attributes are called from the Path. After making this change the information is now presented to the user,

fix(lab) Properly call Path attributes for X-ray mode.

---

sites/dev/hooks/useApp.mjs
sites/shared/components/workbench/edit/index.mjs

Fixes for dev and lab Vercel build failures.
dev build failure:
```
12:38:17.596 | ./hooks/useApp.mjs
12:38:17.596 | Module not found: Can't resolve 'site/prebuild/navigation.js'
```
lab build failure:
```
12:35:06.555 | ../shared/components/workbench/edit/index.mjs
12:35:06.556 | Attempted import error: 'shared/components/popout.mjs' does not contain a default export (imported as 'Popout').
```

fix(dev/shared): .mjs filename and named exports changes

---

sites/shared/components/workbench/menu/test-design-options/index.mjs
sites/shared/components/workbench/sample.mjs
sites/shared/utils.mjs

- Menu now works on TestThing view, with the added bonus that menu categories have been re-implemented
- Run a regular draft on first view load so that we don't show an error immediately
- Always show a page title

fix (TestThing) Fix menu and inital draft

---

sites/shared/components/icons.mjs
sites/shared/components/workbench/layout/draft/buttons.mjs

allow IconWrapper component to optionally return an unwrapped version of the icon path for use within svg objects
This resolves #3539 because it means sizing is handled by the buttons component instead of the svg that the icon is wrapped in

fix (#3539) add wrap flag to iconWrapper

---

designs/teagan/src/sleeve.mjs

Teagan had 2 parts labeled as number "2".
Before:
After:

fix(teagan): Renumber sleeve part to 3

---

designs/plugintest/src/plugin-title.mjs

The old boundary box was causing part of the title contents to be hidden.
Before:
After:

fix(plugintest): Adjust title bounding box to prevent clipping

---

scripts/skip-build-base.mjs
sites/lab/skip_build.mjs

Preview builds of lab will also be triggered on changes to designs and plugins now.
I think this is worthwhile for broader testing of designs within the community, and, especially because design changes are slower to be merged, having previews allows designers to direct people to a build that contains those changes

feature (ignored_builds) Add plugins and designs build trigger for lab

---

markdown/dev/reference/api/part/config/hide/en.md

Per the discussion in https://discord.com/channels/698854858052075530/698862765053575188/1076219332037726278 I am changing the docs to correct the description of `hideDependencies`.
I am also adding language to clarify `hideAll`, what it does and how it differs from the combination of `hide` and `hideDependencies`.

fix(docs): Correct hideDependencies and clarify hideAll descriptions

---

sites/shared/components/workbench/layout/print/plugin.mjs

Due to issues with floating point math imprecision, some of the longer half and whole unit interval ticks are missing on the metric ruler:
(The bug does not appear with the 2-inch imperial ruler that we currently use. However, the bug would appear if different inch lengths were to be used.)
This fix uses whole numbers for the intervals and a counter, and the resulting integer math more reliably detects half and whole unit intervals.

fix(workbench): Restore missing whole and half interval ticks on ruler

---

scripts/skip-build-base.mjs
sites/lab/skip_build.mjs

The big one is that now if you have [vercel skip] anywhere in your commit message, vercel will skip the build
the little one is I included changes to core in lab build triggers

Addition Vercel Ignored build refinements

---

sites/shared/components/workbench/layout/print/index.mjs

I believe that the intention was to have the fill set to `none` and that the previous `url(#page)` was simply left over from some previous implementation. It just happened that the failover behavior for the non-existent `#page` URL was setting fill to `none`, and because of this the issue was not noticeable (except on Safari which handles the failover incorrectly).
I'll request reviews from @joostdecock and @eriese who might have knowledge about why we are currently using the `#page` URL. Perhaps its use is intentional. Or, perhaps it actually is a valid, existent URL that I failed to locate.

fix(workbench): Change forPrinting background fill to "none". Fixes #2649

---

config/dependencies.yaml
packages/core/package.json
packages/core/src/pattern-config.mjs
packages/core/src/pattern-draft-queue.mjs
packages/core/src/pattern.mjs
packages/core/src/patternConfig.mjs
packages/core/src/store.mjs
packages/core/tests/pattern-init.test.mjs
packages/core/tests/pattern-other.test.mjs
packages/core/tests/pattern-runtime-parts.test.mjs
packages/core/tests/snap.test.mjs
yarn.lock

In preparation for the cutting layout, I've begun refactoring the way we resolve part configurations because right now we resolve all parts at once and trigger a complete re-initialization if any changes are made. We have adding at *runtime* but not really at *draft time* and for all the parts duplication that will be needed in cutting layout I liked the idea of being able to add a part, have it resolve in-cycle, and put itself onto the end of the draft order.
I ended up separating all config resolution into a separate class while I was at it because `Pattern` is doing too many things and the file is getting unmanageably large
The goals of this pull request:
Current state of the branch should be that all tests pass, so let me know how you feel about the implementation

feature (Pattern Config Resolution) Resolve Part Configurations Progressively

---

designs/simon/src/back.mjs
designs/simon/src/collar.mjs
designs/simon/src/front.mjs
designs/simon/src/yoke.mjs

Used relative positioning to avoid snippets and macros positioned outside parts when scaled to doll sizes. (Also adjusted the positioning of some elements which were okay but could be improved.)
Before and after screenshots of the SVGs:

fix(simon): Improve positioning for snippets and macros using relative points

---

designs/charlie/src/back.mjs
designs/charlie/src/front.mjs

This is the first of a set of two Charlie PRs that addresses Bug #3258. That is the bug where the front and back inseam lengths are different, and similarly the back and front outseams are also different lengths.
This first PR doesn't actually address the problem or change the Charlie pattern. Instead, it just adds helper paths and log messages to assist debugging the issue. With this PR, the different lengths are logged, and users can more easily see what is going on. 
(After the first PR is merged, I will wait a bit before submitting the second PR. That will be the one that actually tries to fix the problem.)

chore(charlie): Add debugging messages for inseam/outseam lengths

---

designs/charlie/src/back.mjs
designs/charlie/src/front.mjs

This is the fix for #3258 for the inseam so now the back and front matches. The change was to use the `fitKnee=true` calculations instead of the incorrect `fitKnee=false`.
The PR contains an incomplete fix for the outseam, and they still do not match back and front. Additional work will need to be done to fully fix the outseam.
I had been waiting for PR #3309 to be merged in order to file this PR. However, that PR seems to be delayed, so I am going ahead and filing this now.

fix(charlie): Fix length of back inseam to match front

---

designs/bruce/src/front.mjs
designs/bruce/src/side.mjs

This PR is the first in a series of pattern fixes to implement the philosophy of "Patterns should not crash with an error. Instead, they should produce a degraded pattern as best they can and print warning messages to the user."
Specifically this Bruce PR:
- Stops the iterative tusk adjustment loop as soon as it detects that the adjustments have stopped producing better results. The goal is to avoid "runaway" rotations that keep making the pattern worse the longer the iterations run.
- Avoids a crash when two circles do not intersect and the bottom left location on the side cannot be determined. Instead, it picks the best-but-arbitrary location for the point and creates it there.
- For each of these situations, a warning message is logged explaining the specific issue.
- For each of these …

fix(bruce): Turn failing patterns into degraded patterns with warning messages

---

markdown/dev/reference/api/part/config/hide/en.md
markdown/dev/reference/api/part/config/name/en.md

From looking at the code, it appears that `linktitle` in regular Markdown pages is nether parsed nor used. Instead, the property simply gets set with the value of `title` later in the process.
This PR removes `linktitle` from the 2 pages that included it, to help avoid confusion.

fix(docs): Remove linktitle Frontmatter keys

---

designs/charlie/src/back.mjs
designs/charlie/src/front.mjs

Two of my PRs added the same code to Charlie (because each PR was written to be independent, unsure of whether the other PR would be merged). The result was duplicate code. 
This PR removes the duplicate code (the old version that calculated the inseam without `fitKnee=true`).

fix(charlie): Remove duplicated code from two merged PRs

---

designs/albert/src/pocket.mjs

Fixing eslint errors flagged/introduced by my PR:
```
/home/runner/work/freesewing/freesewing/designs/albert/src/pocket.mjs
7:5  error  'options' is defined but never used               no-unused-vars
8:5  error  'measurements' is defined but never used          no-unused-vars
22:9  error  'apronLength' is assigned a value but never used  no-unused-vars
✖ 3 problems (3 errors, 0 warnings)
error Command failed with exit code 1.
```

fix(albert): Remove unused variables to pass eslint

---

sites/shared/prebuild/i18n.mjs

`yarn i18n-only` was failing in `new-design` because of the new sidecar implementation. It was looking for files based on a path relative to `cwd` under the assumption that that was a site folder. This change looks for files relative to `sites/shared/prebuild/i18n.mjs`, so that it will always be in the right place

fix (shared/prebuild/i18n) update relative filepath for checking sidecars

---

designs/bella/src/back.mjs
designs/carlita/src/front.mjs
designs/carlita/src/side.mjs
designs/carlton/src/back.mjs
designs/carlton/src/belt.mjs
designs/carlton/src/chestpocketbag.mjs
designs/carlton/src/chestpocketwelt.mjs
designs/carlton/src/collar.mjs
designs/carlton/src/collarstand.mjs
designs/carlton/src/cufffacing.mjs
designs/carlton/src/front.mjs
designs/carlton/src/innerpocketbag.mjs
designs/carlton/src/innerpockettab.mjs
designs/carlton/src/innerpocketwelt.mjs
designs/carlton/src/pocket.mjs
designs/carlton/src/pocketflap.mjs
designs/carlton/src/pocketlining.mjs
designs/carlton/src/tail.mjs
designs/carlton/src/topsleeve.mjs
designs/carlton/src/undersleeve.mjs
markdown/dev/howtos/design/cutlist/en.md
markdown/dev/reference/api/part/draft/en.md
markdown/dev/reference/api/store/extend/en.md
markdown/dev/reference/plugins/cutlist/en.md
packages/core/src/part.mjs
packages/core/src/pattern.mjs
packages/core/tests/store.test.mjs
plugins/plugin-cutlist/src/index.mjs
plugins/plugin-cutonfold/src/index.mjs
plugins/plugin-grainline/src/index.mjs

Destructuring methods added by plugins into the draft method was seeming a little magical. Accessing those methods via the store, and namespacing those methods by the plugin that brought them will hopefully help demystify where those methods came from

chore (store plugin methods) Change method access to via store only

---

plugins/plugin-cutlist/src/index.mjs
plugins/plugin-title/src/index.mjs
sites/shared/components/workbench/layout/cut/plugin-cut-layout.mjs

1. Corrects the updated cutlist method names to fix the pattern crashes.
> TypeError: Cannot read properties of undefined (reading 'addCut')
2. Prevents these warning messages:
> Store.get(key) on key cutlist,carlton.front,materials,fabric, which is undefined
> Store.get(key) on key cutlist,bent.underSleeve, which is undefined
3. Corrects grainline rotation in the cutting layout. The fix is to allow rotation in both directions, clockwise and counter-clockwise, instead of always rotating in one direction.
Before and after:

fix(plugin-cutlist, plugin-test, workbench): Cutting layout-related fixes

---

markdown/dev/reference/macros/title/en.md

(Unfortunately, this typo was causing part of the page to be interpreted, resulting in a runtime error.)

fix(docs): Typo missing quote in title macro docs

---

markdown/dev/howtos/ways-to-contribute/proofreading/en.md
markdown/dev/tutorials/pattern-design/completing-the-neck-opening/en.md
markdown/dev/tutorials/pattern-design/constructing-the-neck-opening/en.md
markdown/dev/tutorials/pattern-design/draft-method/en.md

The example for "without destructuring" was the destructured way it's done in the tutorial, the example for "with destructuring" was the old way to pass in a props object without destructuring. I switched the two so that the "without destructuring" example is of a function without destructuring and the "with destructuring" example is of the preferred destructured function.

Pattern design tutorial proofreading

---

markdown/dev/reference/api/path/intersects/en.md
markdown/dev/reference/api/path/intersectsx/en.md
markdown/dev/reference/api/path/intersectsy/en.md
markdown/dev/reference/api/utils/curveintersectsx/en.md
markdown/dev/reference/api/utils/curveintersectsy/en.md
markdown/dev/reference/api/utils/curvesintersect/en.md
markdown/dev/reference/api/utils/lineintersectscurve/en.md

To address the situation that Bug #3367 will not be fixed, this PR adds warnings to the documentation for the problem methods/functions.

fix(docs): Add warning to curve intersection methods and functions

---

sites/shared/components/wrappers/workbench.mjs

fix(workbench): renderProps in xray caused error as 'draft' was not part of props

---

sites/shared/components/workbench/draft/path.mjs

Problem:
Noticed that the Name catergory in the info box was empty for paths.
Example:
Solution:
Change `bbox.name` to `props.pathName`
Fixed:
This works with inherted paths as well.

fix(sites) Missing Path Name Info

---

markdown/org/docs/patterns/sandy/cutting/en.md
markdown/org/docs/patterns/sandy/fabric/en.md
markdown/org/docs/patterns/sandy/instructions/en.md
markdown/org/docs/patterns/sandy/options/seamlessfullcircle/en.md

For #2615
I had a noticed a while back that my initial Doc work on Sandy needed some more refinement. It was a bit confusing and the waistband cutting info was incorrect.
Upon further inspection I decided it was best to completely overhaul the instructions to streamline them as having two separate instructions were confusing and could be merged together.

Sandy Documentation Overhaul

---

markdown/org/docs/patterns/sandy/instructions/en.md

- Stray `<Note>` opening tag with no end tag.
- Also cleaned some trailing whitespace.

fix(docs): (sandy) Remove stray <Note> opening tag

---

markdown/org/docs/patterns/charlie/options/crossseamcurveangle/en.md
markdown/org/docs/patterns/charlie/options/crotchseamcurveangle/en.md
markdown/org/docs/patterns/paco/options/crossseamcurveangle/en.md
markdown/org/docs/patterns/paco/options/crotchseamcurveangle/en.md
markdown/org/docs/patterns/titan/options/crossseamcurveangle/en.md
markdown/org/docs/patterns/titan/options/crotchseamcurveangle/en.md

One of the outstanding on #1342
Was initially going to just do Titan's but thought best to check Paco's and Charlie's. Found some info on Charlies but decided to add a little more info
Added
- Titan options,crossSeamCurveAngle info
- Titan options,crotchSeamCurveAngle info
- Paco options,crossSeamCurveAngle info
- Paco options,crotchSeamCurveAngle info
Updates
- Charlie options,crossSeamCurveAngle info
- Charlie options,crotchSeamCurveAngle info
If the extra info is not accurate I can remove it

Add Missing Cross/Crotch Seam Curve Angle Option Info

---

packages/core/src/part.mjs

This is an (untested) fix for #3781
It ensures a part's freeId is inherited when the part is injected.

fix(core): Proposal to fix #3781

---

config/dependencies.yaml
markdown/dev/guides/markdown/code-blocks/en.md
markdown/dev/guides/markdown/custom-components/en.md
sites/shared/components/mdx/highlight.mjs
sites/shared/components/mdx/mermaid.mjs
sites/shared/mdx/loader.mjs
sites/shared/package.json
yarn.lock

At the request of @marpants this adds support for mermaid diagrams to our shared MDX pipeline. Diagrams can be created by using a fenced code block using the `mermaid` language.
I did not verify to what extend this bloats the bundle. Perhaps that's something we need to look into later and consider the trade-off. For now, my main concern is to keep a new contributor happy, so here it goes :)

feat(shared): Add Mermaid support to MDX pipeline

---

config/templates/plugin/package.json.mustache
config/templates/plugin/src/index.mjs.mustache
scripts/add-software.mjs

Initially `yarn new plugin` would not create a new plugin.
This pull request adds the functionaly for creating a new plugin
Example of prompt:
Examples of validatePluginName:
Example of createPlugin:
Example of generated `index.mjs` file:
Example of generated `package.mjs` file:
Additions:
- added prompt to yarn new design in `add-software.mjs`
- added validatePluginName() in `add-software.mjs`
- added createPlugin() in `add-software.mjs`
- added orderPlugin() in `add-software.mjs`
- create `config/templates/plugin` folder
- create `index.mjs.mustache` to `templates/plugin/src`
- create `packages.json.mustache` to `templates/plugin`
Changes:
- validateName has been changed to validateDesignName in `add-software.mjs`
Please don't hesitate to suggest changes on the prompt message or the …

Add functionality for yarn new plugin

---

.github/workflows/playwright.yml
.gitignore
config/dependencies.yaml
config/scripts.yaml
nx.json
package.json
sites/dev/package.json
sites/lab/e2e/lab.spec.js
sites/lab/package.json
sites/lab/playwright.config.mjs
sites/org/package.json
sites/shared/config/playwright.mjs
yarn.lock

This PR lays the foundation for adding [playwright](https://playwright.dev/docs/intro) tests to our front end:

Feature (tests) Get E2E testing set up

---

config/scripts.yaml
sites/org/package.json

`yarn cleanall` currently deletes needed pages from `sites/org`, requiring developers to run `git restore` afterwards to recover them. This PR fixes the issue by removing the `clean` script from `sites/org/package.json`. 
I note that the `sites/dev/package.json` does not contain a `clean` script, but `sites/lab/package.json` does. I think the root cause might be that the org `package.json` file was copied from lab.
Previously discussed:
https://discord.com/channels/698854858052075530/944926520282054666/1074943455329013822
discord://discord.com/channels/698854858052075530/944926520282054666/1074943455329013822
```sh
% yarn cleanall
yarn run v1.22.19
$ lerna run clean
lerna notice cli v6.6.1
...
% git status
On branch develop
Your branch is up to date with 'origin/develop'.
Changes not …
```

fix(dev,org): Add/change clean script

---

designs/sandy/src/skirt.mjs

There was a behavior in Sandy where if a 100% circle is used and seam allowance is enabled, the skirt pattern is not the expected half-circle. Instead, the skirt falls short of a half-circle. This PR fixes this so 100% circle skirts have an exact half-circle pattern and there is no seam allowance along that 2nd edge (because it is on the fold).
Before the fix:
After the fix:
This has a side effect that the pattern jumps between 99.9% and 100.0%:
At 99.9%:
At 100.0%:

fix(sandy): Correct 100% full circle angle and seam allowance

---

sites/shared/components/wrappers/workbench.mjs

In the browser Javascript console I see messages that indicate that the lab is drafting patterns without measurements. This happens in certain circumstances, like when the ClearThing button is used or when visiting the Logs view immediately after browsing to a new design.
For example, if I go to Carlton and use the ClearThing button I see messages like `Warning: The round macro only handles 90 degree angles correctly.` and `Called part.setCutOnFold() but at least one parameter is not a Point instance`. And also things like, `Unable to draft part 'bent.sleeve' (set 0) TypeError: Cannot read properties of undefined (reading 'x')`.

fix(workbench): Do not pre-draft patterns without measurements

---

designs/holmes/src/ear.mjs
designs/jaeger/src/options.mjs
designs/simon/src/options.mjs
designs/simone/src/fba-front.mjs
designs/yuri/src/back.mjs
designs/yuri/src/front.mjs

I checked both localhost lab and lab.freesewing.dev to verify that they have the same design options after this PR is applied.
(The only exception is Simon/Simone's Collar Ease option which will be addressed in a separate PR.)

fix(various designs): Restore design options omitted during v3 port. Fixes #3004.

---

.eslintignore
.github/workflows/lint.all.yml
.github/workflows/lint.diff.yml
.github/workflows/playwright.yml
.github/workflows/tests.all.yml

While working on the workflow for testing new-design I learned that simply caching the root `node_modules` means that some dependencies might get missed if they are not hoisted because they are not shared. So this PR now brings all workflows that use caching in line with the strategy of caching all `node_modules` folders
it also adds mustache files to the lint ignore in hopes of streamlining linting, but I'm not sure that'll help with lint.diff

chore (workflows) enforce consistent caching across workflows

---

designs/bella/src/back.mjs
designs/bella/src/front-side-dart.mjs
designs/bent/src/topsleeve.mjs
designs/bent/src/undersleeve.mjs
designs/breanna/src/back.mjs
designs/breanna/src/front.mjs
designs/breanna/src/sleeve.mjs
designs/brian/src/back.mjs
designs/brian/src/front.mjs
designs/brian/src/sleeve.mjs
designs/noble/src/backinside.mjs
designs/noble/src/backoutside.mjs
designs/noble/src/frontinside.mjs
designs/noble/src/frontoutside.mjs
designs/titan/src/back.mjs
designs/titan/src/front.mjs

PR to add cutlist info to the block/sloper designs. It is important to do this first, before adding cutlists to other designs that inherit from them.
- I chose to add a minimal amount of `addCut()`s, only adding code where needed to produce the correct cutting layout. (The alternative I considered was adding explicit cutlist code to every part, even when not required, in the name of potential clarity.)
- Some parts have a `removeCut()` that was needed to clear an inherited cutlist. I elected to not add a comment explaining these situations.
- I also considered adding an explicit `removeCut()` to every inheriting part regardless of whether it was needed, but I chose not to do so.
- I added a missing `cutonfoldAndGrainline` to Breanna's front. The foldline and grainline are mentioned in the …

Add cutlists to blocks/slopers

---

packages/core/src/pattern/pattern-drafter.mjs

PDF exports were missing page markup because it get drafted in the `postLayout` hook, at which point stacks are already generated with parts added to them. After the recent refactor I must have changed the order or operations somewhat, so now when `Pattern.draftPartForSet` creates a new `Part` out of cycle, it never gets added to the correct stack, so it is not included in SVG renders. This PR makes it so that `Pattern.draftPartForSet` check to see if there is an existing part and calls `draft` on it instead, which will mean that the part that was put in the stack is the one that's used.
I don't foresee side effects in a rare instance where a part is double drafted (which would only happen if someone was doing something very advanced in a plugin) because existing points and paths will be …

fixes #3957 Re-use existing part for out-of-cycle draft

---

packages/new-design/lib/config.mjs

Right now, `npx @freesewing/new-design@next` will download the latest *published* packages, but will also download `lab` and `shared` files directly from the `develop` branch, which can lead to the build errors when the next tag is stale.
This PR makes it so that `npx @freesewing/new-design@next` downloads those files from the github tag of the same name as the published package version, enforcing consistency. 
I notice that while the tag is created in `postrelease` we are not consistently pushing the tag every time we publish a version, so this will want us to make sure that we are doing that.

fix (new-design) peg new-design downloads to the current tag

---

packages/core/src/part.mjs

(This will help in situations such as the pattern coder accidentally using `sewtogether` as the macro name, rather than the correct `sewTogether`.)

fix(core): (part) Add warning message if invalid macro name used

---

designs/benjamin/src/bow1.mjs
designs/benjamin/src/bow2.mjs
designs/benjamin/src/bow3.mjs
designs/benjamin/src/ribbon.mjs
markdown/org/docs/patterns/benjamin/cutting/en.md
markdown/org/docs/patterns/benjamin/instructions/en.md

- Change part names for consistency and improvement, to make the pattern, cutting instructions, and construction instructions consistent in the names they use ("Bow", "Short Bow", "Medium Bow", "Long Bow, and "Collar Band").
- Improve and clarify instructions.
- Fix cutlist instructions (2 Medium Bow/Knot 2 and only 1 Long Bow/Knot 3).

fix(benjamin): Part name changes, instructions, and cutlist

---

plugins/plugin-annotations/src/title.mjs

The `title` macro is displaying warning messages For designs with no set cutlist or ones that set the cutlist after `title` macro. For example, for Waralee (which has not yet had cutlist info added):

fix(plugin-annotation,title): Supress warning message if cutlist not defined

---

sites/shared/components/workbench/inputs/measurement.mjs
sites/shared/components/workbench/measurements/index.mjs

Fixes #3973.
I don't know if this is an appropriate way or the best way to fix the issue. This PR adds an `optional` parameter allows zero values if optional. (From testing I observed that the value is set to zero when the field is blanked out.)

fix(workbench): Allow blank optional measurements

---

markdown/dev/tutorials/getting-started-linux/dev-setup/en.md
markdown/dev/tutorials/getting-started-linux/dev-start/en.md
markdown/dev/tutorials/getting-started-mac/dev-setup/en.md
markdown/dev/tutorials/getting-started-mac/dev-start/en.md
markdown/dev/tutorials/getting-started-mac/installing-nvm/en.md
markdown/dev/tutorials/getting-started-windows/en.md
markdown/dev/tutorials/pattern-design/structure/en.md

Continuing work for #3024.
I made an editorial change to nudge users towards using `yarn` rather than `npm` as the recommended option.

fix(docs): Tutorials doc review corrections and updates

---

markdown/dev/reference/api/pattern/sample/en.md
markdown/dev/reference/settings/sample/en.md

(The `sample` setting was previously undocumented in the reference Settings section.)

chore(docs): Move sample setting docs from Pattern.sample() to its own doc

---

designs/bob/src/bib.mjs
designs/penelope/src/back.mjs
designs/penelope/src/front.mjs
designs/penelope/src/shape.mjs
markdown/dev/reference/api/part/config/measurements/en.md
markdown/dev/reference/settings/measurements/en.md

fix(bob,penelope,docs): Access optional measurements via `measurements`

---

markdown/dev/reference/macros/bannerbox/en.md
plugins/plugin-annotations/src/bannerbox.mjs

The `bannerbox` macro was calling the `banner` macro with hardcoded `repeat` and `dy` values. The PR fixes this, using the values passed to the macro.
The default `repeat` value was changed to `99` to reflect the actual hardcoded value that was previously used.
Documentation was updated with the changes. 
I also added additional documentation: 
- The bannerbox is larger than the provided box.
- Information about the offset used to make the bigger box (since during testing I was confused why changing margins seemed to increase offsets by a greater amount than expected). 
- Information about what happens if there is not enough or too much text.

fix(bannerbox): Removed hardcoded values in call to `banner`

---

designs/brian/src/back.mjs

This PR adds an explicit cutlist to Brian's Back (and by inheritance, Brian's Front) parts.
My previous PR #3908 to add cutlists to Brian was incomplete. My policy then was to add an explicit cutlist only if it was necessary to "produce the correct cutlist in the cutting layout". So, if a part's cutting layout was already correct due to the no-explicit-cutlist default behavior (like Brian's Back and Front parts), I didn't add the cutlist.
However, the explicit cutlist is required to add the cutting instructions to titles. Brian's Back and Front parts were missing these. (And, by inheritance Bent's parts were also missing these. And, the issue would have affected any other design inheriting from Brian.) So, this PR now adds the missing cutlists.
Before and After (titles now have cutting …

fix(brian): Add explicit cutlist for back and (inherited) front parts

---

packages/core/src/pattern/pattern-config.mjs
packages/core/tests/fixtures/part.mjs
packages/core/tests/pattern-init.test.mjs

Resolves #4049 brings draft order in line with expectations, adds tests to specifically check correct draft order resolution

fix (core) draft after dependencies before from dependencies

---

markdown/dev/reference/settings/scale/en.md

Closes #3873.
This PR describes the expected, correct behaviors for `scale`. However, some of the actual, current behaviors might not be correct (scale isn't working properly yet for some elements). Not-yet-merged PR #3999 should fix this.

DRAFT: fix(docs): (scale) Add more details about effects

---

designs/albert/src/front.mjs
designs/albert/src/strap.mjs
designs/bob/src/bib.mjs
designs/florence/src/mask.mjs
designs/florent/src/brimbottom.mjs
designs/florent/src/briminterfacing.mjs
designs/florent/src/brimtop.mjs
designs/florent/src/side.mjs
designs/florent/src/top.mjs
designs/holmes/src/ear.mjs
designs/holmes/src/gore.mjs
designs/holmes/src/visor.mjs
designs/hortensia/src/bottompanel.mjs
designs/hortensia/src/frontpanel.mjs
designs/hortensia/src/sidepanel.mjs
designs/hortensia/src/sidepanelreinforcement.mjs
designs/hortensia/src/strap.mjs
designs/hortensia/src/zipperpanel.mjs
designs/lucy/src/pocket.mjs
designs/octoplushy/src/eye.mjs
designs/trayvon/src/fabric.mjs
designs/trayvon/src/interfacing.mjs
designs/trayvon/src/lining.mjs
designs/trayvon/src/loop.mjs

This PR adds cutlist info to our Accessory designs, with the exceptions of:
- Hi (covered under PR #3924)
- Octoplushy (covered under PR #4098)
- Magde (no cutlist info available yet, pattern designer asked on Discord for info)
This PR also moves `cutonfold` and `grainline` macros out of `complete` blocks.
It does not add any titles to parts that don't already have them.

chore(accessory designs): Add cutlist

---

designs/bella/src/back.mjs

This PR prevents negative width back darts by setting the width to 0 in those situations. An `info` message is also logged: `Back dart is not necessary (width is 0.0 mm/inches).`
Before:
After:

fix(bella): Prevent negative width back dart

---

markdown/dev/reference/packages/en.md
markdown/dev/reference/packages/i18n/en.md
markdown/dev/reference/packages/models/en.md
markdown/dev/reference/packages/new-design/en.md
markdown/dev/reference/packages/prettier-config/en.md
markdown/dev/reference/packages/rehype-highlight-lines/en.md
markdown/dev/reference/packages/rehype-jargon/en.md
markdown/dev/reference/packages/snapseries/en.md

A first pass at adding documentation for packages.
- I put the documenation files in `/reference`.
- I realize that `models` may be changing soon, and the documentation will need to be updated. However, I chose to document the package as it exists today.
- I had to guess at how some things worked and what the Usage sections should look like. 
- Similarly, I just copied and pasted the same Installation sections.
This PR closes #3214

chore(docs): Add documentation for packages

---

sites/shared/components/workbench/edit/gist-validator.mjs

The "Edit YAML" function was giving a MissingMeasurements warning message when saving edited YAML for Bob which has no required measurements.

fix(workbench): Accept measurement-less edited YAML for designs with no required measurements

---

packages/new-design/lib/utils.mjs

Fixes #4290
Prepends `file://` schema during the import of template data to support windows paths.
Testing:  
1.  Check out branch and navigate to root directory
2. Run:  `node packages/new-design/index.mjs` 
3. Follow prompts and answer questions
4. After completion - verify that a new directory has been created with templated files.
FAILIF:  ERR_UNSUPPORTED_ESM_URL_SCHEME is thrown
Note:  This should be tested on *nix system for regression, and a windows system to verify the fix works.

fix(new-design): Import using absolute identifier

---

sites/shared/components/workbench/index.mjs
sites/shared/hooks/use-pattern-settings.mjs

This moves patterns settings from React state to the URL, which has some great advantages:
- It's page-reload proof
- Don't like a change you just made? Just use the back button of your browser to revert to the previous state
- This makes it trivial to update measurements in state, without changing them permanently
- This also allows us to pre-generate a URL that will display a pattern in a particular state
We could make this a little neater by filtering the measurements so that only the ones used by the design are included, as that will keep the URLs a lot shorter.
One potential concern is that this *leaks* measurement data in the URL. Which is perhaps fine because browser history is private, but it's worth pointing it out anyway.

feat(shared): Keep pattern settings in URL

---

designs/aaron/src/front.mjs
designs/bee/src/cup.mjs
designs/carlton/src/front.mjs
designs/simone/src/fba-front.mjs
packages/core/src/part.mjs
packages/models/tests/models.test.mjs
tests/designs/config.mjs

While working on the new front end I discovered that a few designs didn't actually include all necessary measurements in their configs, which meant that sets that didn't have all the needed measurements could in some cases be used, which obviously caused errors.
This PR adds the measurements to the correct parts and implements a test to catch this issue in the future

fix (designs) add missing measurements to design configs

---

markdown/org/docs/measurements/waisttohips/en.md

Removed the "where your trousers sit" wording because it is confusing to customers. Also, the hips circumference measurement instructions don't mention trousers.
> To me, "the top of your hip bone" and "where your trousers sit" are two completely different points, with the latter being entirely dependant on your style choices.
https://discord.com/channels/698854858052075530/757632180980547686/1111570194528219146
discord://discord.com/channels/698854858052075530/757632180980547686/1111570194528219146
(The customer mentioned that there was a discrepancy on the v2 org website between the With Breasts and Without Breasts images regarding where the hips were located. However, this PR does not address that issue, and I'm not sure if the problem will still exist in v3. If the issue is seen in …

fix(docs): (waistToHips) Removed ambiguous trousers reference

---

sites/shared/components/sets/set-picker.mjs
sites/shared/hooks/use-backend.mjs

It seems I introduced this loop in 4d8052d by removing the empty dependency array for the hook that gets the sets in `UserSetPicker`. Adding `backend` to the dependency array didn't fix the issue because `backend` was being re-instantiated on every call to `useBackend`, so I made a `Backend` class and am memoizing the instance based on the token.

fix (Workbench) remove infinite loop in measies view

---

markdown/dev/reference/settings/layout/en.md

After troubleshooting on discord we found a solution to own object layout in v3. It renamed parts to stacks in this object and some other pieces seem to require width and height so I added them to the example too.

Parts renamed to stacks in layout reference docs

---

designs/bee/src/cup.mjs

Have started to work in v3 and noticed that Bee had lost the changes it made to Bella's options when it was ported.
This PR simply restores the changes Bee makes.
Changes:
- Bella options that are constant Bee have been restored
- Bella options that sit in a differenet catergory for Bee have now been moved back to locations.
Note: If there is an easier way to just change the catergory rather than having to rewrite out the option please let me know and I will update the PR.

fix(Bee) Options changes restored.

---

config/dependencies.yaml
sites/dev/package.json
sites/lab/package.json
sites/org/package.json
sites/org/pages/blog/[dir].mjs
sites/org/pages/showcase/[dir].mjs
sites/shared/package.json
yarn.lock

These pages used `slug` in two different meanings, so I got rid of that footgun.

fix(org): Avoid confusing about what slug means

---

.gitpod.yml

updates gitpod config to lts/hydrogen
also changes the script it runs on start to `yarn tips` because `yarn kickstart` isn't necessary every time you re-open a workspace

fix (gitpod) update to lts/hydrogen

---

.gitpod.yml

Can't run `yarn tips` without running `yarn install`, so may as well just run `yarn kickstart` on creation

fix (gitpod) better install command

---

designs/bee/src/cup.mjs

Problem
- bella.frontSideDart was still visible when drafting Bee
Solution
- Add `from: true` to `hide {}`
Simply was missed during port and option update.

fix(bee) Hiding inherited Bella frontSideDart part

---

sites/backend/prisma/schema.prisma
sites/backend/src/middleware.mjs
sites/backend/src/models/user.mjs

After realizing (late) that there was a bug in how we track user activity in the v2 backend (see #4698) I said I would:
- Add a `lastSeen` field to the database to be less ambiguous
- Ensure this `lastSeen` field is updated each time a user checks in
This PR implements that by extending the Express middleware to:
- Update the `lastSeen` record of the authenticated user (both when using JWT and API Keys authentication)
- Increment the `jwtCals` or `keyCalls` field based on whether JWT or KEY authentication is used
I've also dropped the `lastSignIn` record in favor of `lastSeen` as it is less ambiguous.
The different *calls* fields (`jwtCalls` and `keyCalls`) will keep a tally of the amount of backend API calls made by a user.

feat(backend): Track lastSeen and jwtCalls/keyCalls in middleware

---

packages/new-design/shared/lab/components/header.mjs
packages/new-design/shared/lab/components/layouts/lab.mjs
sites/lab/components/layouts/lab.mjs

On the current develop branch, trying to run the lab results in the following error:
```
- error ./components/layouts/lab.mjs:1:0
Module not found: Can't resolve 'shared/components/theme-picker/index.mjs'
> 1 | import { ThemePicker } from 'shared/components/theme-picker/index.mjs'
2 | import { LocalePicker } from 'shared/components/locale-picker/index.mjs'
```
Because those two modules have been moved and renamed. So here's a fix that points those imports to the right place, in every file I found that referenced them

Fix import errors for ModalThemePicker and ModalLocalePicker

---

markdown/org/docs/site/apikeys/level/en.md

Seemingly using `Link` breaks things, so let's use `Tip` instead.

chore(markdown): Attempt to side-step crowdin issues

---

markdown/dev/reference/api/part/config/measurements/en.md
markdown/dev/reference/api/part/draft/en.md

This PR addresses the concerns in #3974, suggesting that information about optional measurements did not belong in the Part config documentation and instead should be moved to Part draft documentation.

fix(docs): Move optional measurements info from Part config to Part draft

---

CONTRIBUTING.md

Fixes #5205 
Replaces dead links in the [CONTRIBUTING.md](https://github.com/freesewing/freesewing/blob/develop/CONTRIBUTING.md#:~:text=When%20you%20engage,of%20Conduct.) with supposed proper replacements. 
Would need cross-verification of the replacements.

fix(CONTRIBUTING.md)

---

designs/onyx/src/base.mjs
designs/onyx/src/raglansleeve.mjs

Changes how ease around the armhole is calculated by having the armpit point move downwards for positive eases.
Current: Sleeve ease is applied entirely to the top of the shoulder.
New: Sleeve ease is applied equally to the top of the shoulder and to the armpit when sleeveEase is positive, but still applied only to the shoulder top for negative ease.
The reasoning is that, while you don't want to squeeze the armpit with negative ease, you do want extra room to be distributed evenly for roomier garments.
This should improve the quality of patterns generated with positive ease.

Onyx - Tweak to armhole ease

---

designs/shelly/i18n/en.json
designs/shelly/src/back.mjs
designs/shelly/src/base.mjs
designs/shelly/src/front.mjs
designs/shelly/src/neckband.mjs
designs/shelly/src/raglansleeve.mjs

Changes how the armpit is calculated on the body so that it moves down as sleeveEase grows. In other words, the sleeve now gains ease equally on the shoulder and the armpit, instead of entirely on the shoulder.
Cleans up Shelly's code as follows:
- replaces .hide(true) with .hide()
- replaces .attr('class', ...) with .addClass(...)
- removes redundant measurement declarations
- removes empty plugins[] declarations
- removes unneeded if(paperless) checks
- removes unneeded if(complete) checks
- SA now works without needed complete to be set to true
- fixed a bug causing the fold line on the neckband to not render.

Shelly 3 - Code cleanup

---

markdown/dev/reference/api/utils/applytransformtopoint/en.md
markdown/dev/reference/api/utils/combinetransforms/en.md

Closes  #4078
Documented two new methods `utils.applyTransformToPoint()` and `utils.combineTransforms` in the Utils section of API references doc.

Added documentation of two new methods in the utils section of API.

---

sites/dev/pages/index.mjs
sites/org/pages/index.mjs
sites/org/pages/support.mjs
sites/shared/components/social/mastodon-verification.mjs
sites/shared/components/workbench/exporting/export-handler.mjs

When generating a fully default design that does not require any measurements, the export failed because where we expect a settings object, we get `false` instead. This guards against this scenario by instantiating an empty object in this case.
Fixes #5430

fix(shared): Guard against exporting without settings

---

sites/shared/components/account/github.mjs

While doing the workaround steps in #5433, I was exploring the settings and noticed that these placeholders were the wrong way around. This is a quick fix for that 😝

fix(sites): swap github email and name placeholders

---

config/changelog.yaml
packages/core/src/pattern/pattern-plugins.mjs
sites/shared/components/workbench/views/draft/header.mjs

The parameters passed to the conditional load method were incorrect causing a conditional plugin to never get loaded.

fix(core): Corectly load conditional plugins

---

sites/backend/src/models/user.mjs

We need to allow login without consent, because people need to be logged in to give consent.
This is typically handled at the sign-in page, but when people navigate away, or for some other reason need to bootstrap an account without consent, this is required.
The same happens when logging in with username/password or magic link, but there we already accommodate for this use case.
However, for Oauth, this was overlooked, so this commit adds it.
To be complete: This allows login while both consent is lacking, and status is not active because that's the state the account is in at that point.

fix(backend): Allow Oauth login without consent. Fixes #5433"

---

plugins/plugin-annotations/i18n/en.json

Just a simple typo fix for the cut instructions plugin.

Typo fix in plugin-annotations en.json (mirorred -> mirrored)

---

markdown/dev/reference/api/path/setclass/en.md

In the example for setClass, addClass is used. This fix changes it to setClass.

(Documentation) Fix error in the example for /reference/api/path/setclass

---

sites/org/page-templates/edit-pattern.mjs
sites/shared/components/workbench/new.mjs
sites/shared/components/workbench/views/draft/header.mjs

This reverts the temporary fix for #5534
(commit 99b6e75956883ef57b08a5a87cb4e7be2c7e9075 ) and implements a proper fix.
This also closes #5570 as that was a side-effect of the initial half-assed fix.

fix(shared): Saving pattern in edit mode

---

markdown/org/docs/about/site/draft/en.md

This PR fixes several typo's in https://freesewing.org/docs/about/site/draft.

Typo fixes in documentation

---

sites/shared/components/account/patterns.mjs

Adds a grey/disabled delete button to `account/patterns` when no patterns are selected. Motivated by multiple users (me included) at least initially glossing over the fact that this is how pattern deletion is done.

Add disabled pattern delete button when no patterns selected

---

config/changelog.yaml
markdown/dev/howtos/code/adding-text/en.md
markdown/dev/reference/macros/en.md
markdown/dev/reference/macros/title/en.md
packages/react-components/src/pattern/utils.mjs
plugins/plugin-annotations/src/title.mjs
plugins/plugin-annotations/tests/title.test.mjs
plugins/plugin-i18n/src/index.mjs
sites/shared/components/tabs.mjs
sites/shared/styles/globals.css

This started out as a fix for #5753 after I felt the approach in #5760 was not the best way to handle this.
The problem lies in the way the cutlist data is added to the pattern by the title plugin. The whole cutlist thing was added by a less experienced contributor, and they were a little too focussed on what they were trying to accomplish, rather than keeping an eye on the big picture.
In this case, a bunch of points get added to the part to anchor all of the text for the cutlist. This causes problems when inheriting parts because points are added per material, and now we don't know what materials were used and how to remove these points.
I appreciate @woutervdub effort to resolve this in #5760 but as I mentioned above, I don't love the approach.
Rather than finding a clever way to …

feat: Support notes in title macro

---

markdown/dev/tutorials/getting-started-linux/dev-setup/en.md

I've been aware of this issue for a while but previously believed that it likely wouldn't affect anyone. However, it turned out that a FreeSewing customer did encounter this issue, and it caused problems for them, as reported on Discord:
> it was unclear to me, that "yarn" meant the npm package yarn, and not the command testing utility "yarn" in linux. 
> much confusion ensued.
https://discord.com/channels/698854858052075530/1190514590061179010/1190514590061179010
discord://discord.com/channels/698854858052075530/1190514590061179010/1190514590061179010

fix(markdown): Add yarn disambiguation to Linux tutorial

---

markdown/dev/tutorials/getting-started-vercel/en.md

1. Removed mentions of lab.freesewing.dev/`sites/lab`.
2. Updated estimated build times.
3. Added "Disabling automatic deployments" section.
4. Fixed various typos and wording.

fix(markdown): Update Vercel tutorial for v3

---

sites/shared/components/workbench/views/flags.mjs

fix(shared): Flags should not display null notes

---

markdown/dev/reference/macros/cutonfold/en.md

fix(markdown): Fix property type in cutOnFold macro docs

---

packages/core/src/pattern/pattern-config.mjs

In the 2022-11-12 Contributor Call, we agreed to remove the options distance debug logging code once v3 was released. This PR performs that chore and closes #3062.
Options distance information is still logged, but instead of individual messages for each part, things are now logged as a concise summary.
After:
Before:

chore(core): Remove options distance debug logging

---

markdown/org/docs/designs/carlita/instructions/en.md
markdown/org/docs/designs/hugo/instructions/en.md
markdown/org/docs/designs/jaeger/instructions/en.md

Making sure that incomplete documentation is marked with `<Fixme>` tags (rather than `<Note>` or `<Warning>`) to make it easier to find and to help prevent it from from being overlooked.

fix(carlita,hugo,jaeger): Add Fixme tags to incomplete documentation

---

markdown/dev/reference/api/part/config/options/en.md
markdown/dev/reference/api/part/config/options/extend/en.md

I took a guess as to what the Extending Options documentation was supposed to cover.

fix(markdown): Add more info to Extending Options part doc

---

markdown/org/docs/designs/bob/instructions/en.md

I started working to fix this Fixme by adding bias tape sewing instructions, but then I came to the belief that it isn't needed. The Bob bib is part of a pattern tutorial, not a sewing tutorial. We don't teach other sewing techniques like how to sew a snap or buttonhole, so similarly we don't need to teach how to sew bias tape.

fix(bob): In docs, remove bias tape Fixme

---

markdown/org/docs/designs/gozer/en.md
markdown/org/docs/designs/gozer/notes/en.md

I added a `<DesignInfo>` to Gozer's main doc page. Otherwise, there is no specification info about the design and no links to the instructions, etc., except in the navigation menu.
The `<br />` is to add vertical whitespace. Otherwise the `#FreeSewingGozer` starts immediately after the `Wouter`, making them run together. It didn't look right.
I intentionally chose to use `<br />` rather than a trailing `\` or two space characters to add the vertical whitespace because I think it makes the Markdown file easier to read and edit. Otherwise, it could look as if a blank line with two space characters had been added to the file by mistake.
(The empty element in the `Documentation` list is because Gozer has no design options. I've addressed this `<DesignInfo>` custom tag issue in PR #5944.) …

fix(gozer): In docs, add <DesignInfo> and change <Fixme> to <Warning>

---

sites/shared/components/designs/info.mjs

This issue was exposed while testing `<DesignInfo>` for Gozer. (Gozer's docs are missing the tag, and I am filing a PR to add it.)
Gozer is the only design with no options. All other existing designs have at least one option, which is why we haven't seen the issue before.
(The added blank line 370 is for visual whitespace to separate the parts and plugins sections, to make the code easier to read.)

fix(shared): Adjust <DesignInfo> to accommodate designs with no design options

---

markdown/dev/guides/markdown/custom-components/en.md

A major edit of the Custom Tags guide.
Fixes #3312.

chore(markdown): Add missing tags to Custom Tags guide

---

markdown/dev/reference/api/svg/asrenderprops/en.md
markdown/dev/reference/api/svg/render/en.md

Also a small grammar fix in `Svg.asRenderProps()`.
(This fixes half of Issue #3193. The other half will be addressed in a separate PR.)
Edit: Added:
The other half of #3193 was subsequently merged via #5900. As a result, this PR now closes #3193.

chore(markdown): Add Svg.render() documentation

---

.github/workflows/playwright.yml
.github/workflows/tests.new-design.yml

Every time I sync my personal fork from freesewing/freesewing, GitHub sends me 2 workflow failure notifications:
```
.github/workflows/playwright.yml workflow run failed for develop branch
.github/workflows/tests.new-design.yml workflow run failed for develop branch
```
The failures and notifications occur because the content of the two workflows was commented out. Specifically, GitHub is expecting to see an `on:` section in the file:
```
[Error: .github#L1]
No event triggers defined in `on`
```
This fix adds noop jobs to the workflows as a temporary workaround. I imagine that eventually the workflows will be updated to work with v3. Or, perhaps they will be removed from the repository instead.
Edit: Added:
Or, perhaps this PR isn't necessary. I just found out that workflows can be …

fix(github): Add noop jobs to workflows to prevent spurious notifications

---

packages/core/src/stack.mjs

I noticed that the `anchor` property gets added only when/after `Stack.home()` was called.
(No docs updates are needed. The `anchor` property is already listed in the `Stack` Core API doc.)

fix(core): Add missing anchor property to Stack() constructor

---

markdown/dev/reference/api/part/en.md
markdown/dev/reference/api/path/en.md

Added properties and methods info to the Part doc.
(The methods are manually added because `<ReadMore />` would catch the config and draft directories.)

fix(markdown): In Part doc, add properties and methods

---

config/changelog.yaml
markdown/dev/reference/api/path/combine/en.md
markdown/dev/reference/api/path/length/en.md
packages/core/src/path.mjs
packages/core/tests/path.test.mjs
packages/core/tests/pattern-draft.test.mjs
sites/dev/jargon.mjs

The discussion in #5976 is whether `Path.join()` should use a line segment to close any gaps in the path caused by move operations, or by differences in the end and start points of paths being joined.
The answer is yes, that is the intended behaviour, but people who read _join_ might expect differently.
So I have made a few changes to clarify this:
- The new `Path.combine()` method combines multiple path instances into a single instance without making any changes to the drawing operations
- Since `Path.combine()` is variadic, I have also updated `Path.join()` to be variadic too, since that is more consistent.
- The old way of calling `Path.join(path, bool)` is deprecated and will log a warning. Calling `Path.join()` this way will be removed in v4.
- Related to this change is how …

feat(core): Added Path.combine and related changes, closes #5976

---

config/changelog.yaml
designs/brian/src/base.mjs

Originally, #5999 was filed to report issues with the sleeve on Jaeger not responding to biceps ease as expected. Increasing the biceps ease would actually make the sleeve more narrow.
Turns out, this is a side-effect of the way the armhole depth is calculated in v3. We used to take the biceps measurement (and ease) for that, but now we rely on the waist to armpit measurements.
In brain, we used this new measurements along with the armholeDepthFactor option to locate the bottom of the armhole. This means that when we change the biceps ease, nothing will change in the briam armhole, which means the total sleevecap length target remains unchanges.
However, in Jaeger, increased biceps ease causes a taller sleevecap, and since the total target sleevecap length (inherited from Brian) remains …

fix(brian): Take biceps ease into account for armhole depth

---

designs/tristan/i18n/en.json
markdown/org/showcase/a-lined-tristan-top-with-front-lacing/en.md
markdown/org/showcase/a-noble-top-for-the-renaissance-festival/en.md

Moved two showcases from Noble to Tristan.
Updated name from "Tristan" to "Tristan top" on Designs page.

Updated Tristan design name and showcases

---

markdown/dev/reference/api/attributes/en.md
markdown/dev/reference/api/defs/en.md

It was unclear to me whether the omission of the `list` property from the Attributes and Defs docs was intentional or not. Because `list` is an Enumerable property, I thought that perhaps the omission was accidental.
But, if the omission was intentional, please just close this PR.

fix(markdown): Add missing list property to Attributes and Defs docs

---

markdown/dev/tutorials/getting-started-windows/en.md

Corrected a 404 link. The previous `.node-version` file was removed some time ago.
_(I'm still thinking about a long-term fix and messaging for the acceptable/recommended Node.js versions issue. It would be easier to maintain if we had this documented in just one place, instead of in every tutorial.)_

fix(markdown): In Windows tutorial, change link from .node-version to .nvmrc

---

sites/shared/components/workbench/exporting/export-handler.mjs
sites/shared/components/workbench/exporting/export-worker.js
sites/shared/components/workbench/exporting/pdf-maker.mjs

Resolves #5332.
This PR adds information to the PDF coversheet.

feat(shared): Add pattern information to PDF cover sheet

---

sites/shared/prebuild/markdown.mjs

fix(shared): Blog navigation menu in reverse chronological order

---

sites/shared/components/account/sets.mjs
sites/shared/components/workbench/views/measies/index.mjs

Resolves #5915.
Clicking on a measurement set with missing measurements directs to the measies view. There functionality already exists to tell the user which measurements are missing. Users can then Edit Measurements by Hand to provide the missing measurements.

feat(shared): Allow missing measurement sets to be selected for new patterns

---

sites/shared/components/measurements/image.mjs

The issue was introduced in 3bca940.
It was reported on Discord:
https://discord.com/channels/698854858052075530/1206763279989608479/1206763279989608479
discord://discord.com/channels/698854858052075530/1206763279989608479/1206763279989608479

fix(shared): Correct MeasieImage width and source URL

---

markdown/dev/reference/api/part/config/options/extend/en.md
sites/shared/utils.mjs

This PR adds new, optional, functionality to the workbench UI and to the `Part` configuration options to allow Design Options menus and options to be placed in a specific order.
Basically, there is a new, optional `order` attribute that can be added to an `options` entry. If present, the UI will use it to order the option and its `menu`. This new functionality is explained in the updated documentation, also included in this PR.
This PR does not introduce any new behavior for existing designs. The PR does not change source code for existing FreeSewing designs. These designs will continue to have their Design Options menus and entries ordered in the same way they have been. It is up to pattern designers to decide whether they want to use this new functionality by adding `order` attributes …

feat(shared): Optional ordering for design options and menus

---

packages/models/tests/models.test.mjs
sites/backend/tests/shared.mjs

`yarn test` was encountering errors:
```sh
✖  @freesewing/models:test
$ npx mocha tests/*.test.mjs
file:///.../packages/models/tests/models.test.mjs:1
import chai from 'chai'
^^^^
SyntaxError: The requested module 'chai' does not provide an export named 'default'
```
```sh
✖  backend.freesewing.org:test
$ npx mocha --require mocha-steps tests/index.mjs
file:///.../freesewing/sites/backend/tests/shared.mjs:3
import chai from 'chai'
^^^^
SyntaxError: The requested module 'chai' does not provide an export named 'default'
```

fix(models, backend): In tests, use chai namespace import instead of default

---

markdown/org/docs/designs/lucy/cutting/en.md
markdown/org/docs/designs/lucy/fabric/en.md
markdown/org/docs/designs/lucy/instructions/en.md
markdown/org/docs/designs/lucy/needs/en.md
markdown/org/docs/designs/lucy/options/edge/en.md
markdown/org/docs/designs/lucy/options/length/en.md
markdown/org/docs/designs/lucy/options/width/en.md

These files seem to have been caught in the crossfire of fixing crowing issues with uppercased files. This reverts those changes.

fix(markdown): Roll back crowding accidental removals

---

sites/shared/components/workbench/views/measies/editor.mjs

(There is an analogous situation with Account -> Create a new measurements set -> Edit Measurement Sets -> Filter by Design where optional measurement fields aren't seen. For example, if you select Brian you don't get the opportunity to enter the optional `highBust` measurement. That other situation is not addressed by this PR.)
How things look with the PR, with a variety of designs:

fix(shared): Add optional measurements to pattern Edit Measurements by Hand

---

plugins/plugin-annotations/src/title.mjs
sites/shared/components/workbench/exporting/export-handler.mjs
sites/shared/components/workbench/exporting/export-worker.js
sites/shared/components/workbench/exporting/pdf-maker.mjs
sites/shared/components/workbench/new.mjs
sites/shared/components/workbench/views/measies/index.mjs

Closes #6051.
This PR:
- Passes measurement set name to the pattern, so the `title` macro can display it.
- Also adds the measurement set name to the PDF cover sheet.
- Makes some changes to the PDF cover sheet, how things are formatted/presented.
Please note that this PR introduces a new `settings.metadata.setName` setting which is not a part of Core. I felt that I had to do this to be able to provide the set name to the export handler. Otherwise the `title` macro would display "ephemeral" on PDFs. (If there is a different way to do this without introducing the non-official, non-Core setting, this PR can be rewokred to do so.)

fix(shared, plugins): Provide measurement set name to patterns

---

config/changelog.yaml
designs/brian/src/base.mjs
markdown/dev/reference/hooks/predraft/en.md
markdown/dev/reference/hooks/presetdraft/en.md
plugins/plugin-bust/src/index.mjs
plugins/plugin-bust/tests/plugin.test.mjs
sites/shared/components/curated-sets.mjs

The `plugin-bust` plugin is used to draft designs for high bust rather than full chest circumference. To facilitate that, we provide(d) a named export called `withCondition` that checks whether the plugin is wanted, and if so loads it.
Problem with that is that the conditional loading of a plugin applied to the entire pattern. And since we support drafting patterns for multiple sets (and use this to sample) this means that all of these sets would either get the plugin effect or not, based on the first set.
So, to fix that, we have changed the lifecycle hook used by this plugin to `preSetDraft` (from `preDraft`) and changed the `withCondition` method to always return true.
This means that the plugin will always be loaded, and we have moved the check that used to be in `withCondition` to …

feat: Changes to handle per-set bust plugin conditionality

---

config/changelog.yaml
designs/onyx/src/base.mjs
designs/shelly/src/base.mjs
designs/tamiko/src/top.mjs

(I was seeing 3x `WARNING: The 'withCondition' named export...` messages being printed to the console when the localhost lab started up and also while it was running. I think that the lab was loading all the designs upon start and also reloading them at other times?)

chore(onyx, shelly, tamiko): Load bustPlugin unconditionally

---

designs/hugo/i18n/en.json
designs/hugo/src/waistband.mjs

Fixes #6085.
Also added missing grainline info to expand flag details.
After:

fix(hugo): Correct waistband grainline direction

---

markdown/org/docs/about/site/account/compare/en.md
sites/shared/components/account/en.yaml

I felt that "Measurements Sets Comparison" might be a better and easier-to-understand name than "Metricset Comparison".

(shared, markdown): Rename Metricset Comparison to Measurements Sets Comparison

---

markdown/dev/reference/api/utils/deg2rad/en.md
markdown/dev/reference/api/utils/generatestacktransform/en.md
markdown/dev/reference/api/utils/gettransformedbounds/en.md
markdown/dev/reference/api/utils/mergei18n/en.md
markdown/dev/reference/api/utils/mergeoptions/en.md
markdown/dev/reference/api/utils/rad2deg/en.md

Some corrections to `utils` docs and changes to "normalize" the newer docs so they match the naming and formatting of the older ones.
Previously, some were named differently, throwing off the sorting. Before:

fix(markdown): Correct and normalize utils docs

---

sites/shared/components/account/en.yaml
sites/shared/components/account/links.mjs

Added missing translation keys for social media. This allows stylized capitalization like for "GitHub" and "TikTok".
Also removed forced capitalization of social media names, to allow for the possibility of some future social media that might style its name with an initial lowercase letter. 
After:
Before:

fix(shared): Add translation keys for social media

---

sites/shared/components/workbench/exporting/export-handler.mjs

A FreeSewing user discovered that Export for Editing PDFs were not generating, even though Export for Printing PDFs were:
https://discord.com/channels/698854858052075530/1208712564456820766/1208712564456820766
discord://discord.com/channels/698854858052075530/1208712564456820766/1208712564456820766
The coversheet `workerArgs.strings` variable was being initialized only for "Export for Printing" PDFs, resulting in an uninitialized variable error that resulted in the issue.
The error was introduced when I added extra `workerArgs.strings` for additional PDF coverpage info.

fix(shared): Export for Editing PDF files are not generating

---

sites/lab/components/jargon.mjs

The localhost lab needed the new jargon file to be able to run.

fix(lab): Add jargon file

---

sites/shared/components/workbench/menus/ui-settings/en.yaml
sites/shared/components/workbench/views/draft/menu.mjs

This PR adds a new tip message to the right menu, for User Experience levels 1, 2, and 3, with a different message for each level. No tip is displayed for User Experience levels 4 and 5.
This PR closes #6103. The new tip should help users locate settings that have been hidden, like Seam Allowance.

fix(shared): Add Missing Settings? tip to pattern draft right menu

---

sites/shared/components/workbench/exporting/export-handler.mjs
sites/shared/components/workbench/views/exporting/index.mjs
sites/shared/i18n/status/en.yaml

This PR addresses the issue that the "Nailed it!" success message is seen when an export fails. It defines an additional `stopLoadingFail()` method and calls the appropriate method in the event listener depending on success or failure.
It also removes a `stopLoading()` call upon failure during the setup phase which is also currently showing the "Nailed it!" success message upon failure: 
- I removed this setup failure `stopLoading()` entirely instead of simply changing it to `stopLoadingFail()`. This is because doing so could result in a situation where a "Failed" message is seen (during setup) immediately followed by a "Nailed it!" success message, a situation where there is an error during setup that doesn't stop the export from succeeding.
- With the removal of this `stopLoading()` …

fix(shared): Nailed it! seen on export failure

---

sites/shared/components/workbench/views/draft/header.mjs

I noticed that the kiosk and renderer buttons weren't under User Experience control.
Before:
After:

fix(shared): In draft header, show/hide kiosk and renderer buttons based on User Experience

---

sites/shared/components/workbench/views/draft/header.mjs

The monochrome theme was the only one where the UE buttons blend into the background.
Before:
After:
The enabled Reset Options button also blends into the background.  (The disabled button shows up just fine.)
Before:
After:

fix(shared): Override draft UI button colors for monochrome theme

---

sites/shared/components/sponsors/en.yaml
sites/shared/i18n/support/en.yaml

Corrected the Discord channel name to "need-help".
Also contains a small fix to correct the stylized capitalization of "BugSnag".

fix(shared): Correct Discord support channel name

---

sites/shared/components/account/sets.mjs

This partially addresses #5646 by fixing the first issue.

fix(shared): Create new measurements sets using account imperial setting

---

sites/shared/components/workbench/views/test/menu.mjs

- Optional measurements were missing from Test View. This PR adds them.
- It also uses translations and sorts measurements by translated name.
After (`highBust` has been added, `neck` translation temporarily changed to "Zeck circumference" for testing purposes):
Before (`highBust` missing, no translations):

fix(shared): In Test view, include optional measurements

---

sites/shared/components/workbench/views/test/menu.mjs

Before (no translations for menu and submenu names):
After (translations from Workbench (Fit and Pockets) and from the Charlie i18n files (with some test translation keys added for `backpockets` and `frontpockets`) :
The translation keys used for testing:

fix(shared): For Test view option menus, use design and workbench translation keys

---

sites/shared/components/account/en.yaml
sites/shared/components/account/sets.mjs

This PR adds a text message to the Edit Measurements page as a workaround for the second issue of #5646.

fix(shared): Workaround for Units not updating on edit measurements page

---

markdown/dev/tutorials/pattern-design/part1/new-design/en.md

There seemed to be a "doc escape" for a user recently, where they had difficulty setting up their Windows system using the pattern design tutorial. This PR adds links to the setup tutorials to hopefully help in this type of situation.
https://discord.com/channels/698854858052075530/698862765053575188/1212401887924592730
discord://discord.com/channels/698854858052075530/698862765053575188/1212401887924592730

fix(markdown): In pattern design tutorial, add links to setup tutorials

---

sites/org/components/layouts/post.mjs

I am not sure, but I think that this code change might fix the incorrect label?
Before:

fix(org): Correct showcase author claim label

---

designs/uma/src/back.mjs
designs/uma/src/base.mjs
designs/uma/src/front.mjs

Fixes #6239
The main fix is the reuse of the existing path in designs/uma/src/back.mjs instead of building an (inferior) copy, the rest is minor code style improvement or removal of useless code (in front.mjs)

fix(uma): fix back exposure if expand is off

---

designs/brian/i18n/en.json

Closes #6118.
New wording:
Wording based on input and feedback from Discord:
https://discord.com/channels/698854858052075530/1209868328408059954/1210033408772800543
discord://discord.com/channels/698854858052075530/1209868328408059954/1210033408772800543
https://discord.com/channels/698854858052075530/1209868328408059954/1211329125558779935
discord://discord.com/channels/698854858052075530/1209868328408059954/1211329125558779935
This PR affects only the wording seen in the UI. There is a related Issue #6124 to write the documentation page for the Draft for High Bust option.

fix(brian): Reword description for Draft for High Bust option

---

markdown/org/docs/about/terms/en.md
sites/dev/components/jargon.mjs
sites/org/components/jargon.mjs
sites/shared/components/jargon.mjs
sites/shared/components/mdx/index.mjs
sites/shared/i18n/docs/en.yaml

Inspired by the proposed documentation changes in #6230 I have added a new component and documentation pages that list the various terms.

feat: Add terminoloy/glossary page and component

---

markdown/dev/guides/markdown/jargon/en.md
sites/shared/prebuild/git.mjs

See #6230.
Taken out the section on adding terms as that is outside the scope of a markdown guide.

chore: Update markdown guide, take out section on adding terms

---

sites/shared/components/workbench/menus/design-options/inputs.mjs

That value is already divided by 100 [here](https://github.com/freesewing/freesewing/blob/e4a07a0c93dd1360fb6bdcd1216ce5cd2d105511/sites/shared/utils.mjs#L206). This causes misreported measurements that are at the default value, see for example the zipper length in Onyx:

fix(shared): No need to divide config.dflt by 100 again

---

sites/shared/components/workbench/pan-zoom-pattern.mjs
sites/shared/components/workbench/views/draft/index.mjs

This fixes problems with pattern translation where the translation inside a pattern we using the UI's i18n instance to do the translation.
That causes issues when the pattern language and UI langauges are different (something we support). Furthermore, we need to load the design's own namespace as the default, and load the annotations plugin namespace and do some other things that are specific to translation inside the patterns.
This resolves that by creating a dedicated i18n instance to handle translation inside patterns.
This unblocks #6340

[shared] fix: Pattern translation in UI

---

designs/wahid/i18n/en.json
designs/wahid/src/back.mjs
designs/wahid/src/front.mjs

* Fix title macro part names, so they are translated properly
* Add a warning when waist and hip reduction are both zero, so no back dart is required
See discussion on discord: https://discord.com/channels/698854858052075530/1217044081822273547/1217044388316975104

Some minor Wahid improvements

---

markdown/org/docs/designs/brian/options/draftforhighbust/en.md
sites/backend/src/models/set.mjs
sites/shared/components/account/sets.mjs
sites/shared/components/designs/info.mjs
sites/shared/components/workbench/en.yaml
sites/shared/hooks/use-account.mjs
sites/shared/utils.mjs

Closes #6121
This adds an extra parameter to the method that generated the menu structure for options to include all options. Which means that conditional options will be sorted under a 'conditional' menu heading.

fix(shared): Include conditional options in docs

---

markdown/org/docs/measurements/waisttoupperleg/en.md

If you haven't done the upper leg circumference measurement yet, or you forgot it exist, measuring to the of of the leg is unclear and would probably lead to a much smaller measurement than intended. (I'd measure to right below my hip bones)

Clarify documentation of waist-to-upper-leg measurement

---

sites/org/pages/account/bookmark.mjs
sites/org/pages/account/pattern.mjs
sites/org/pages/account/set.mjs
sites/shared/components/account/en.yaml

Changes page titles to use singular words, for Bookmark, Pattern, and Measurements Set pages.
Before/after for Patterns:
Before:
After:

fix(org,shared): Use singular words for page titles

---

designs/huey/i18n/en.json
designs/huey/src/cuff.mjs
designs/huey/src/front.mjs
designs/huey/src/waistband.mjs

* Add missing i18n strings for ribbing option
* hide unused ribbing parts when ribbing option is disabled
* add a note about needed zipper length (please check calculation)
* Fixed typo "Hops ease"

fix(huey): Assorted minor fixes and improvements

---

markdown/org/docs/about/site/bookmarks/type/en.md
sites/shared/components/account/en.yaml
sites/shared/components/bookmarks.mjs

Uses the `bookmarkThisThing` translation key that already existed.
Note: This PR adds the "`pattern`" translation key to `sites/shared/components/account/en.yaml`. However, PR #6402 also adds the same `pattern` translation key in a different location in the file. Depending on which PR gets merged first, the other PR might need to be modified to remove the duplicate `pattern` key.
There is already a `page` translation key that exists, so "Bookmark this Documentation" could be changed to "Bookmark this Page", if preferred.
The typo changes "docs" to "doc" which is the actual bookmark type.
After:
Before:

fix(shared): Use "Bookmark this" translation strings

---

sites/shared/components/workbench/views/logs/en.yaml

fix(shared): Correct warning logs translation key name

---

markdown/dev/howtos/design/trace/en.md

- Pre-render function updated in accordance with plugin instruction
- Anchor point definition added
- Missing closing parenthesis added
- Plugin bundle reference removed for easier code copy / paste

Patch on the trace instructions

---

designs/teagan/src/sleeve.mjs

This extra path causes extra-thick rendering of the sleevecap in brian (and maybe problems for laser cutters)

fix(teagan): Hide sleevecap path from brian

---

markdown/dev/reference/api/path/rotate/en.md
packages/core/src/path.mjs
packages/core/src/utils.mjs
packages/core/tests/path.test.mjs

I found a function like this very helpful in my Umbra and Tina designs. Sometimes you can't practically rotate the individual control of a path points because the path itself can be composed of multiple lines/curves that might have been splitted, and so on.

add(core): Add Path.rotate(...) function analogue to Point.rotate(...)

---

sites/org/pages/admin/subscribers.mjs
sites/shared/components/mdx/index.mjs
sites/shared/components/mdx/spoiler.mjs
sites/shared/styles/globals.css

Fixes #6005
Based on the code by @BenJamesBen from the issue
[Demo](https://github.com/freesewing/freesewing/assets/4310707/16be03ce-c979-4949-8326-0b64ceacb10e)
Usage: Just put whatever you want to hide (text, images, ...) inside 
```
<Spoiler>
....
</Spoiler>
```

Add <Spoiler> tag for markdown content

---

markdown/dev/howtos/design/seam-allowance/en.md

The function Path.setRender() was used in the how-to "Add seam allowance and/or hem allowance". 
As far as I can tell this function doesn't exist anymore and isn't documented anywhere and I replaced it with Path.hide().
I am not quite sure if it makes sense to use Path.hide() here or if there is a more resource efficient option to not render the same path twice.

Replace .setRender() with .hide()

---

packages/core/src/path.mjs
packages/core/tests/path.test.mjs

Path.offset(...) no longer fails on very short curves or zero length paths. Fixes #6519
Also fixed bbox calculation of another degenerate case (path objects without line or curve, e.g. as a result of cleaning up a very short path)

fix(core): Path.offset(...) improvements

---

sites/shared/prebuild/markdown.mjs

Vercel is unhappy because the scan for jargon pages errors, but I honestly don't know why because the command runs just fine locally.
So I've wrapped this in a try ... catch block, but we'll have to await the Vercel build to check whether that resolves the matter.

chore(org): Wrap scan for jargon in try ... catch

---

sites/shared/prebuild/markdown.mjs

When we don't care about the language, use grep directly rather than find first in prebuild script.
This is to sidestep an issue where the vercel build fails because the find+grep combo fails (even though it does find the results).

fix(org): Switch to direct grep rather than find

---

config/software/designs.json
designs/jane/i18n/en.json
designs/jane/src/sleeve.mjs
markdown/org/docs/designs/jane/cutting/en.md
markdown/org/docs/designs/jane/en.md
markdown/org/docs/designs/jane/fabric/en.md
markdown/org/docs/designs/jane/instructions/en.md
markdown/org/docs/designs/jane/measurements/en.md
markdown/org/docs/designs/jane/needs/en.md
markdown/org/docs/designs/jane/options/bicepsease/en.md
markdown/org/docs/designs/jane/options/bodyease/en.md
markdown/org/docs/designs/jane/options/en.md
markdown/org/docs/designs/jane/options/gussetsize/en.md
markdown/org/docs/designs/jane/options/neckdepthback/en.md
markdown/org/docs/designs/jane/options/neckdepthfront/en.md
markdown/org/docs/designs/jane/options/neckwidth/en.md
markdown/org/docs/designs/jane/options/shiftlength/en.md
markdown/org/docs/designs/jane/options/sleevelength/en.md
sites/org/hooks/use-design.mjs
sites/org/pages/account/patterns/jane/edit.mjs
sites/org/pages/new/jane.mjs
sites/shared/components/mdx/index.mjs

This includes wrong names for MDX components, missing content for documentation of design options, and renaming a poorly named option.

fix(jane): Fix various issues with Jane

---

sites/org/components/github/inputs.mjs
sites/shared/components/account/mfa.mjs
sites/shared/components/inputs.mjs
sites/shared/components/patrons/subscribe.mjs
sites/shared/components/workbench/menus/shared/inputs.mjs

Fixes #6542
Also fixes some other small issues:
* duplicate `item_number` input element in patron Paypal code
* replaced invalid `inputMode="number"` with `inputMode="decimal"`
* replaced `disabled={Number(amount) < 1}` with `disabled={!(Number(amount) > 0)}` (an invalid value would be `NaN`, which wouldn't be less than 1.)

Replace input type="number" with input type="text" inputmode="numeric"/"decimal"

---

sites/shared/components/account/en.yaml
sites/shared/components/account/mfa.mjs

I noticed while redoing some of my 2FA things that Freesewing doesn't expose the TOTP secret to the user, except encoded into the QR code. This makes some setups significantly more difficult for no gain, which is why showing the secret as text (either directly or when asked for by the user) is standard.
Side by side of the change:

(feature) Add secret to MFA enable

---

plugins/plugin-ringsector/src/index.mjs

Closes #6792
Adds missing line to ringsector path.
Fixes the issue with Sandy's curved waistband,
Tristan's seam allowance paths are changed here #6798 to accomadate this change.

fix(ringsector) Add missing line to path

---

markdown/org/docs/designs/jane/options/sleevelength/en.md

Causes `yarn build` on `sites/org` to fail.

fix(markdown): close frontmatter properly in Jane documentation

---

markdown/dev/reference/api/path/split/en.md
packages/core/src/path.mjs
packages/core/tests/path.test.mjs

In some edge cases, like when splitting a path on or very close to its
start or end point, `Path.split()` will return an array in which one of
the elements is not a Path object, but rather an empty array.
That is rather combersome to check for, so this changes that behaviour
and will return null for such cases.
I've also updated the documentation to clarify this behaviour.
Fixes #6816
This also fixes a bug when a path was being split on its end point.

fix(core): Handle path splits on start or end points

---

designs/opal/src/back.mjs
designs/opal/src/front.mjs
markdown/org/docs/designs/onyx/needs/en.md

Fixes a bug in Opal where it was crashing if sa was == 0 and paperless was true.
There were points that are only generated for the seam allowance that were being referred to in the dimension macros. This bug fix remedies this problem.

[Bugfix] Opal

---

designs/lily/i18n/en.json
designs/lily/src/back.mjs

fitKnee was intended to be locked not hidden.
This has been updated on back.mjs and the fitKnee translations have been removed from the i18n file.
Found this whilst working on the Lily docs and didn't want it getting muddled with the documentation work.

fix(lily) Locking fitKnee as intended

---

designs/lily/src/back.mjs

fix errors related to cutting off too close to the fork;
also ensures that capping the cut off does not reduce the length further than any allowed value

[lily] fix errors related to cutting off too close to the fork

---

config/changelog.yaml
designs/charlie/src/front.mjs
designs/titan/i18n/en.json
designs/titan/src/back.mjs
designs/titan/src/front.mjs

Fixes #6271
This will flag a warning message when the created front waist or back waist is below the cross-seam curve control point and will adjust that control point to be (very slightly) below the waistband in order to not cause weird shapes or follow-up problems in designs like Charlie.
I also added a check in charlie that would fix the crash on its own, but results in a very bad shape.
See discussion in the mentioned issue (including the linked discord thread) for details.

fix(charlie, titan): Handle bad cross-seam-front and waist-to-seat measurements

---

markdown/dev/tutorials/pattern-design/part2/constructing-the-neck-opening/en.md
markdown/dev/tutorials/pattern-design/part3/conclusion/en.md
sites/dev/pages/404.mjs

Closes #6887 and fixes other related problems discovered at the same time.
For the 404 page, I chose the simple [help page](https://freesewing.dev/howtos/help), since if references both Discord and GitHub issues. I don't think it matters too much, so long as it points to something other than another 404 :sweat_smile:

Fix broken links in freesewing.dev

---

packages/core/src/path.mjs

Path.clean() does weird things on paths with curves. Found while messing with Bibi design.

fix(core): Fix typo in path.clean() method

---

markdown/org/docs/about/faq/womenswear-blocks/en.md
sites/org/pages/profile.mjs
sites/shared/components/mdx/meta.mjs
sites/shared/components/support/support.mjs

Closes #6990
Fixes old-style user profile links to align with the new way things work. See the issue for more details.

Fix user profile links

---

designs/charlie/src/beltloops.mjs
designs/charlie/src/waistband.mjs

Cut count of belt loops was hardcoded to 7, when it should follow the option (which defaults to 8, anyway)
Waistband has double seam allowance on the left side, so for the final width the extra width is `1.5 * extraSa`

fix(charlie): adjust messages, so they match the expanded parts

---

sites/backend/src/controllers/apikeys.mjs
sites/backend/src/controllers/bookmarks.mjs
sites/backend/src/controllers/curated-sets.mjs
sites/backend/src/controllers/option-packs.mjs
sites/backend/src/controllers/patterns.mjs
sites/backend/src/controllers/sets.mjs
sites/backend/src/models/pattern.mjs
sites/backend/src/models/subscriber.mjs

According to the code, no result string is used when the response code is 404:
https://github.com/freesewing/freesewing/blob/85214486b500f69c9b9b8417dc8af952c9bd0e07/sites/backend/src/utils/model-decorator.mjs#L241
So, including a result string when calling `setResponse()` does nothing. This PR removes the superfluous result string from `setResponse()` calls to avoid confusion.

fix(backend): 404 errors do not use a result string

---

markdown/dev/reference/plugins/annotations/en.md
markdown/dev/reference/plugins/bin-pack/en.md
markdown/dev/reference/plugins/core/en.md
markdown/dev/reference/plugins/measurements/en.md
markdown/dev/reference/plugins/mirror/en.md
markdown/dev/reference/plugins/round/en.md
markdown/dev/reference/plugins/sprinkle/en.md
markdown/dev/reference/store-methods/pack/en.md

Fixes #5888
1. Adds missing`plugin-bin-pack` documentation.
2. Adds details to the `pack()` store method documentation.
3. Updates note for plugins provided by `core-plugins`

fix(docs): Add plugin-bin-pack doc and update related docs

---

plugins/plugin-ringsector/src/index.mjs

This reverts the ringsector macro changes from #6955 as this caused compatibility problems with some existing designs (which have already been fixed, see #7012) and also potentially with some wip and private designs.
Additionally, some people on Discord wanted to keep these specific control points as they wanted to use them for their future designs.

change(plugins): Revert ringsector changes from #6955

---

designs/opal/src/back.mjs

Fixes a bug where it was possible to attempt to find the intersection of two parallel lines. backBibBaseAngle is now limited to +85 degrees to prevent this.
Closes #7123

Opal: Fixes intersection of parallel lines bug.

---

designs/huey/i18n/en.json
designs/huey/src/front.mjs
markdown/org/docs/designs/huey/options/pocketopening/en.md

This PR adds a pocket opening size option to Huey. The default is 90%, the same as the current design, so there is no default change in the design.
On Discord, a user mentioned that the Huey pocket was somewhat shallow because of the opening, making it easier for items to fall out of the pocket.
https://discord.com/channels/698854858052075530/698854858496802868/1287918139627147287
discord://discord.com/channels/698854858052075530/698854858496802868/1287918139627147287

enhancement(huey): Add pocket opening size option

---

designs/gozer/src/ghost.mjs

Fixes #7059
Changes:
1. Eye line distance from top of head increased from `head circumference / 6.28` to `head circumference / 2.25`.
2. Pupil-to-pupil width decreased from from `head circumference * 0.13` to about `head circumference * 0.079` (1  /  12.7).
(Eye size is unchanged, but I changed how the value was written to `1 / 24` instead of `0.0416` for improved understandability.)
I have not constructed a test garment for these changes. However, the generated pattern has the eyeline at 25.33 cm and the pupil-to-pupil width at 8.98 cm, close to the desired values I estimated using my 57 cm head as a model.
Because PR #6087 will change the positions of the logo and title, this PR ignores the fact that currently they are not optimally placed.

fix(gozer): Adjust position of eyes

---

designs/bent/src/sleeve.mjs

Fixes #6023
This changes the sleeve width algorithm to be based on biceps circumference. Previously the algorithm used a set fraction of the sleeve opening as the sleeve width.
(I am initially filing this as Draft status. I will post to Discord to get feedback on the PR, and within 7 days I will either move this PR out of Draft status or close it entirely.)
Comparing before/after patterns using curated measurements sets, it seems that this new formula produces roughly the same patterns as before. However, as biceps circumference increases, the sleeve width now increases instead of decreasing.

fix(bent): Base sleeve width on biceps circumference

---

designs/bee/src/cup.mjs
designs/bella/i18n/en.json
designs/bella/src/back.mjs
designs/bella/src/front-side-dart.mjs
designs/noble/src/options.mjs
markdown/org/docs/designs/bella/options/waistdartcurve/en.md

1. Adds a `waistDartCurve` option  to Bella's front, to allow straight and convex curved darts.
2. Increases the max length of the waist dart to 100%. 
3. Adds new documentation for the new option.
I didn't generate test sample images for the new option or for the updated option.
The enhancements to Bella's darts were originally requested by a customer.
https://discord.com/channels/698854858052075530/757632180980547686/1113170603701190706
discord://discord.com/channels/698854858052075530/757632180980547686/1113170603701190706

enhancement(bella,docs): Add front waist dart curve option and allow longer waist dart

---

markdown/org/showcase/sleeveless-simon-by-lasermonkey12/en.md

This showcase was attributed to the correct maker name but wrong user ID.

Fix user ID in showcase post

---

designs/bella/src/front-side-dart.mjs

This PR omits Bella's front waist dart if the width of the dart is zero or negative. (Currently, Bella incorrectly draws negative-width waist darts.)
The fix includes the seam line, the seam allowance line, and dimensions. The fix was tested on Noble and Bee to verify that they still work and produce identical patterns before and after the fix.
This measurement set was used to reproduce the issue and test the fix on Bella. It was also used to verify no side effects affecting Noble or Bee:
```yaml
measurements:
highBust: 1000
chest: 1020
underbust: 1000
waist: 1100
waistBack: 550
bustSpan: 200
neck: 400
hpsToBust: 300
hpsToWaistFront: 500
hpsToWaistBack: 500
shoulderToShoulder: 450
shoulderSlope: 15
bustPointToUnderbust: 70
```

fix(bella): Omit zero or negative width front waist dart

---

plugins/plugin-annotations/src/logo.mjs

Closes #3905
The answer is that we want it as outline. When printing the outline requires less ink.
By removing the stroke it is once again in the export.

fix(plugins) Logo missing when Exported to PDF

---

plugins/plugin-ringsector/src/index.mjs

#7069 does not revert the changes to ringsector made by #6955 fully and as results loses the fix from #6799

fix(plugins) ringsector full reversion.

---

package.json
sites/org/next.config.mjs
sites/shared/components/mdx/index.mjs

- Remove references to Web of Trust components that are gone
- Specify execa version explicitly, otherwise you get a random old version from some dependency and versions below 6.0.0 have compatibility issues
- Get rid of @next/bundle-analyzer as it seems to cause build issues and even adding a dependency doesn't seem to work reliably :shrug:

Fix build problems

---

sites/orgdocs/src/theme/MDXComponents/design-info.mjs

The variable `person` was undefined in the scope of the join method.
Related to #7168

fix: Fix DesignInfo mdx component handling of multiple design/code authors

---

sites/orgdocs/src/theme/MDXComponents/design-info.mjs

(The real fix for this type of situation would be to add the missing translation string. However, this PR adds a quality-of-life improvement by displaying the bare translation key instead.)

fix(orgdocs): Use bare key for option menus without translations

---

sites/org/pages/patrons/thanks.mjs

This should hopefully add the space missing between the thanksMsg2 and the email address after it.

fix(org): Add missing space after thanksMsg2

---

sites/shared/components/workbench/menus/shared/menu-item.mjs

Fixes #7037 
(I added only the one, new `control` line. The other indent spacing code changes were made by `prettier`.)

fix(shared): Provide control to menu items to allow User Experience circles to be filled

---

sites/shared/components/workbench/views/print/config.mjs

This PR changes the control levels for all Print Settings to User Experience level 1, in the Print Layout view.
On Discord a user experienced confusion when clicking on "Print Settings" did not reveal any settings as expected. It turned out that their User Experience level was set to 1 and the configured control levels for all print settings were level 2 and higher.
https://discord.com/channels/698854858052075530/1293352270943092798/1293352270943092798
discord://discord.com/channels/698854858052075530/1293352270943092798/1293352270943092798
I am interpreting the situation as a bug, with the root cause being that the print settings control levels are misconfigured. Instead, the correct situation is that all print settings should be level 1. This is my reasoning:
- In the Print Layout view: …

fix(shared): Change print settings to user experience level 1

---

sites/shared/components/designs/design-picker.mjs

This PR sorts design tags and techniques alphabetically by translated name. 
(There are also some code indentation changes, but those changes were added by `prettier`.)

fix(shared): Sort design tags and techniques alphabetically

---

designs/paco/src/front.mjs

The flap position can be calculated more accurately by flipping the flap around the outseam line instead of mirroring it on the y-axis.
Before: 
After:

fix(paco): Use more accurate flap position

---

sites/shared/prebuild/search.mjs

Fixes an error preventing the org development environment from running:
```sh
% yarn start
yarn run v1.22.22
$ yarn prebuild && yarn dev
$ node --conditions=internal --experimental-json-modules ./prebuild.mjs
node:internal/modules/esm/resolve:265
throw new ERR_MODULE_NOT_FOUND(
^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../sites/dev/site.config.mjs' imported from .../sites/shared/prebuild/search.mjs
at finalizeResolution (node:internal/modules/esm/resolve:265:11)
at moduleResolve (node:internal/modules/esm/resolve:933:10)
at defaultResolve (node:internal/modules/esm/resolve:1169:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25)
at ModuleLoader.getModuleJob …
```

fix(shared): Remove dev site config from search

---

packages/core/src/path.mjs
packages/core/src/utils.mjs
packages/core/tests/path.test.mjs
packages/core/tests/utils.test.mjs
sites/dev/docs/reference/api/path/intersects/readme.mdx
sites/dev/docs/reference/api/path/intersectsbeam/readme.mdx
sites/dev/docs/reference/api/path/intersectsx/readme.mdx
sites/dev/docs/reference/api/path/intersectsy/readme.mdx
sites/dev/docs/reference/api/utils/beamintersectsline/readme.mdx
sites/dev/docs/reference/api/utils/beamsintersect/readme.mdx

This is mostly a general collection of fixes and improvements that I discovered why working on the seam allowance macro.
- Add path.intersectsBeam() method
- Add utils.beamIntersectsLine() method
- Simplify calculation and improve precision on beam intersections. A beam intersection situation between two parallel vertical lines going in opposite direction was not detected properly
- Document return types properly
- beamIntersectsCurve now uses the proper function from Bezier library instead of emulating it by constructing a huge line
- docs: path.intersect... methods never return false, they simply return an empty array in case of no intersection. This behavior is unfortunately not consistent between methods, but let's at least document the current behavior.
Note: This might affect …

Fix and improve path intersection methods

---

.gitignore

Before:
```sh
% git status -u
On branch develop
Your branch is up to date with 'origin/develop'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
.nx/workspace-data/58AA42CE-3558-5D47-B9C9-26F06263EF49.db
.nx/workspace-data/58AA42CE-3558-5D47-B9C9-26F06263EF49.db-shm
.nx/workspace-data/58AA42CE-3558-5D47-B9C9-26F06263EF49.db-wal
.nx/workspace-data/d/daemon.log
.nx/workspace-data/file-map.json
.nx/workspace-data/lockfile.hash
.nx/workspace-data/nx_files.nxt
.nx/workspace-data/parsed-lock-file.json
.nx/workspace-data/project-graph.json
nothing added to commit but untracked files present (use "git add" to track)
```

fix(.gitignore): Ignore nx/workspace-data

---

designs/simon/src/yoke.mjs

- Previously it said to cut 1 on the fold, which is wrong. You don't cut the yoke on the fold, it's two pieces.
- Now it says to cut 2 mirrored from main fabric, which is correct.
Bug report that I submitted: https://github.com/freesewing/freesewing/issues/7365
before:
after:

Fix the cutting instructions for the Simon Yoke
